// File: supabase/functions/referral-generate-pdf/index.ts
/**
 * Referral PDF generator (Docito)
 *
 * - Auth required
 * - Patient can download
 * - Referrer and receiver (doctor/clinic/lab/imaging/pharmacy + staff) can download
 * - Super admin can download
 * - Locale-aware (en, ru, uz, tr, ar, ja, ko, zh, es, pt, de)
 * - Includes verification code + verify URL + QR
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, StandardFonts, rgb } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";
// @ts-ignore - optional RTL support
let arabicReshaper: any = null;
// @ts-ignore - optional RTL support
let bidi: any = null;
try {
  arabicReshaper = (await import("https://esm.sh/arabic-reshaper@3.0.0")).default;
  bidi = (await import("https://esm.sh/bidi-js@1.0.3")).default;
} catch {
  // RTL reshaping not available - graceful fallback
}

import {
  secureHandler,
  errorResponse,
  corsHeaders,
} from "../_shared/security-middleware.ts";
import { sanitizeString } from "../_shared/input-validator.ts";
import { DOCITO_LOGO_PNG_BASE64, DOCITO_FONT_TTF_BASE64 } from "./assets.ts";

type Locale = "en" | "ru" | "uz" | "tr" | "ar" | "ja" | "ko" | "zh" | "es" | "pt" | "de";

type PdfRequest = {
  referral_id: string;
  locale?: string;
};

const schema = {
  referral_id: { type: "uuid" as const, required: true },
  locale: { type: "string" as const, required: false, maxLength: 12, sanitize: true, trim: true },
};

const RTL_LOCALES = new Set<Locale>(["ar"]);
const CJK_LOCALES = new Set<Locale>(["ja", "ko", "zh"]);

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    title: "Referral",
    details: "Details",
    clinical: "Clinical",
    timeline: "Timeline",
    workflow: "Workflow",
    files: "Files",
    referralNumber: "Referral number",
    verificationCode: "Verification code",
    verifyUrl: "Verification URL",
    createdAt: "Created",
    updatedAt: "Updated",
    status: "Status",
    priority: "Priority",
    type: "Type",
    referralScope: "Scope",
    targetField: "Target field",
    receiverName: "Receiver name",
    validFrom: "Valid from",
    validUntil: "Valid until",
    patient: "Patient",
    referrer: "Referrer",
    receiver: "Receiver",
    referrerDetails: "Referrer details",
    receiverDetails: "Receiver details",
    reason: "Reason",
    clinicalNotes: "Clinical notes",
    diagnosisCodes: "Diagnosis codes",
    scheduling: "Scheduling",
    preferredDate: "Preferred date",
    preferredTimeSlot: "Preferred time slot",
    estimatedDuration: "Estimated duration",
    sentAt: "Sent",
    acceptedAt: "Accepted",
    rejectedAt: "Rejected",
    completedAt: "Completed",
    rejectionReason: "Rejection reason",
    resultNotes: "Result notes",
    imagingWorkflowStatus: "Imaging workflow status",
    assignedImagingStaffId: "Assigned imaging staff",
    system: "System",
    id: "ID",
    referrerType: "Referrer type",
    receiverType: "Receiver type",
    referrerEntityId: "Referrer entity ID",
    receiverEntityId: "Receiver entity ID",
    referrerUserId: "Referrer user ID",
    receiverUserId: "Receiver user ID",
    name: "Name",
    email: "Email",
    phone: "Phone",
    footer: "Generated by Docito",
    generatedAt: "Generated",
    attachments: "Attachments",
    resultAttachments: "Result attachments",
  },
  ru: {
    title: "Направление",
    details: "Детали",
    clinical: "Клиническая информация",
    timeline: "Хронология",
    workflow: "Процесс",
    files: "Файлы",
    referralNumber: "Номер направления",
    verificationCode: "Код проверки",
    verifyUrl: "Ссылка для проверки",
    createdAt: "Создано",
    updatedAt: "Обновлено",
    status: "Статус",
    priority: "Приоритет",
    type: "Тип",
    referralScope: "Тип направления",
    targetField: "Целевая область",
    receiverName: "Получатель (имя)",
    validFrom: "Действительно с",
    validUntil: "Действительно до",
    patient: "Пациент",
    referrer: "Направивший",
    receiver: "Получатель",
    referrerDetails: "Данные отправителя",
    receiverDetails: "Данные получателя",
    reason: "Причина",
    clinicalNotes: "Клинические заметки",
    diagnosisCodes: "Коды диагноза",
    scheduling: "Запись",
    preferredDate: "Предпочтительная дата",
    preferredTimeSlot: "Предпочтительное время",
    estimatedDuration: "Ожидаемая длительность",
    sentAt: "Отправлено",
    acceptedAt: "Принято",
    rejectedAt: "Отклонено",
    completedAt: "Завершено",
    rejectionReason: "Причина отклонения",
    resultNotes: "Итоговые заметки",
    imagingWorkflowStatus: "Статус (визуализация)",
    assignedImagingStaffId: "Назначенный сотрудник (визуализация)",
    system: "Система",
    id: "ID",
    referrerType: "Тип отправителя",
    receiverType: "Тип получателя",
    referrerEntityId: "ID организации отправителя",
    receiverEntityId: "ID организации получателя",
    referrerUserId: "ID пользователя отправителя",
    receiverUserId: "ID пользователя получателя",
    name: "Имя",
    email: "Email",
    phone: "Телефон",
    footer: "Сгенерировано Docito",
    generatedAt: "Сгенерировано",
    attachments: "Вложения",
    resultAttachments: "Вложения результата",
  },
  uz: {
    title: "Yo‘llanma",
    details: "Tafsilotlar",
    clinical: "Klinik ma’lumot",
    timeline: "Vaqt jadvali",
    workflow: "Jarayon",
    files: "Fayllar",
    referralNumber: "Yo‘llanma raqami",
    verificationCode: "Tekshiruv kodi",
    verifyUrl: "Tekshiruv havolasi",
    createdAt: "Yaratilgan",
    updatedAt: "Yangilangan",
    status: "Holat",
    priority: "Ustuvorlik",
    type: "Turi",
    referralScope: "Ko‘lam",
    targetField: "Yo‘nalish",
    receiverName: "Qabul qiluvchi (ism)",
    validFrom: "Amal qiladi (dan)",
    validUntil: "Amal qiladi (gacha)",
    patient: "Bemor",
    referrer: "Yo‘naltiruvchi",
    receiver: "Qabul qiluvchi",
    referrerDetails: "Yo‘naltiruvchi tafsilotlari",
    receiverDetails: "Qabul qiluvchi tafsilotlari",
    reason: "Sabab",
    clinicalNotes: "Klinik izohlar",
    diagnosisCodes: "Tashxis kodlari",
    scheduling: "Rejalashtirish",
    preferredDate: "Afzal sana",
    preferredTimeSlot: "Afzal vaqt",
    estimatedDuration: "Taxminiy davomiylik",
    sentAt: "Yuborilgan",
    acceptedAt: "Qabul qilingan",
    rejectedAt: "Rad etilgan",
    completedAt: "Yakunlangan",
    rejectionReason: "Rad etish sababi",
    resultNotes: "Natija izohlari",
    imagingWorkflowStatus: "Tasvir statusi",
    assignedImagingStaffId: "Tasvir xodimi",
    system: "Tizim",
    id: "ID",
    referrerType: "Yo‘naltiruvchi turi",
    receiverType: "Qabul qiluvchi turi",
    referrerEntityId: "Yo‘naltiruvchi tashkilot ID",
    receiverEntityId: "Qabul qiluvchi tashkilot ID",
    referrerUserId: "Yo‘naltiruvchi foydalanuvchi ID",
    receiverUserId: "Qabul qiluvchi foydalanuvchi ID",
    name: "Ism",
    email: "Email",
    phone: "Telefon",
    footer: "Docito tomonidan yaratilgan",
    generatedAt: "Yaratilgan",
    attachments: "Ilovalar",
    resultAttachments: "Natija ilovalari",
  },
  tr: {
    title: "Sevk",
    details: "Detaylar",
    clinical: "Klinik",
    timeline: "Zaman çizelgesi",
    workflow: "İş akışı",
    files: "Dosyalar",
    referralNumber: "Sevk numarası",
    verificationCode: "Doğrulama kodu",
    verifyUrl: "Doğrulama URL",
    createdAt: "Oluşturuldu",
    updatedAt: "Güncellendi",
    status: "Durum",
    priority: "Öncelik",
    type: "Tür",
    referralScope: "Kapsam",
    targetField: "Hedef alan",
    receiverName: "Alıcı adı",
    validFrom: "Geçerli (başlangıç)",
    validUntil: "Geçerli (bitiş)",
    patient: "Hasta",
    referrer: "Yönlendiren",
    receiver: "Alıcı",
    referrerDetails: "Yönlendiren detayları",
    receiverDetails: "Alıcı detayları",
    reason: "Gerekçe",
    clinicalNotes: "Klinik notlar",
    diagnosisCodes: "Tanı kodları",
    scheduling: "Planlama",
    preferredDate: "Tercih edilen tarih",
    preferredTimeSlot: "Tercih edilen saat",
    estimatedDuration: "Tahmini süre",
    sentAt: "Gönderildi",
    acceptedAt: "Kabul edildi",
    rejectedAt: "Reddedildi",
    completedAt: "Tamamlandı",
    rejectionReason: "Reddetme nedeni",
    resultNotes: "Sonuç notları",
    imagingWorkflowStatus: "Görüntüleme durumu",
    assignedImagingStaffId: "Atanan personel (görüntüleme)",
    system: "Sistem",
    id: "ID",
    referrerType: "Yönlendiren türü",
    receiverType: "Alıcı türü",
    referrerEntityId: "Yönlendiren kurum ID",
    receiverEntityId: "Alıcı kurum ID",
    referrerUserId: "Yönlendiren kullanıcı ID",
    receiverUserId: "Alıcı kullanıcı ID",
    name: "Ad",
    email: "E-posta",
    phone: "Telefon",
    footer: "Docito tarafından oluşturuldu",
    generatedAt: "Oluşturulma",
    attachments: "Ekler",
    resultAttachments: "Sonuç ekleri",
  },
  ar: {
    title: "إحالة",
    details: "التفاصيل",
    clinical: "سريري",
    timeline: "الجدول الزمني",
    workflow: "سير العمل",
    files: "الملفات",
    referralNumber: "رقم الإحالة",
    verificationCode: "رمز التحقق",
    verifyUrl: "رابط التحقق",
    createdAt: "تاريخ الإنشاء",
    updatedAt: "آخر تحديث",
    status: "الحالة",
    priority: "الأولوية",
    type: "النوع",
    referralScope: "النطاق",
    targetField: "المجال المستهدف",
    receiverName: "اسم المستلم",
    validFrom: "صالح من",
    validUntil: "صالح حتى",
    patient: "المريض",
    referrer: "المرسِل",
    receiver: "المستلم",
    referrerDetails: "تفاصيل المرسِل",
    receiverDetails: "تفاصيل المستلم",
    reason: "السبب",
    clinicalNotes: "ملاحظات سريرية",
    diagnosisCodes: "رموز التشخيص",
    scheduling: "الجدولة",
    preferredDate: "التاريخ المفضل",
    preferredTimeSlot: "الفترة الزمنية المفضلة",
    estimatedDuration: "المدة المتوقعة",
    sentAt: "أُرسلت",
    acceptedAt: "قُبلت",
    rejectedAt: "رُفضت",
    completedAt: "اكتملت",
    rejectionReason: "سبب الرفض",
    resultNotes: "ملاحظات النتيجة",
    imagingWorkflowStatus: "حالة التصوير",
    assignedImagingStaffId: "موظف التصوير المعين",
    system: "النظام",
    id: "المعرّف",
    referrerType: "نوع المرسِل",
    receiverType: "نوع المستلم",
    referrerEntityId: "معرّف جهة المرسِل",
    receiverEntityId: "معرّف جهة المستلم",
    referrerUserId: "معرّف مستخدم المرسِل",
    receiverUserId: "معرّف مستخدم المستلم",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    footer: "تم الإنشاء بواسطة Docito",
    generatedAt: "وقت الإنشاء",
    attachments: "المرفقات",
    resultAttachments: "مرفقات النتيجة",
  },
  ja: {
    title: "紹介状",
    details: "詳細",
    clinical: "臨床",
    timeline: "タイムライン",
    workflow: "ワークフロー",
    files: "ファイル",
    referralNumber: "紹介番号",
    verificationCode: "検証コード",
    verifyUrl: "検証URL",
    createdAt: "作成日",
    updatedAt: "更新日",
    status: "ステータス",
    priority: "優先度",
    type: "種類",
    referralScope: "範囲",
    targetField: "対象分野",
    receiverName: "受領者名",
    validFrom: "有効開始",
    validUntil: "有効期限",
    patient: "患者",
    referrer: "紹介元",
    receiver: "紹介先",
    referrerDetails: "紹介元の詳細",
    receiverDetails: "紹介先の詳細",
    reason: "理由",
    clinicalNotes: "臨床メモ",
    diagnosisCodes: "診断コード",
    scheduling: "スケジュール",
    preferredDate: "希望日",
    preferredTimeSlot: "希望時間帯",
    estimatedDuration: "推定時間",
    sentAt: "送信",
    acceptedAt: "承認",
    rejectedAt: "却下",
    completedAt: "完了",
    rejectionReason: "却下理由",
    resultNotes: "結果メモ",
    imagingWorkflowStatus: "画像ワークフロー",
    assignedImagingStaffId: "担当スタッフ(画像)",
    system: "システム",
    id: "ID",
    referrerType: "紹介元タイプ",
    receiverType: "紹介先タイプ",
    referrerEntityId: "紹介元エンティティID",
    receiverEntityId: "紹介先エンティティID",
    referrerUserId: "紹介元ユーザーID",
    receiverUserId: "紹介先ユーザーID",
    name: "名前",
    email: "メール",
    phone: "電話",
    footer: "Docito により生成",
    generatedAt: "生成日時",
    attachments: "添付",
    resultAttachments: "結果添付",
  },
  ko: {
    title: "의뢰서",
    details: "세부 정보",
    clinical: "임상",
    timeline: "타임라인",
    workflow: "워크플로",
    files: "파일",
    referralNumber: "의뢰 번호",
    verificationCode: "검증 코드",
    verifyUrl: "검증 URL",
    createdAt: "생성",
    updatedAt: "업데이트",
    status: "상태",
    priority: "우선순위",
    type: "유형",
    referralScope: "범위",
    targetField: "대상 분야",
    receiverName: "수신자 이름",
    validFrom: "유효 시작",
    validUntil: "유효 종료",
    patient: "환자",
    referrer: "의뢰자",
    receiver: "수신자",
    referrerDetails: "의뢰자 상세",
    receiverDetails: "수신자 상세",
    reason: "사유",
    clinicalNotes: "임상 노트",
    diagnosisCodes: "진단 코드",
    scheduling: "일정",
    preferredDate: "선호 날짜",
    preferredTimeSlot: "선호 시간대",
    estimatedDuration: "예상 시간",
    sentAt: "발송",
    acceptedAt: "수락",
    rejectedAt: "거절",
    completedAt: "완료",
    rejectionReason: "거절 사유",
    resultNotes: "결과 노트",
    imagingWorkflowStatus: "영상 워크플로",
    assignedImagingStaffId: "담당자(영상)",
    system: "시스템",
    id: "ID",
    referrerType: "의뢰자 유형",
    receiverType: "수신자 유형",
    referrerEntityId: "의뢰 기관 ID",
    receiverEntityId: "수신 기관 ID",
    referrerUserId: "의뢰 사용자 ID",
    receiverUserId: "수신 사용자 ID",
    name: "이름",
    email: "이메일",
    phone: "전화",
    footer: "Docito 생성",
    generatedAt: "생성 시간",
    attachments: "첨부",
    resultAttachments: "결과 첨부",
  },
  zh: {
    title: "转诊单",
    details: "详情",
    clinical: "临床",
    timeline: "时间线",
    workflow: "流程",
    files: "文件",
    referralNumber: "转诊编号",
    verificationCode: "验证代码",
    verifyUrl: "验证链接",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    status: "状态",
    priority: "优先级",
    type: "类型",
    referralScope: "范围",
    targetField: "目标领域",
    receiverName: "接收方名称",
    validFrom: "有效期开始",
    validUntil: "有效期结束",
    patient: "患者",
    referrer: "转出方",
    receiver: "接收方",
    referrerDetails: "转出方详情",
    receiverDetails: "接收方详情",
    reason: "原因",
    clinicalNotes: "临床备注",
    diagnosisCodes: "诊断代码",
    scheduling: "预约",
    preferredDate: "偏好日期",
    preferredTimeSlot: "偏好时间段",
    estimatedDuration: "预计时长",
    sentAt: "已发送",
    acceptedAt: "已接受",
    rejectedAt: "已拒绝",
    completedAt: "已完成",
    rejectionReason: "拒绝原因",
    resultNotes: "结果备注",
    imagingWorkflowStatus: "影像流程状态",
    assignedImagingStaffId: "指派影像人员",
    system: "系统",
    id: "ID",
    referrerType: "转出方类型",
    receiverType: "接收方类型",
    referrerEntityId: "转出方机构ID",
    receiverEntityId: "接收方机构ID",
    referrerUserId: "转出方用户ID",
    receiverUserId: "接收方用户ID",
    name: "姓名",
    email: "邮箱",
    phone: "电话",
    footer: "由 Docito 生成",
    generatedAt: "生成时间",
    attachments: "附件",
    resultAttachments: "结果附件",
  },
  es: {
    title: "Derivación",
    details: "Detalles",
    clinical: "Clínico",
    timeline: "Cronología",
    workflow: "Flujo de trabajo",
    files: "Archivos",
    referralNumber: "Número de derivación",
    verificationCode: "Código de verificación",
    verifyUrl: "URL de verificación",
    createdAt: "Creado",
    updatedAt: "Actualizado",
    status: "Estado",
    priority: "Prioridad",
    type: "Tipo",
    referralScope: "Alcance",
    targetField: "Campo objetivo",
    receiverName: "Nombre del receptor",
    validFrom: "Válido desde",
    validUntil: "Válido hasta",
    patient: "Paciente",
    referrer: "Remitente",
    receiver: "Receptor",
    referrerDetails: "Detalles del remitente",
    receiverDetails: "Detalles del receptor",
    reason: "Motivo",
    clinicalNotes: "Notas clínicas",
    diagnosisCodes: "Códigos de diagnóstico",
    scheduling: "Programación",
    preferredDate: "Fecha preferida",
    preferredTimeSlot: "Horario preferido",
    estimatedDuration: "Duración estimada",
    sentAt: "Enviado",
    acceptedAt: "Aceptado",
    rejectedAt: "Rechazado",
    completedAt: "Completado",
    rejectionReason: "Motivo del rechazo",
    resultNotes: "Notas del resultado",
    imagingWorkflowStatus: "Estado de imagen",
    assignedImagingStaffId: "Personal asignado (imagen)",
    system: "Sistema",
    id: "ID",
    referrerType: "Tipo de remitente",
    receiverType: "Tipo de receptor",
    referrerEntityId: "ID entidad remitente",
    receiverEntityId: "ID entidad receptora",
    referrerUserId: "ID usuario remitente",
    receiverUserId: "ID usuario receptor",
    name: "Nombre",
    email: "Email",
    phone: "Teléfono",
    footer: "Generado por Docito",
    generatedAt: "Generado",
    attachments: "Adjuntos",
    resultAttachments: "Adjuntos del resultado",
  },
  pt: {
    title: "Encaminhamento",
    details: "Detalhes",
    clinical: "Clínico",
    timeline: "Linha do tempo",
    workflow: "Fluxo de trabalho",
    files: "Arquivos",
    referralNumber: "Número do encaminhamento",
    verificationCode: "Código de verificação",
    verifyUrl: "URL de verificação",
    createdAt: "Criado",
    updatedAt: "Atualizado",
    status: "Status",
    priority: "Prioridade",
    type: "Tipo",
    referralScope: "Escopo",
    targetField: "Área alvo",
    receiverName: "Nome do destinatário",
    validFrom: "Válido a partir de",
    validUntil: "Válido até",
    patient: "Paciente",
    referrer: "Remetente",
    receiver: "Destinatário",
    referrerDetails: "Detalhes do remetente",
    receiverDetails: "Detalhes do destinatário",
    reason: "Motivo",
    clinicalNotes: "Notas clínicas",
    diagnosisCodes: "Códigos de diagnóstico",
    scheduling: "Agendamento",
    preferredDate: "Data preferida",
    preferredTimeSlot: "Horário preferido",
    estimatedDuration: "Duração estimada",
    sentAt: "Enviado",
    acceptedAt: "Aceito",
    rejectedAt: "Rejeitado",
    completedAt: "Concluído",
    rejectionReason: "Motivo da rejeição",
    resultNotes: "Notas do resultado",
    imagingWorkflowStatus: "Status de imagem",
    assignedImagingStaffId: "Equipe atribuída (imagem)",
    system: "Sistema",
    id: "ID",
    referrerType: "Tipo do remetente",
    receiverType: "Tipo do destinatário",
    referrerEntityId: "ID da entidade remetente",
    receiverEntityId: "ID da entidade destinatária",
    referrerUserId: "ID do usuário remetente",
    receiverUserId: "ID do usuário destinatário",
    name: "Nome",
    email: "Email",
    phone: "Telefone",
    footer: "Gerado por Docito",
    generatedAt: "Gerado",
    attachments: "Anexos",
    resultAttachments: "Anexos do resultado",
  },
  de: {
    title: "Überweisung",
    details: "Details",
    clinical: "Klinisch",
    timeline: "Zeitachse",
    workflow: "Ablauf",
    files: "Dateien",
    referralNumber: "Überweisungsnummer",
    verificationCode: "Verifizierungscode",
    verifyUrl: "Verifizierungs-URL",
    createdAt: "Erstellt",
    updatedAt: "Aktualisiert",
    status: "Status",
    priority: "Priorität",
    type: "Typ",
    referralScope: "Umfang",
    targetField: "Zielfeld",
    receiverName: "Empfängername",
    validFrom: "Gültig ab",
    validUntil: "Gültig bis",
    patient: "Patient",
    referrer: "Überweiser",
    receiver: "Empfänger",
    referrerDetails: "Details Überweiser",
    receiverDetails: "Details Empfänger",
    reason: "Grund",
    clinicalNotes: "Klinische Notizen",
    diagnosisCodes: "Diagnosecodes",
    scheduling: "Terminplanung",
    preferredDate: "Bevorzugtes Datum",
    preferredTimeSlot: "Bevorzugtes Zeitfenster",
    estimatedDuration: "Geschätzte Dauer",
    sentAt: "Gesendet",
    acceptedAt: "Akzeptiert",
    rejectedAt: "Abgelehnt",
    completedAt: "Abgeschlossen",
    rejectionReason: "Ablehnungsgrund",
    resultNotes: "Ergebnisnotizen",
    imagingWorkflowStatus: "Bildgebung Status",
    assignedImagingStaffId: "Zugewiesenes Personal (Bildgebung)",
    system: "System",
    id: "ID",
    referrerType: "Typ Überweiser",
    receiverType: "Typ Empfänger",
    referrerEntityId: "Entity-ID Überweiser",
    receiverEntityId: "Entity-ID Empfänger",
    referrerUserId: "User-ID Überweiser",
    receiverUserId: "User-ID Empfänger",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon",
    footer: "Erstellt von Docito",
    generatedAt: "Erstellt",
    attachments: "Anhänge",
    resultAttachments: "Ergebnis-Anhänge",
  },
};

function t(locale: Locale, key: string): string {
  return I18N[locale]?.[key] ?? I18N.en[key] ?? key;
}

function normalizeLocale(input?: string): Locale {
  const raw = (sanitizeString(input || "", 12) || "").toLowerCase();
  if (!raw) return "en";
  if (raw.startsWith("ru")) return "ru";
  if (raw.startsWith("uz")) return "uz";
  if (raw.startsWith("tr")) return "tr";
  if (raw.startsWith("ar")) return "ar";
  if (raw.startsWith("ja")) return "ja";
  if (raw.startsWith("ko")) return "ko";
  if (raw.startsWith("zh")) return "zh";
  if (raw.startsWith("es")) return "es";
  if (raw.startsWith("pt")) return "pt";
  if (raw.startsWith("de") || raw.startsWith("deutsch")) return "de";
  return "en";
}

function safeText(v: unknown, max = 1000): string {
  const s = typeof v === "string" ? v : v == null ? "" : String(v);
  return sanitizeString(s, max);
}

function fmtDateTime(input: unknown, locale: Locale): string {
  const s = typeof input === "string" ? input : input instanceof Date ? input.toISOString() : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return safeText(s, 64);

  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mi = String(d.getUTCMinutes()).padStart(2, "0");

  // ISO-like for most locales; dd.mm.yyyy for RU/UZ
  if (locale === "ru" || locale === "uz") return `${dd}.${mm}.${yyyy} ${hh}:${mi} UTC`;
  return `${yyyy}-${mm}-${dd} ${hh}:${mi} UTC`;
}

function fmtDate(input: unknown, locale: Locale): string {
  const s = typeof input === "string" ? input : input instanceof Date ? input.toISOString() : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return safeText(s, 32);

  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  if (locale === "ru" || locale === "uz") return `${dd}.${mm}.${yyyy}`;
  return `${yyyy}-${mm}-${dd}`;
}

function b64ToBytes(b64: string): Uint8Array {
  const clean = (b64 || "").replace(/\s+/g, "");
  const bin = atob(clean);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function fetchBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch font: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}

async function getPrimaryFontBytes(locale: Locale): Promise<Uint8Array> {
  // Arabic + CJK: use Noto fonts.
  if (locale === "ar") {
    return await fetchBytes(
      "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf",
    );
  }

  if (locale === "ja") {
    return await fetchBytes(
      "https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf",
    );
  }

  if (locale === "ko") {
    return await fetchBytes(
      "https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf",
    );
  }

  if (locale === "zh") {
    return await fetchBytes(
      "https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf",
    );
  }

  // Default: bundled DejaVu subset with Cyrillic.
  return b64ToBytes(DOCITO_FONT_TTF_BASE64);
}

function canUseStandardFont(locale: Locale): boolean {
  return locale === "en" || locale === "es" || locale === "pt" || locale === "de";
}

function reshapeAndBidi(text: string, locale: Locale): string {
  if (locale !== "ar") return text;
  const reshaped = arabicReshaper.reshape(text);
  return bidi.fromString(reshaped);
}

function splitForWrap(text: string, locale: Locale): string[] {
  if (!text) return [];

  // If CJK, wrap by characters.
  if (CJK_LOCALES.has(locale)) return Array.from(text);

  // Otherwise, wrap by whitespace.
  // Keep punctuation attached to avoid odd line breaks.
  return text.split(/\s+/g).filter(Boolean);
}

function wrapText(
  raw: string,
  font: any,
  fontSize: number,
  maxWidth: number,
  locale: Locale,
): string[] {
  const text = (raw || "").replace(/\r\n/g, "\n");
  if (!text) return [];

  const lines: string[] = [];
  const paragraphs = text.split("\n");

  const measure = (s: string) => {
    try {
      return font.widthOfTextAtSize(s, fontSize);
    } catch {
      return s.length * (fontSize * 0.6);
    }
  };

  const breakLongToken = (token: string): string[] => {
    const chars = Array.from(token);
    const out: string[] = [];
    let cur = "";
    for (const ch of chars) {
      const next = cur + ch;
      if (cur && measure(next) > maxWidth) {
        out.push(cur);
        cur = ch;
      } else {
        cur = next;
      }
    }
    if (cur) out.push(cur);
    return out.length ? out : [token];
  };

  for (const p of paragraphs) {
    const para = p || "";
    if (!para.trim()) {
      lines.push("");
      continue;
    }

    const tokens = splitForWrap(para.trim(), locale);
    let current = "";

    for (const tok of tokens) {
      const tokenParts = measure(tok) > maxWidth ? breakLongToken(tok) : [tok];
      for (const part of tokenParts) {
        const sep = current ? (CJK_LOCALES.has(locale) ? "" : " ") : "";
        const nextLine = current + sep + part;

        if (!current) {
          current = part;
          continue;
        }

        if (measure(nextLine) <= maxWidth) {
          current = nextLine;
        } else {
          lines.push(current);
          current = part;
        }
      }
    }
    if (current) lines.push(current);
  }

  return lines;
}

function safeJson(value: unknown, maxLen = 2000): string {
  if (value == null) return "";
  try {
    const s = JSON.stringify(value, null, 2);
    if (s.length <= maxLen) return s;
    return s.slice(0, maxLen - 3) + "...";
  } catch {
    return safeText(String(value), maxLen);
  }
}

function sanitizeFileName(name: string): string {
  return (name || "document")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[^a-zA-Z0-9._\-\s]/g, "_")
    .slice(0, 120);
}

async function hasEntityAccess(
  service: any,
  userId: string,
  entityType: string,
  entityId: string | null,
): Promise<boolean> {
  if (!entityId) return false;

  const type = (entityType || "").toLowerCase();
  try {
    if (type === "doctor") {
      const { data } = await service
        .from("doctors")
        .select("id")
        .eq("id", entityId)
        .eq("user_id", userId)
        .maybeSingle();
      return !!data;
    }

    if (type === "clinic") {
      // New clinic_staff
      const cs = await service
        .from("clinic_staff")
        .select("id")
        .eq("practice_id", entityId)
        .eq("user_id", userId)
        .eq("status", "active")
        .maybeSingle();
      if (cs.data) return true;

      // Legacy practice_staff
      const ps = await service
        .from("practice_staff")
        .select("id")
        .eq("practice_id", entityId)
        .eq("user_id", userId)
        .eq("status", "active")
        .maybeSingle();
      if (ps.data) return true;

      // Practice admin
      const pa = await service
        .from("practices")
        .select("id")
        .eq("id", entityId)
        .eq("admin_id", userId)
        .maybeSingle();
      return !!pa.data;
    }

    if (type === "lab" || type === "lab_center") {
      const { data } = await service
        .from("lab_staff")
        .select("id")
        .eq("lab_center_id", entityId)
        .eq("user_id", userId)
        .eq("status", "active")
        .maybeSingle();
      if (data) return true;

      const admin = await service
        .from("lab_centers")
        .select("id")
        .eq("id", entityId)
        .eq("admin_id", userId)
        .maybeSingle();
      return !!admin.data;
    }

    if (type === "imaging_center" || type === "imaging") {
      const { data } = await service
        .from("imaging_staff")
        .select("id")
        .eq("imaging_center_id", entityId)
        .eq("user_id", userId)
        .eq("status", "active")
        .maybeSingle();
      if (data) return true;

      const admin = await service
        .from("imaging_centers")
        .select("id")
        .eq("id", entityId)
        .eq("admin_id", userId)
        .maybeSingle();
      return !!admin.data;
    }

    if (type === "pharmacy") {
      const { data } = await service
        .from("pharmacy_staff")
        .select("id")
        .eq("pharmacy_id", entityId)
        .eq("user_id", userId)
        .eq("status", "active")
        .maybeSingle();
      if (data) return true;

      const admin = await service
        .from("pharmacies")
        .select("id")
        .eq("id", entityId)
        .eq("admin_id", userId)
        .maybeSingle();
      return !!admin.data;
    }

    return false;
  } catch {
    return false;
  }
}

serve(async (req) => {
  const { response, context, validatedBody } = await secureHandler(req, "referral-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "expensive",
    validationSchema: schema,
  });

  if (response) return response;
  if (!context || !validatedBody) return errorResponse("Internal server error", 500);

  try {
    const { userId, roles, serviceClient: service } = context;
    const body = validatedBody as PdfRequest;

    // Resolve locale (request > profile > default)
    let locale: Locale = normalizeLocale(body.locale);
    if (!body.locale) {
      const prof = await service
        .from("profiles")
        .select("language")
        .eq("user_id", userId)
        .maybeSingle();
      const inferred = normalizeLocale((prof.data as any)?.language);
      if (inferred) locale = inferred;
    }

    const { data: referral, error: refErr } = await service
      .from("referrals")
      .select(
        `
        id,
        referral_number,
        verification_code,
        patient_id,

        referrer_type,
        referrer_entity_id,
        referrer_user_id,

        receiver_type,
        receiver_entity_id,
        receiver_user_id,

        referral_scope,
        target_field,
        receiver_name,

        referral_type_enum,
        priority,
        status,
        reason,
        clinical_notes,
        diagnosis_codes,
        valid_from,
        valid_until,
        preferred_date,
        preferred_time_slot,
        estimated_duration_minutes,

        attachments,
        sent_at,
        accepted_at,
        rejected_at,
        rejection_reason,
        completed_at,
        result_notes,
        result_attachments,

        created_at,
        updated_at
      `,
      )
      .eq("id", body.referral_id)
      .maybeSingle();

    if (refErr) {
      console.error("referral-generate-pdf: fetch referral error", refErr);
      return errorResponse("Failed to fetch referral", 500);
    }
    if (!referral) return errorResponse("Referral not found", 404);

    // Hydrate patient profile separately (no FK in schema cache for embed)
    let patientProfile: { full_name?: string; email?: string; phone?: string } | null = null;
    if ((referral as any).patient_id) {
      const { data: pp } = await service
        .from("profiles")
        .select("full_name,email,phone")
        .eq("id", (referral as any).patient_id)
        .maybeSingle();
      patientProfile = (pp as any) || null;
    }
    (referral as any).patient = patientProfile;

    // Hydrate referrer / receiver display names (parallel, fail-safe)
    const entityTableFor = (t?: string | null): string | null => {
      switch ((t || "").toLowerCase()) {
        case "clinic": return "clinics";
        case "hospital": return "hospitals";
        case "laboratory":
        case "lab": return "laboratories";
        case "pharmacy": return "pharmacies";
        case "doctor": return "doctors";
        default: return null;
      }
    };
    const fetchUserName = async (uid?: string | null): Promise<string | null> => {
      if (!uid) return null;
      try {
        const { data } = await service.from("profiles").select("full_name").eq("user_id", uid).maybeSingle();
        return ((data as any)?.full_name as string) || null;
      } catch { return null; }
    };
    const fetchEntityName = async (etype?: string | null, eid?: string | null): Promise<string | null> => {
      const tbl = entityTableFor(etype);
      if (!tbl || !eid) return null;
      try {
        const { data } = await service.from(tbl).select("name").eq("id", eid).maybeSingle();
        return ((data as any)?.name as string) || null;
      } catch { return null; }
    };
    const r0: any = referral;
    const [referrerUserName, receiverUserName, referrerEntityName, receiverEntityName] = await Promise.all([
      fetchUserName(r0.referrer_user_id),
      fetchUserName(r0.receiver_user_id),
      fetchEntityName(r0.referrer_type, r0.referrer_entity_id),
      fetchEntityName(r0.receiver_type, r0.receiver_entity_id),
    ]);
    r0.referrer_user_name = referrerUserName;
    r0.receiver_user_name = receiverUserName;
    r0.referrer_entity_name = referrerEntityName;
    r0.receiver_entity_name = receiverEntityName;

    // Authorization: patient, referrer, receiver, or staff/admin of either entity.
    const isSuperAdmin = (roles || []).includes("super_admin");
    const actorId = userId as string;
    const r: any = referral;

    let allowed = false;
    if (isSuperAdmin) allowed = true;
    if (!allowed && r.patient_id === actorId) allowed = true;
    if (!allowed && r.referrer_user_id === actorId) allowed = true;
    if (!allowed && r.receiver_user_id && r.receiver_user_id === actorId) allowed = true;
    if (!allowed) {
      const referrerOk = await hasEntityAccess(service, actorId, r.referrer_type, r.referrer_entity_id);
      const receiverOk = await hasEntityAccess(service, actorId, r.receiver_type, r.receiver_entity_id);
      allowed = referrerOk || receiverOk;
    }

    if (!allowed) return errorResponse("Forbidden", 403);

    const baseUrl = Deno.env.get("PUBLIC_SITE_URL") || "https://docito.app";
    const verifyUrl = `${baseUrl.replace(/\/$/, "")}/verify/referral?ref=${encodeURIComponent(
      r.referral_number,
    )}&code=${encodeURIComponent(r.verification_code)}`;

    const isRtl = RTL_LOCALES.has(locale);

    // PDF setup
    const pdfDoc = await PDFDocument.create();
    let primaryFont: any;
    let boldFont: any;
    if (canUseStandardFont(locale)) {
      primaryFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
      boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    } else {
      pdfDoc.registerFontkit(fontkit);
      const fontBytes = await getPrimaryFontBytes(locale);
      primaryFont = await pdfDoc.embedFont(fontBytes, { subset: true });
      boldFont = primaryFont;
    }

    // Optional logo
    let logo: any = null;
    try {
      const logoBytes = b64ToBytes(DOCITO_LOGO_PNG_BASE64);
      logo = await pdfDoc.embedPng(logoBytes);
    } catch (assetError) {
      console.warn("referral-generate-pdf: skipping logo asset", assetError);
    }
    const qrPngDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 256 });
    const qrBytes = new Uint8Array(await (await fetch(qrPngDataUrl)).arrayBuffer());
    const qrImg = await pdfDoc.embedPng(qrBytes);

    // Brand palette (Docito)
    const brandPrimary = rgb(0.05, 0.36, 0.78);   // #0e5cc7-ish
    const brandSoft    = rgb(0.93, 0.96, 1.0);
    const textColor    = rgb(0.07, 0.09, 0.13);
    const subtleColor  = rgb(0.42, 0.45, 0.52);
    const borderGray   = rgb(0.86, 0.88, 0.92);
    const idColor      = rgb(0.55, 0.58, 0.64);

    const PAGE_W = 595.28;
    const margin = 36;
    const contentW = PAGE_W - margin * 2;

    // Sizes
    const sizeTitle = 18;
    const sizeSection = 11;
    const sizeBody = 10;
    const sizeLabel = 8;
    const sizeId = 7;
    const lineH = 12;

    type DrawCtx = { page: any | null; y: number };

    const text = (ctx: DrawCtx, s: string, x: number, size: number, color: any, font = primaryFont) => {
      const v = reshapeAndBidi(s, locale);
      if (!ctx.page) return;
      const w = font.widthOfTextAtSize(v, size);
      ctx.page.drawText(v, { x: isRtl ? x - w : x, y: ctx.y, size, font, color });
    };

    const wrapped = (ctx: DrawCtx, s: string, x: number, maxW: number, size: number, color: any, font = primaryFont) => {
      const v = reshapeAndBidi(s || "-", locale);
      const lines = wrapText(v, font, size, maxW, locale);
      for (const line of lines) {
        if (ctx.page) {
          const w = font.widthOfTextAtSize(line, size);
          ctx.page.drawText(line, { x: isRtl ? x - w : x, y: ctx.y, size, font, color });
        }
        ctx.y -= lineH;
      }
    };

    const sectionHeader = (ctx: DrawCtx, title: string) => {
      ctx.y -= 8;
      // colored bar + soft fill
      if (ctx.page) {
        ctx.page.drawRectangle({ x: margin, y: ctx.y - 16, width: contentW, height: 18, color: brandSoft });
        ctx.page.drawRectangle({ x: margin, y: ctx.y - 16, width: 3, height: 18, color: brandPrimary });
      }
      const tx = isRtl ? PAGE_W - margin - 8 : margin + 10;
      ctx.y -= 12;
      text(ctx, title, tx, sizeSection, brandPrimary, boldFont);
      ctx.y -= 10;
    };

    const kv = (ctx: DrawCtx, key: string, value: string) => {
      const labelW = 130;
      const xLabel = isRtl ? PAGE_W - margin : margin;
      const xValue = isRtl ? PAGE_W - margin - labelW : margin + labelW;
      const valueMaxW = contentW - labelW;
      // label
      text(ctx, key.toUpperCase(), xLabel, sizeLabel, subtleColor, boldFont);
      // value (wrapped, advances y itself)
      const startY = ctx.y;
      // value baseline lower than label by lineH? we keep aligned: draw value at same y, then move down
      wrapped(ctx, value || "-", xValue, valueMaxW, sizeBody, textColor);
      // ensure at least one line consumed
      if (ctx.y === startY) ctx.y -= lineH;
      ctx.y -= 2;
    };

    const partyCard = (ctx: DrawCtx, title: string, name: string, type: string, extra: string) => {
      const cardH = 46;
      ctx.y -= 4;
      if (ctx.page) {
        ctx.page.drawRectangle({
          x: margin, y: ctx.y - cardH, width: contentW, height: cardH,
          borderColor: borderGray, borderWidth: 0.8, color: rgb(1, 1, 1),
        });
      }
      const xL = isRtl ? PAGE_W - margin - 10 : margin + 10;
      ctx.y -= 13;
      text(ctx, title.toUpperCase(), xL, sizeLabel, brandPrimary, boldFont);
      ctx.y -= 14;
      text(ctx, name || "—", xL, sizeBody + 2, textColor, boldFont);
      ctx.y -= 12;
      text(ctx, [type, extra].filter(Boolean).join("  ·  "), xL, sizeLabel + 1, subtleColor);
      ctx.y -= 12;
    };

    const renderAll = (ctx: DrawCtx) => {
      const startY = ctx.y;

      // Header: logo + title + brand rule
      const logoH = logo ? 28 : 0;
      const logoW = logo ? (logo.width / logo.height) * logoH : 0;
      if (ctx.page && logo) {
        const lx = isRtl ? PAGE_W - margin - logoW : margin;
        ctx.page.drawImage(logo, { x: lx, y: ctx.y - logoH + 4, width: logoW, height: logoH });
      }
      const titleX = isRtl
        ? PAGE_W - margin - (logo ? logoW + 10 : 0)
        : margin + (logo ? logoW + 10 : 0);
      // place title baseline aligned roughly with logo
      const tCtx = { ...ctx };
      tCtx.y = ctx.y - 18;
      text(tCtx, t(locale, "title"), titleX, sizeTitle, textColor, boldFont);
      // tagline / domain on the right
      const taglineX = isRtl ? margin : PAGE_W - margin;
      const taglineCtx = { ...ctx };
      taglineCtx.y = ctx.y - 12;
      text(taglineCtx, "docito.live", taglineX, sizeLabel, subtleColor);
      ctx.y -= Math.max(logoH, 24) + 6;
      // brand rule
      if (ctx.page) {
        ctx.page.drawRectangle({ x: margin, y: ctx.y, width: contentW, height: 1.2, color: brandPrimary });
      }
      ctx.y -= 12;

      // Meta box: referral number + verification code + QR
      const boxH = 78;
      const qrSize = 64;
      if (ctx.page) {
        ctx.page.drawRectangle({
          x: margin, y: ctx.y - boxH, width: contentW, height: boxH,
          borderColor: borderGray, borderWidth: 0.8, color: rgb(0.99, 0.99, 1),
        });
      }
      const qrX = isRtl ? margin + 8 : PAGE_W - margin - qrSize - 8;
      const qrY = ctx.y - 8 - qrSize;
      if (ctx.page) ctx.page.drawImage(qrImg, { x: qrX, y: qrY, width: qrSize, height: qrSize });

      const metaX = isRtl ? PAGE_W - margin - 12 : margin + 12;
      const metaInner = { page: ctx.page, y: ctx.y - 16 };
      text(metaInner, t(locale, "referralNumber").toUpperCase(), metaX, sizeLabel, subtleColor, boldFont);
      metaInner.y -= 14;
      text(metaInner, safeText(r.referral_number, 80) || "—", metaX, sizeBody + 2, textColor, boldFont);
      metaInner.y -= 16;
      text(metaInner, t(locale, "verificationCode").toUpperCase(), metaX, sizeLabel, subtleColor, boldFont);
      metaInner.y -= 12;
      text(metaInner, safeText(r.verification_code, 80) || "—", metaX, sizeBody, textColor);
      ctx.y -= boxH + 10;

      // Party cards: Referrer, Receiver, Patient
      partyCard(
        ctx,
        t(locale, "referrer"),
        r.referrer_user_name || r.referrer_entity_name || "—",
        safeText(r.referrer_type, 40) || "",
        r.referrer_user_name && r.referrer_entity_name ? r.referrer_entity_name : "",
      );
      partyCard(
        ctx,
        t(locale, "receiver"),
        r.receiver_user_name || r.receiver_entity_name || r.receiver_name || "—",
        safeText(r.receiver_type, 40) || "",
        r.receiver_user_name && r.receiver_entity_name ? r.receiver_entity_name : "",
      );
      partyCard(
        ctx,
        t(locale, "patient"),
        safeText(r.patient?.full_name, 120) || "—",
        safeText(r.patient?.email, 120) || "",
        safeText(r.patient?.phone, 60) || "",
      );

      // Details
      sectionHeader(ctx, t(locale, "details"));
      kv(ctx, t(locale, "status"), safeText(r.status, 60) || "-");
      kv(ctx, t(locale, "priority"), safeText(r.priority, 60) || "-");
      kv(ctx, t(locale, "type"), safeText(r.referral_type_enum, 60) || "-");
      kv(ctx, t(locale, "referralScope"), safeText(r.referral_scope, 60) || "-");
      if (r.target_field) kv(ctx, t(locale, "targetField"), safeText(r.target_field, 60));
      kv(ctx, t(locale, "createdAt"), fmtDateTime(r.created_at, locale) || "-");
      if (r.valid_from) kv(ctx, t(locale, "validFrom"), fmtDate(r.valid_from, locale));
      if (r.valid_until) kv(ctx, t(locale, "validUntil"), fmtDate(r.valid_until, locale));

      // Clinical
      sectionHeader(ctx, t(locale, "clinical"));
      kv(ctx, t(locale, "reason"), safeText(r.reason, 2000) || "-");
      if (r.clinical_notes) kv(ctx, t(locale, "clinicalNotes"), safeText(r.clinical_notes, 4000));
      if (r.diagnosis_codes && (Array.isArray(r.diagnosis_codes) ? r.diagnosis_codes.length : true)) {
        kv(ctx, t(locale, "diagnosisCodes"),
           Array.isArray(r.diagnosis_codes) ? r.diagnosis_codes.join(", ") : safeText(r.diagnosis_codes, 500));
      }

      // Scheduling — only if any value
      if (r.preferred_date || r.preferred_time_slot || r.estimated_duration_minutes) {
        sectionHeader(ctx, t(locale, "scheduling"));
        if (r.preferred_date) kv(ctx, t(locale, "preferredDate"), fmtDate(r.preferred_date, locale));
        if (r.preferred_time_slot) kv(ctx, t(locale, "preferredTimeSlot"), safeText(r.preferred_time_slot, 200));
        if (r.estimated_duration_minutes) kv(ctx, t(locale, "estimatedDuration"), `${r.estimated_duration_minutes} min`);
      }

      // Timeline — only show populated rows
      const timelineRows: Array<[string, string]> = [];
      if (r.sent_at) timelineRows.push([t(locale, "sentAt"), fmtDateTime(r.sent_at, locale) || "-"]);
      if (r.accepted_at) timelineRows.push([t(locale, "acceptedAt"), fmtDateTime(r.accepted_at, locale) || "-"]);
      if (r.rejected_at) timelineRows.push([t(locale, "rejectedAt"), fmtDateTime(r.rejected_at, locale) || "-"]);
      if (r.completed_at) timelineRows.push([t(locale, "completedAt"), fmtDateTime(r.completed_at, locale) || "-"]);
      if (r.rejection_reason) timelineRows.push([t(locale, "rejectionReason"), safeText(r.rejection_reason, 1000)]);
      if (r.result_notes) timelineRows.push([t(locale, "resultNotes"), safeText(r.result_notes, 4000)]);
      if (timelineRows.length) {
        sectionHeader(ctx, t(locale, "timeline"));
        for (const [k, v] of timelineRows) kv(ctx, k, v);
      }

      // Footer block: brand line + tiny IDs + generated at
      ctx.y -= 14;
      if (ctx.page) {
        ctx.page.drawRectangle({ x: margin, y: ctx.y, width: contentW, height: 0.8, color: borderGray });
      }
      ctx.y -= 12;
      const footL = `Docito  ·  docito.live`;
      const footR = `${t(locale, "generatedAt")}: ${fmtDateTime(new Date().toISOString(), locale)}`;
      if (ctx.page) {
        const lW = primaryFont.widthOfTextAtSize(footL, sizeLabel);
        const rW = primaryFont.widthOfTextAtSize(footR, sizeLabel);
        ctx.page.drawText(footL, { x: margin, y: ctx.y, size: sizeLabel, font: boldFont, color: brandPrimary });
        ctx.page.drawText(footR, { x: PAGE_W - margin - rW, y: ctx.y, size: sizeLabel, font: primaryFont, color: subtleColor });
        // subtly use lW to avoid lint about unused
        void lW;
      }
      ctx.y -= 10;
      // Tiny IDs line
      const idLine = [
        `Ref: ${safeText(r.id, 80)}`,
        r.referrer_user_id ? `R-User: ${safeText(r.referrer_user_id, 80)}` : null,
        r.receiver_user_id ? `Rx-User: ${safeText(r.receiver_user_id, 80)}` : null,
        r.referrer_entity_id ? `R-Ent: ${safeText(r.referrer_entity_id, 80)}` : null,
        r.receiver_entity_id ? `Rx-Ent: ${safeText(r.receiver_entity_id, 80)}` : null,
      ].filter(Boolean).join("   ");
      wrapped(ctx, idLine, isRtl ? PAGE_W - margin : margin, contentW, sizeId, idColor);

      return startY - ctx.y;
    };

    const r: any = referral;

    // Pass 1: measure on a temporary tall page
    const measurePage = pdfDoc.addPage([PAGE_W, 4000]);
    const measureCtx: DrawCtx = { page: null, y: 4000 - margin };
    const consumed = renderAll(measureCtx);
    pdfDoc.removePage(pdfDoc.getPageIndices().indexOf(pdfDoc.getPages().indexOf(measurePage)));

    // Pass 2: real page sized to content
    const minH = 360;
    const pageH = Math.max(minH, consumed + margin * 2);
    const realPage = pdfDoc.addPage([PAGE_W, pageH]);
    const realCtx: DrawCtx = { page: realPage, y: pageH - margin };
    renderAll(realCtx);

    const bytes = await pdfDoc.save();
    const fileName = sanitizeFileName(`referral_${r.referral_number || r.id}`) + ".pdf";

    return new Response(bytes as unknown as BodyInit, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (e) {
    console.error("referral-generate-pdf error", e);
    return errorResponse("Failed to generate PDF", 500);
  }
});
