// Path: supabase/functions/referral-generate-pdf/index.ts

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, rgb } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";

import {
  corsHeaders,
  errorResponse,
  secureHandler,
} from "../_shared/security-middleware.ts";
import type { ValidationSchema } from "../_shared/input-validator.ts";

import { DOCITO_FONT_TTF_BASE64, DOCITO_LOGO_PNG_BASE64 } from "./assets.ts";

type Locale = "en" | "ru" | "uz";

type ReqBody = {
  referral_id: string;
  locale?: string;
};

const schema: ValidationSchema<ReqBody> = {
  referral_id: { type: "uuid", required: true },
  locale: { type: "string", required: false, minLength: 2, maxLength: 12, sanitize: true, trim: true },
};

function b64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function normalizeLocale(raw?: string | null): Locale {
  const s = (raw || "").toLowerCase().trim();
  if (s.startsWith("ru")) return "ru";
  if (s.startsWith("uz")) return "uz";
  return "en";
}

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    title: "Referral",
    referralNumber: "Referral Number",
    createdAt: "Created At",
    status: "Status",
    scope: "Referral Scope",
    scopeGeneral: "General",
    scopeSpecific: "Specific",
    referrer: "Referring Provider",
    receiver: "Referred To",
    patient: "Patient",
    dob: "Date of Birth",
    gender: "Gender",
    phone: "Phone",
    email: "Email",
    address: "Address",
    type: "Referral Type",
    priority: "Priority",
    reason: "Reason for Referral",
    diagnosis: "Diagnosis Codes",
    notes: "Clinical Notes",
    preferredDate: "Preferred Date",
    preferredTime: "Preferred Time",
    validFrom: "Valid From",
    validUntil: "Valid Until",
    verification: "Verification",
    verificationCode: "Verification Code",
    verifyAt: "Verify at",
    generatedBy: "Generated by Docito (docito.app)",
    na: "—",
  },
  ru: {
    title: "Направление",
    referralNumber: "Номер направления",
    createdAt: "Дата создания",
    status: "Статус",
    scope: "Тип направления",
    scopeGeneral: "Общее",
    scopeSpecific: "Конкретное",
    referrer: "Направившая организация/врач",
    receiver: "К кому направлено",
    patient: "Пациент",
    dob: "Дата рождения",
    gender: "Пол",
    phone: "Телефон",
    email: "Email",
    address: "Адрес",
    type: "Тип услуги",
    priority: "Приоритет",
    reason: "Причина направления",
    diagnosis: "Коды диагноза",
    notes: "Клинические заметки",
    preferredDate: "Предпочтительная дата",
    preferredTime: "Предпочтительное время",
    validFrom: "Действительно с",
    validUntil: "Действительно до",
    verification: "Проверка",
    verificationCode: "Код проверки",
    verifyAt: "Проверить на",
    generatedBy: "Сформировано в Docito (docito.app)",
    na: "—",
  },
  uz: {
    title: "Yoʻllanma",
    referralNumber: "Yoʻllanma raqami",
    createdAt: "Yaratilgan sana",
    status: "Holat",
    scope: "Yoʻllanma turi",
    scopeGeneral: "Umumiy",
    scopeSpecific: "Aniq",
    referrer: "Yoʻllovchi",
    receiver: "Qabul qiluvchi",
    patient: "Bemor",
    dob: "Tugʻilgan sana",
    gender: "Jins",
    phone: "Telefon",
    email: "Email",
    address: "Manzil",
    type: "Xizmat turi",
    priority: "Ustuvorlik",
    reason: "Yoʻllanma sababi",
    diagnosis: "Tashxis kodlari",
    notes: "Klinik qaydlar",
    preferredDate: "Afzal sana",
    preferredTime: "Afzal vaqt",
    validFrom: "Boshlanishi",
    validUntil: "Amal qilish muddati",
    verification: "Tasdiqlash",
    verificationCode: "Tasdiqlash kodi",
    verifyAt: "Tekshirish",
    generatedBy: "Docito orqali yaratildi (docito.app)",
    na: "—",
  },
};

function t(locale: Locale, key: string): string {
  return I18N[locale][key] || I18N.en[key] || key;
}

function safeText(v: unknown, fallback: string): string {
  const s = typeof v === "string" ? v.trim() : "";
  return s.length ? s : fallback;
}

function isoDate(v: unknown): string | null {
  const s = typeof v === "string" ? v.trim() : "";
  if (!s) return null;
  const m = s.match(/^\d{4}-\d{2}-\d{2}/);
  return m ? m[0] : null;
}

function isoDateTime(v: unknown): string | null {
  const s = typeof v === "string" ? v.trim() : "";
  if (!s) return null;
  const d = new Date(s);
  if (isNaN(d.getTime())) return null;
  return d.toISOString().replace("T", " ").slice(0, 19) + "Z";
}

function pickLocalizedName(row: Record<string, any> | null, locale: Locale): string | null {
  if (!row) return null;
  const key = locale === "ru" ? "name_ru" : locale === "uz" ? "name_uz" : "name_en";
  const byLocale = typeof row[key] === "string" ? row[key].trim() : "";
  if (byLocale) return byLocale;
  const base = typeof row.name === "string" ? row.name.trim() : "";
  return base || null;
}

async function getActorLocale(serviceClient: any, userId: string): Promise<Locale> {
  const { data } = await serviceClient
    .from("profiles")
    .select("language")
    .eq("user_id", userId)
    .maybeSingle();
  return normalizeLocale((data as any)?.language);
}

async function getDoctorDisplay(serviceClient: any, doctorId: string, locale: Locale): Promise<string | null> {
  const { data } = await serviceClient
    .from("doctors")
    .select(
      "id, specialty, specialty_en, specialty_ru, specialty_uz, profiles:user_id(full_name)",
    )
    .eq("id", doctorId)
    .maybeSingle();

  const name = (data as any)?.profiles?.full_name ? String((data as any).profiles.full_name) : null;

  const specKey = locale === "ru" ? "specialty_ru" : locale === "uz" ? "specialty_uz" : "specialty_en";
  const specialty = (data as any)?.[specKey] || (data as any)?.specialty || null;

  if (name && specialty) return `${name} — ${specialty}`;
  if (name) return name;
  if (specialty) return String(specialty);
  return null;
}

async function getEntityDisplay(serviceClient: any, type: string, entityId: string, locale: Locale): Promise<string | null> {
  const t0 = (type || "").toLowerCase();
  if (!entityId) return null;

  if (t0 === "doctor") return await getDoctorDisplay(serviceClient, entityId, locale);

  if (t0 === "clinic" || t0 === "practice") {
    const { data } = await serviceClient
      .from("practices")
      .select("id, name, name_en, name_ru, name_uz")
      .eq("id", entityId)
      .maybeSingle();
    return pickLocalizedName(data as any, locale);
  }

  if (t0 === "lab") {
    const { data } = await serviceClient
      .from("lab_centers")
      .select("id, name")
      .eq("id", entityId)
      .maybeSingle();
    return (data as any)?.name ? String((data as any).name) : null;
  }

  if (t0 === "imaging_center" || t0 === "imaging") {
    const { data } = await serviceClient
      .from("imaging_centers")
      .select("id, name")
      .eq("id", entityId)
      .maybeSingle();
    return (data as any)?.name ? String((data as any).name) : null;
  }

  if (t0 === "pharmacy") {
    const { data } = await serviceClient
      .from("pharmacies")
      .select("id, name")
      .eq("id", entityId)
      .maybeSingle();
    return (data as any)?.name ? String((data as any).name) : null;
  }

  return null;
}

async function canUserAccessReferrer(context: any, referral: any): Promise<boolean> {
  const roles: string[] = context?.roles || [];
  const userId: string | null = context?.userId || null;

  if (!userId) return false;
  if (roles.includes("super_admin")) return true;

  if (referral?.referrer_user_id && referral.referrer_user_id === userId) return true;

  const referrerType = String(referral?.referrer_type || "").toLowerCase();
  const referrerEntityId = String(referral?.referrer_entity_id || "");

  if (!referrerType || !referrerEntityId) return false;

  if (referrerType === "doctor") {
    const { data } = await context.serviceClient
      .from("doctors")
      .select("id")
      .eq("id", referrerEntityId)
      .eq("user_id", userId)
      .maybeSingle();
    return Boolean((data as any)?.id);
  }

  const entityType =
    referrerType === "clinic" ? "clinic"
      : referrerType === "lab" ? "lab"
      : referrerType === "imaging_center" ? "imaging"
      : referrerType === "pharmacy" ? "pharmacy"
      : referrerType;

  const { data: accessOk, error } = await context.supabase.rpc("can_access_entity", {
    p_entity_type: entityType,
    p_entity_id: referrerEntityId,
  });

  if (error) return false;
  return Boolean(accessOk);
}

function wrapText(font: any, text: string, size: number, maxWidth: number): string[] {
  const clean = (text || "").replace(/\s+/g, " ").trim();
  if (!clean) return [];
  const words = clean.split(" ");
  const lines: string[] = [];
  let line = "";

  for (const w of words) {
    const cand = line ? `${line} ${w}` : w;
    const width = font.widthOfTextAtSize(cand, size);
    if (width > maxWidth) {
      if (line) lines.push(line);
      line = w;
    } else {
      line = cand;
    }
  }

  if (line) lines.push(line);
  return lines;
}

async function buildPdf(params: {
  locale: Locale;
  referralNumber: string;
  createdAt: string;
  status: string;
  referralScope: "general" | "specific";
  referrer: string;
  receiver: string;
  patientName: string;
  patientDob?: string | null;
  patientGender?: string | null;
  patientPhone?: string | null;
  patientEmail?: string | null;
  patientAddress?: string | null;
  referralType?: string | null;
  priority?: string | null;
  reason?: string | null;
  diagnosisCodes?: string[] | null;
  clinicalNotes?: string | null;
  preferredDate?: string | null;
  preferredTime?: string | null;
  validFrom?: string | null;
  validUntil?: string | null;
  verificationCode?: string | null;
  verifyUrl?: string | null;
}) {
  const W = 595.28;
  const H = 841.89;
  const margin = 44;

  const pdf = await PDFDocument.create();
  pdf.registerFontkit(fontkit);

  const fontBytes = b64ToBytes(DOCITO_FONT_TTF_BASE64);
  const font = await pdf.embedFont(fontBytes, { subset: true });

  const page = pdf.addPage([W, H]);

  const logoBytes = b64ToBytes(DOCITO_LOGO_PNG_BASE64);
  const logo = await pdf.embedPng(logoBytes);

  const logoW = 42;
  const logoH = (logo.height / logo.width) * logoW;

  let y = H - margin;

  page.drawImage(logo, { x: margin, y: y - logoH, width: logoW, height: logoH });

  page.drawText("docito.app", {
    x: W - margin - font.widthOfTextAtSize("docito.app", 10),
    y: y - 12,
    size: 10,
    font,
    color: rgb(0.25, 0.25, 0.25),
  });

  y -= logoH + 18;

  page.drawText(t(params.locale, "title"), {
    x: margin,
    y,
    size: 20,
    font,
    color: rgb(0.05, 0.05, 0.05),
  });

  y -= 18;

  page.drawLine({
    start: { x: margin, y },
    end: { x: W - margin, y },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });

  y -= 18;

  const colLabelX = margin;
  const colValueX = margin + 160;
  const maxValueW = W - margin - colValueX;
  const labelSize = 10;
  const valueSize = 10;
  const lineGap = 14;

  const drawKV = (label: string, value: string) => {
    if (y < margin + 90) return;

    page.drawText(label, { x: colLabelX, y, size: labelSize, font, color: rgb(0.25, 0.25, 0.25) });

    const lines = wrapText(font, value, valueSize, maxValueW);
    if (lines.length === 0) {
      page.drawText(t(params.locale, "na"), { x: colValueX, y, size: valueSize, font });
      y -= lineGap;
      return;
    }

    for (let i = 0; i < lines.length; i++) {
      if (y < margin + 90) break;
      page.drawText(lines[i], { x: colValueX, y, size: valueSize, font, color: rgb(0.05, 0.05, 0.05) });
      y -= lineGap;
    }
  };

  const drawSection = (title: string) => {
    if (y < margin + 90) return;
    y -= 6;
    page.drawText(title, { x: margin, y, size: 12, font, color: rgb(0.1, 0.1, 0.1) });
    y -= 10;
    page.drawLine({
      start: { x: margin, y },
      end: { x: W - margin, y },
      thickness: 0.8,
      color: rgb(0.9, 0.9, 0.9),
    });
    y -= 14;
  };

  drawKV(t(params.locale, "referralNumber"), params.referralNumber);
  drawKV(t(params.locale, "createdAt"), params.createdAt);
  drawKV(t(params.locale, "status"), params.status);

  y -= 6;

  drawSection(t(params.locale, "scope"));
  drawKV(t(params.locale, "scope"), params.referralScope === "general" ? t(params.locale, "scopeGeneral") : t(params.locale, "scopeSpecific"));
  drawKV(t(params.locale, "referrer"), params.referrer);
  drawKV(t(params.locale, "receiver"), params.receiver);

  y -= 6;

  drawSection(t(params.locale, "patient"));
  drawKV(t(params.locale, "patient"), params.patientName);
  if (params.patientDob) drawKV(t(params.locale, "dob"), params.patientDob);
  if (params.patientGender) drawKV(t(params.locale, "gender"), params.patientGender);
  if (params.patientPhone) drawKV(t(params.locale, "phone"), params.patientPhone);
  if (params.patientEmail) drawKV(t(params.locale, "email"), params.patientEmail);
  if (params.patientAddress) drawKV(t(params.locale, "address"), params.patientAddress);

  y -= 6;

  drawSection(t(params.locale, "type"));
  if (params.referralType) drawKV(t(params.locale, "type"), params.referralType);
  if (params.priority) drawKV(t(params.locale, "priority"), params.priority);
  if (params.preferredDate) drawKV(t(params.locale, "preferredDate"), params.preferredDate);
  if (params.preferredTime) drawKV(t(params.locale, "preferredTime"), params.preferredTime);
  if (params.validFrom) drawKV(t(params.locale, "validFrom"), params.validFrom);
  if (params.validUntil) drawKV(t(params.locale, "validUntil"), params.validUntil);

  y -= 6;

  drawSection(t(params.locale, "reason"));
  drawKV(t(params.locale, "reason"), params.reason || t(params.locale, "na"));

  if (params.diagnosisCodes && params.diagnosisCodes.length) {
    drawKV(t(params.locale, "diagnosis"), params.diagnosisCodes.join(", "));
  }

  if (params.clinicalNotes) {
    drawKV(t(params.locale, "notes"), params.clinicalNotes);
  }

  const footerY = margin + 26;

  page.drawLine({
    start: { x: margin, y: footerY + 26 },
    end: { x: W - margin, y: footerY + 26 },
    thickness: 1,
    color: rgb(0.9, 0.9, 0.9),
  });

  page.drawText(t(params.locale, "generatedBy"), {
    x: margin,
    y: footerY + 8,
    size: 9,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });

  const verificationCode = params.verificationCode ? String(params.verificationCode) : t(params.locale, "na");
  const verifyUrl = params.verifyUrl ? String(params.verifyUrl) : "https://docito.app";

  page.drawText(t(params.locale, "verification") + ":", {
    x: margin,
    y: footerY + 44,
    size: 10,
    font,
    color: rgb(0.25, 0.25, 0.25),
  });

  page.drawText(`${t(params.locale, "verificationCode")}: ${verificationCode}`, {
    x: margin,
    y: footerY + 30,
    size: 9,
    font,
    color: rgb(0.05, 0.05, 0.05),
  });

  page.drawText(`${t(params.locale, "verifyAt")}: ${verifyUrl}`, {
    x: margin,
    y: footerY + 18,
    size: 9,
    font,
    color: rgb(0.05, 0.05, 0.05),
  });

  try {
    const dataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 140 });
    const b64 = dataUrl.split(",")[1] || "";
    if (b64) {
      const qrBytes = b64ToBytes(b64);
      const qr = await pdf.embedPng(qrBytes);
      const qrW = 92;
      const qrH = 92;
      page.drawImage(qr, { x: W - margin - qrW, y: footerY + 6, width: qrW, height: qrH });
    }
  } catch {
    // ignore QR failures
  }

  return await pdf.save();
}

serve(async (req) => {
  const sec = await secureHandler(req, "referral-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "standard",
    validationSchema: schema,
  });

  if (sec.response) return sec.response;

  const context = sec.context!;
  const body = sec.validatedBody as ReqBody;

  const roles = context.roles || [];
  const hasNonPatientRole = roles.some((r: string) => r !== "patient");
  if (!hasNonPatientRole) {
    return errorResponse("Insufficient permissions", 403);
  }

  const referralId = body.referral_id;
  const locale = body.locale
    ? normalizeLocale(body.locale)
    : await getActorLocale(context.serviceClient, context.userId!);

  const { data: referral, error: referralErr } = await context.serviceClient
    .from("referrals")
    .select(
      [
        "id",
        "referral_number",
        "created_at",
        "status",
        "referral_scope",
        "target_field",
        "target_details",
        "referrer_type",
        "referrer_entity_id",
        "referrer_user_id",
        "receiver_type",
        "receiver_entity_id",
        "referral_type_enum",
        "priority",
        "reason",
        "clinical_notes",
        "diagnosis_codes",
        "preferred_date",
        "preferred_time_slot",
        "valid_from",
        "valid_until",
        "patient_id",
        "patient_name",
        "patient_phone",
        "patient_email",
        "patient_snapshot_full_name",
        "patient_snapshot_phone",
        "patient_snapshot_email",
        "patient_snapshot_dob",
        "patient_snapshot_gender",
        "patient_snapshot_address",
        "patient_snapshot_id_number",
        "verification_code",
      ].join(","),
    )
    .eq("id", referralId)
    .maybeSingle();

  if (referralErr) return errorResponse("Failed to load referral", 500);
  if (!referral) return errorResponse("Referral not found", 404);

  const ok = await canUserAccessReferrer(context, referral);
  if (!ok) return errorResponse("Forbidden", 403);

  let patientName = safeText((referral as any).patient_snapshot_full_name, "");
  let patientPhone = safeText((referral as any).patient_snapshot_phone, "");
  let patientEmail = safeText((referral as any).patient_snapshot_email, "");
  const patientDob = isoDate((referral as any).patient_snapshot_dob);
  const patientGender = safeText((referral as any).patient_snapshot_gender, "");
  const patientAddress = safeText((referral as any).patient_snapshot_address, "");

  if (!patientName) patientName = safeText((referral as any).patient_name, "");
  if (!patientPhone) patientPhone = safeText((referral as any).patient_phone, "");
  if (!patientEmail) patientEmail = safeText((referral as any).patient_email, "");

  const patientId = (referral as any).patient_id ? String((referral as any).patient_id) : "";
  if ((!patientName || !patientEmail || !patientPhone) && patientId) {
    const { data: p } = await context.serviceClient
      .from("profiles")
      .select("full_name, email, phone")
      .eq("user_id", patientId)
      .maybeSingle();

    if (p) {
      if (!patientName) patientName = safeText((p as any).full_name, "");
      if (!patientEmail) patientEmail = safeText((p as any).email, "");
      if (!patientPhone) patientPhone = safeText((p as any).phone, "");
    }
  }

  const createdAt = isoDateTime((referral as any).created_at) || t(locale, "na");
  const status = safeText((referral as any).status, t(locale, "na"));

  const referralNumber = safeText((referral as any).referral_number, (referral as any).id);
  const referralScope =
    String((referral as any).referral_scope || "specific").toLowerCase() === "general" ? "general" : "specific";

  const referrerType = String((referral as any).referrer_type || "");
  const referrerEntityId = String((referral as any).referrer_entity_id || "");
  const referrerDisplay =
    (await getEntityDisplay(context.serviceClient, referrerType, referrerEntityId, locale)) || t(locale, "na");

  let receiverDisplay = t(locale, "na");
  const receiverType = String((referral as any).receiver_type || "");
  const receiverEntityId = (referral as any).receiver_entity_id ? String((referral as any).receiver_entity_id) : "";

  if (referralScope === "specific" && receiverEntityId) {
    receiverDisplay =
      (await getEntityDisplay(context.serviceClient, receiverType, receiverEntityId, locale)) || t(locale, "na");
  } else {
    const targetField = safeText((referral as any).target_field, "");
    const targetDetails = safeText((referral as any).target_details, "");
    receiverDisplay = targetField || safeText((referral as any).referral_type_enum, t(locale, "na"));
    if (targetDetails) receiverDisplay = `${receiverDisplay} — ${targetDetails}`;
  }

  const referralType = safeText((referral as any).referral_type_enum, "");
  const priority = safeText((referral as any).priority, "");
  const reason = safeText((referral as any).reason, "");
  const clinicalNotes = safeText((referral as any).clinical_notes, "");

  const diagnosisCodes = Array.isArray((referral as any).diagnosis_codes)
    ? ((referral as any).diagnosis_codes as string[])
    : null;

  const preferredDate = isoDate((referral as any).preferred_date);
  const preferredTime = safeText((referral as any).preferred_time_slot, "");

  const validFrom = isoDate((referral as any).valid_from);
  const validUntil = isoDate((referral as any).valid_until);

  const verificationCode = safeText((referral as any).verification_code, "");
  const verifyUrl = verificationCode
    ? `https://docito.app/verify/referral?ref=${encodeURIComponent(referralNumber)}&code=${encodeURIComponent(verificationCode)}`
    : `https://docito.app/verify/referral?ref=${encodeURIComponent(referralNumber)}`;

  const pdfBytes = await buildPdf({
    locale,
    referralNumber,
    createdAt,
    status,
    referralScope,
    referrer: referrerDisplay,
    receiver: receiverDisplay,
    patientName: patientName || t(locale, "na"),
    patientDob,
    patientGender: patientGender || null,
    patientPhone: patientPhone || null,
    patientEmail: patientEmail || null,
    patientAddress: patientAddress || null,
    referralType: referralType || null,
    priority: priority || null,
    reason: reason || null,
    diagnosisCodes,
    clinicalNotes: clinicalNotes || null,
    preferredDate: preferredDate || null,
    preferredTime: preferredTime || null,
    validFrom: validFrom || null,
    validUntil: validUntil || null,
    verificationCode: verificationCode || null,
    verifyUrl,
  });

  const filename = `docito-referral-${referralNumber.replace(/[^a-zA-Z0-9_-]/g, "")}.pdf`;

  return new Response(pdfBytes, {
    status: 200,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Access-Control-Expose-Headers": "Content-Disposition",
      "Cache-Control": "no-store",
    },
  });
});
