// File: supabase/functions/generate-referral-pdf/index.ts
/**
 * Generate Referral PDF (Docito)
 *
 * - Auth required
 * - Any role except patient-only can generate
 * - Verifiable via referral_number + verification_code
 * - Branded with Docito logo, domain: docito.app
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, rgb } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";
import {
  secureHandler,
  errorResponse,
  corsHeaders,
} from "../_shared/security-middleware.ts";
import { sanitizeString } from "../_shared/input-validator.ts";
import { DOCITO_LOGO_ICON_PNG_BASE64, DEJAVU_SANS_SUBSET_TTF_BASE64 } from "./assets.ts";

type ReqBody = {
  referral_id: string;
  locale?: string;
};

type EntityInfo = {
  name: string;
  typeLabel: string;
  specialty?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
};

type PatientInfo = {
  name: string;
  phone?: string | null;
  email?: string | null;
  dob?: string | null;
  gender?: string | null;
  address?: string | null;
};

const schema = {
  referral_id: { type: "uuid" as const, required: true },
  locale: { type: "string" as const, required: false, maxLength: 12, sanitize: true, trim: true },
};

const ALLOWED_NON_PATIENT_ROLES = new Set([
  "admin",
  "super_admin",
  "staff",
  "doctor",
  "clinic_admin",
  "lab_admin",
  "imaging_admin",
  "pharmacy_admin",
]);

function b64ToBytes(b64: string): Uint8Array {
  const clean = (b64 || "").replace(/\s+/g, "");
  const bin = atob(clean);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function normalizeLocale(locale?: string): "en" | "ru" | "uz" {
  const raw = sanitizeString(locale || "", 12).toLowerCase();
  if (!raw) return "en";
  if (raw.startsWith("ru")) return "ru";
  if (raw.startsWith("uz")) return "uz";
  return "en";
}

const I18N: Record<"en" | "ru" | "uz", Record<string, string>> = {
  en: {
    title: "Referral",
    generalReferral: "General referral",
    specificReferral: "Specific referral",
    referralNumber: "Referral number",
    createdAt: "Created",
    validFrom: "Valid from",
    validUntil: "Valid until",
    status: "Status",
    priority: "Priority",
    type: "Type",
    patient: "Patient",
    referrer: "Referrer",
    receiver: "Receiver",
    reason: "Reason",
    clinicalNotes: "Clinical notes",
    diagnosisCodes: "Diagnosis codes",
    verifyTitle: "Verify this referral",
    verifyText: "Verify at docito.app using the referral number and verification code, or scan the QR code.",
    verificationCode: "Verification code",
    generatedBy: "Generated by Docito",
    name: "Name",
    dob: "DOB",
    gender: "Gender",
    phone: "Phone",
    email: "Email",
    address: "Address",
    specialty: "Specialty",
    clinicalSection: "Clinical",
  },
  ru: {
    title: "Направление",
    generalReferral: "Общее направление",
    specificReferral: "Конкретное направление",
    referralNumber: "Номер направления",
    createdAt: "Создано",
    validFrom: "Действительно с",
    validUntil: "Действительно до",
    status: "Статус",
    priority: "Приоритет",
    type: "Тип",
    patient: "Пациент",
    referrer: "Направивший",
    receiver: "Получатель",
    reason: "Причина",
    clinicalNotes: "Клинические заметки",
    diagnosisCodes: "Коды диагноза",
    verifyTitle: "Проверка направления",
    verifyText: "Проверьте на docito.app по номеру направления и коду проверки или отсканируйте QR-код.",
    verificationCode: "Код проверки",
    generatedBy: "Сгенерировано Docito",
    name: "Имя",
    dob: "Дата рождения",
    gender: "Пол",
    phone: "Телефон",
    email: "Email",
    address: "Адрес",
    specialty: "Специальность",
    clinicalSection: "Клиническая информация",
  },
  uz: {
    title: "Yo‘llanma",
    generalReferral: "Umumiy yo‘llanma",
    specificReferral: "Aniq yo‘llanma",
    referralNumber: "Yo‘llanma raqami",
    createdAt: "Yaratilgan",
    validFrom: "Amal qiladi (dan)",
    validUntil: "Amal qiladi (gacha)",
    status: "Holat",
    priority: "Ustuvorlik",
    type: "Turi",
    patient: "Bemor",
    referrer: "Yo‘naltiruvchi",
    receiver: "Qabul qiluvchi",
    reason: "Sabab",
    clinicalNotes: "Klinik izohlar",
    diagnosisCodes: "Tashxis kodlari",
    verifyTitle: "Yo‘llanmani tekshirish",
    verifyText: "docito.app saytida yo‘llanma raqami va tekshiruv kodi orqali tekshiring yoki QR kodni skaner qiling.",
    verificationCode: "Tekshiruv kodi",
    generatedBy: "Docito tomonidan yaratilgan",
    name: "Ism",
    dob: "Tug‘ilgan sana",
    gender: "Jinsi",
    phone: "Telefon",
    email: "Email",
    address: "Manzil",
    specialty: "Mutaxassislik",
    clinicalSection: "Klinik ma’lumot",
  },
};

function t(locale: "en" | "ru" | "uz", key: string): string {
  return I18N[locale][key] || I18N.en[key] || key;
}

function formatDateLike(input: unknown, locale: "en" | "ru" | "uz"): string {
  const s = typeof input === "string" ? input : input instanceof Date ? input.toISOString() : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return s;
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");

  if (locale === "en") return `${yyyy}-${mm}-${dd}`;
  return `${dd}.${mm}.${yyyy}`;
}

function formatDateTimeLike(input: unknown, locale: "en" | "ru" | "uz"): string {
  const s = typeof input === "string" ? input : input instanceof Date ? input.toISOString() : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return s;
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mi = String(d.getUTCMinutes()).padStart(2, "0");

  if (locale === "en") return `${yyyy}-${mm}-${dd} ${hh}:${mi} UTC`;
  return `${dd}.${mm}.${yyyy} ${hh}:${mi} UTC`;
}

function normalizePriority(p?: string | null): string {
  const v = sanitizeString(p || "", 20).toLowerCase();
  if (!v) return "routine";
  return v;
}

function normalizeStatus(s?: string | null): string {
  const v = sanitizeString(s || "", 32).toLowerCase();
  return v || "unknown";
}

function normalizeType(s?: string | null): string {
  const v = sanitizeString(s || "", 64);
  return v || "";
}

function safeOneLine(v?: unknown, max = 120): string {
  const s = sanitizeString(typeof v === "string" ? v : v == null ? "" : String(v), max);
  return s.replace(/[\r\n]+/g, " ").trim();
}

function wrapText(text: string, font: any, fontSize: number, maxWidth: number): string[] {
  const cleaned = (text || "").replace(/\s+/g, " ").trim();
  if (!cleaned) return [];
  const words = cleaned.split(" ");
  const lines: string[] = [];
  let line = "";

  const pushLine = (l: string) => {
    if (l.trim()) lines.push(l.trim());
  };

  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    const width = font.widthOfTextAtSize(test, fontSize);
    if (width <= maxWidth) {
      line = test;
      continue;
    }

    // If single word too long, break by chars
    if (!line && font.widthOfTextAtSize(w, fontSize) > maxWidth) {
      let chunk = "";
      for (const ch of w) {
        const tt = chunk + ch;
        if (font.widthOfTextAtSize(tt, fontSize) <= maxWidth) {
          chunk = tt;
        } else {
          pushLine(chunk);
          chunk = ch;
        }
      }
      pushLine(chunk);
      line = "";
      continue;
    }

    pushLine(line);
    line = w;
  }

  pushLine(line);
  return lines;
}

function generateVerificationCode(): string {
  const bytes = new Uint8Array(10);
  crypto.getRandomValues(bytes);
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function fetchPatientInfo(service: any, referral: any): Promise<PatientInfo> {
  const patientId = referral.patient_id as string | null;

  // If there is a linked patient id, prefer profiles
  if (patientId) {
    const { data } = await service
      .from("profiles")
      .select("id, user_id, full_name, email, phone, date_of_birth, gender, address")
      .or(`id.eq.${patientId},user_id.eq.${patientId}`)
      .maybeSingle();

    if (data) {
      return {
        name: data.full_name || referral.patient_name || "Unknown",
        phone: data.phone || referral.patient_phone || null,
        email: data.email || referral.patient_email || null,
        dob: data.date_of_birth || referral.patient_dob || null,
        gender: data.gender || referral.patient_gender || null,
        address: data.address || referral.patient_address || null,
      };
    }
  }

  // Fallback to snapshot fields
  return {
    name: referral.patient_name || "Unknown",
    phone: referral.patient_phone || null,
    email: referral.patient_email || null,
    dob: referral.patient_dob || null,
    gender: referral.patient_gender || null,
    address: referral.patient_address || null,
  };
}

function entityTypeLabel(locale: "en" | "ru" | "uz", type: string): string {
  const t0 = sanitizeString(type || "", 32).toLowerCase();
  const map: Record<string, Record<"en" | "ru" | "uz", string>> = {
    doctor: { en: "Doctor", ru: "Врач", uz: "Shifokor" },
    clinic: { en: "Clinic", ru: "Клиника", uz: "Klinika" },
    lab: { en: "Laboratory", ru: "Лаборатория", uz: "Laboratoriya" },
    imaging_center: { en: "Imaging center", ru: "Диагностический центр", uz: "Diagnostika markazi" },
    pharmacy: { en: "Pharmacy", ru: "Аптека", uz: "Dorixona" },
  };

  return map[t0]?.[locale] || map[t0]?.en || safeOneLine(type, 32);
}

async function fetchEntityInfo(
  service: any,
  locale: "en" | "ru" | "uz",
  type: string | null,
  entityId: string | null,
  userId: string | null,
): Promise<EntityInfo> {
  const typeKey = sanitizeString(type || "", 32).toLowerCase();
  const typeLabel = entityTypeLabel(locale, typeKey);

  // General referral fallback
  if (!entityId && !userId) {
    return { name: `${t(locale, "generalReferral")} (${typeLabel})`, typeLabel };
  }

  try {
    if (typeKey === "doctor") {
      // Try by entityId (doctors.id) first, then by user_id
      let q = service
        .from("doctors")
        .select("id, specialty, profiles:user_id(full_name, email, phone)")
        .limit(1);

      if (entityId) q = q.eq("id", entityId);
      else if (userId) q = q.eq("user_id", userId);

      const { data } = await q.maybeSingle();
      const name = data?.profiles?.full_name || "Unknown Doctor";
      return {
        name,
        typeLabel,
        specialty: data?.specialty || null,
        email: data?.profiles?.email || null,
        phone: data?.profiles?.phone || null,
      };
    }

    if (typeKey === "clinic") {
      const { data } = await service
        .from("practices")
        .select("name, address, city, country, phone")
        .eq("id", entityId)
        .maybeSingle();

      const name = data?.name || "Unknown Clinic";
      const address = [data?.address, data?.city, data?.country].filter(Boolean).join(", ") || null;
      return { name, typeLabel, phone: data?.phone || null, address };
    }

    if (typeKey === "lab") {
      const { data } = await service
        .from("lab_centers")
        .select("name, address, city, country, phone")
        .eq("id", entityId)
        .maybeSingle();

      const name = data?.name || "Unknown Lab";
      const address = [data?.address, data?.city, data?.country].filter(Boolean).join(", ") || null;
      return { name, typeLabel, phone: data?.phone || null, address };
    }

    if (typeKey === "imaging_center") {
      const { data } = await service
        .from("imaging_centers")
        .select("name, address, city, country, phone")
        .eq("id", entityId)
        .maybeSingle();

      const name = data?.name || "Unknown Imaging Center";
      const address = [data?.address, data?.city, data?.country].filter(Boolean).join(", ") || null;
      return { name, typeLabel, phone: data?.phone || null, address };
    }

    if (typeKey === "pharmacy") {
      const { data } = await service
        .from("pharmacies")
        .select("name, address, city, country, phone")
        .eq("id", entityId)
        .maybeSingle();

      const name = data?.name || "Unknown Pharmacy";
      const address = [data?.address, data?.city, data?.country].filter(Boolean).join(", ") || null;
      return { name, typeLabel, phone: data?.phone || null, address };
    }
  } catch {
    // ignore, fallback below
  }

  return { name: typeLabel, typeLabel };
}

type DrawContext = {
  pdf: any;
  page: any;
  font: any;
  locale: "en" | "ru" | "uz";
  margin: number;
  y: number;
};

function newA4Page(pdf: any) {
  // A4 in points
  return pdf.addPage([595.28, 841.89]);
}

function ensureSpace(ctx: DrawContext, needed: number): DrawContext {
  if (ctx.y - needed > ctx.margin) return ctx;
  const page = newA4Page(ctx.pdf);
  return { ...ctx, page, y: page.getHeight() - ctx.margin };
}

function drawSectionTitle(ctx: DrawContext, title: string): DrawContext {
  ctx = ensureSpace(ctx, 24);
  ctx.page.drawText(title, {
    x: ctx.margin,
    y: ctx.y,
    size: 13,
    font: ctx.font,
    color: rgb(0.1, 0.1, 0.1),
  });
  ctx.y -= 16;
  ctx.page.drawLine({
    start: { x: ctx.margin, y: ctx.y },
    end: { x: ctx.page.getWidth() - ctx.margin, y: ctx.y },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });
  ctx.y -= 10;
  return ctx;
}

function drawKV(
  ctx: DrawContext,
  label: string,
  value: string,
  opts?: { valueMaxWidth?: number; fontSize?: number },
): DrawContext {
  const fontSize = opts?.fontSize ?? 10;
  const labelText = safeOneLine(label, 80);
  const valueText = (value || "").toString();
  const labelWidth = 120;
  const valueMaxWidth = opts?.valueMaxWidth ?? (ctx.page.getWidth() - ctx.margin * 2 - labelWidth);

  const lines = wrapText(valueText, ctx.font, fontSize, valueMaxWidth);
  const needed = Math.max(1, lines.length) * (fontSize + 3) + 4;
  ctx = ensureSpace(ctx, needed);

  ctx.page.drawText(labelText, {
    x: ctx.margin,
    y: ctx.y,
    size: fontSize,
    font: ctx.font,
    color: rgb(0.35, 0.35, 0.35),
  });

  if (!lines.length) {
    ctx.page.drawText("-", {
      x: ctx.margin + labelWidth,
      y: ctx.y,
      size: fontSize,
      font: ctx.font,
      color: rgb(0.1, 0.1, 0.1),
    });
    ctx.y -= fontSize + 5;
    return ctx;
  }

  let y = ctx.y;
  for (const ln of lines) {
    ctx.page.drawText(ln, {
      x: ctx.margin + labelWidth,
      y,
      size: fontSize,
      font: ctx.font,
      color: rgb(0.1, 0.1, 0.1),
    });
    y -= fontSize + 3;
  }

  ctx.y = y - 2;
  return ctx;
}

function drawParagraph(
  ctx: DrawContext,
  text: string,
  opts?: { fontSize?: number; maxWidth?: number },
): DrawContext {
  const fontSize = opts?.fontSize ?? 10;
  const maxWidth = opts?.maxWidth ?? (ctx.page.getWidth() - ctx.margin * 2);
  const lines = wrapText(text, ctx.font, fontSize, maxWidth);
  const needed = Math.max(1, lines.length) * (fontSize + 3) + 4;
  ctx = ensureSpace(ctx, needed);

  let y = ctx.y;
  for (const ln of (lines.length ? lines : ["-"])) {
    ctx.page.drawText(ln, { x: ctx.margin, y, size: fontSize, font: ctx.font, color: rgb(0.1, 0.1, 0.1) });
    y -= fontSize + 3;
  }
  ctx.y = y - 2;
  return ctx;
}

async function buildPdf(params: {
  locale: "en" | "ru" | "uz";
  referral: any;
  verificationCode: string;
  patient: PatientInfo;
  referrer: EntityInfo;
  receiver: EntityInfo;
}): Promise<Uint8Array> {
  const { locale, referral, verificationCode, patient, referrer, receiver } = params;

  const pdf = await PDFDocument.create();
  pdf.registerFontkit(fontkit);

  const fontBytes = b64ToBytes(DEJAVU_SANS_SUBSET_TTF_BASE64);
  const font = await pdf.embedFont(fontBytes, { subset: true });

  const page = newA4Page(pdf);
  const margin = 46;
  let ctx: DrawContext = { pdf, page, font, locale, margin, y: page.getHeight() - margin };

  // Header: Docito branding + title
  const logoBytes = b64ToBytes(DOCITO_LOGO_ICON_PNG_BASE64);
  const logo = await pdf.embedPng(logoBytes);
  const logoTarget = 26;
  const logoScale = logoTarget / logo.width;
  const logoDims = logo.scale(logoScale);

  page.drawImage(logo, {
    x: margin,
    y: ctx.y - logoDims.height,
    width: logoDims.width,
    height: logoDims.height,
  });

  page.drawText("Docito", {
    x: margin + logoDims.width + 8,
    y: ctx.y - 18,
    size: 14,
    font,
    color: rgb(0.1, 0.1, 0.1),
  });

  const titleText = t(locale, "title");
  const titleSize = 18;
  const titleWidth = font.widthOfTextAtSize(titleText, titleSize);
  page.drawText(titleText, {
    x: page.getWidth() - margin - titleWidth,
    y: ctx.y - 22,
    size: titleSize,
    font,
    color: rgb(0.1, 0.1, 0.1),
  });

  const domainText = "docito.app";
  const domainWidth = font.widthOfTextAtSize(domainText, 10);
  page.drawText(domainText, {
    x: page.getWidth() - margin - domainWidth,
    y: ctx.y - 40,
    size: 10,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });

  ctx.y = ctx.y - Math.max(logoDims.height, 44) - 14;

  // Summary block
  const referralNumber = safeOneLine(referral.referral_number || referral.id, 64);
  const createdAt = formatDateTimeLike(referral.created_at, locale);
  const validFrom = formatDateLike(referral.valid_from, locale);
  const validUntil = formatDateLike(referral.valid_until, locale);
  const status = normalizeStatus(referral.status);
  const priority = normalizePriority(referral.priority);
  const type = normalizeType(referral.referral_type_enum || referral.referral_type || "");

  const isSpecific = !!(referral.receiver_entity_id || referral.receiver_user_id);
  const scopeLabel = isSpecific ? t(locale, "specificReferral") : t(locale, "generalReferral");

  ctx = drawKV(ctx, t(locale, "referralNumber"), referralNumber);
  ctx = drawKV(ctx, t(locale, "createdAt"), createdAt);
  ctx = drawKV(ctx, t(locale, "validFrom"), validFrom || "-");
  ctx = drawKV(ctx, t(locale, "validUntil"), validUntil || "-");
  ctx = drawKV(ctx, t(locale, "status"), safeOneLine(status, 40));
  ctx = drawKV(ctx, t(locale, "priority"), safeOneLine(priority, 40));
  ctx = drawKV(ctx, t(locale, "type"), safeOneLine(type, 64) || scopeLabel);

  ctx.y -= 8;

  // Patient
  ctx = drawSectionTitle(ctx, t(locale, "patient"));
  ctx = drawKV(ctx, t(locale, "name"), patient.name);
  if (patient.dob) ctx = drawKV(ctx, t(locale, "dob"), formatDateLike(patient.dob, locale));
  if (patient.gender) ctx = drawKV(ctx, t(locale, "gender"), safeOneLine(patient.gender, 24));
  if (patient.phone) ctx = drawKV(ctx, t(locale, "phone"), safeOneLine(patient.phone, 32));
  if (patient.email) ctx = drawKV(ctx, t(locale, "email"), safeOneLine(patient.email, 64));
  if (patient.address) ctx = drawKV(ctx, t(locale, "address"), safeOneLine(patient.address, 120));

  ctx.y -= 6;

  // Referrer
  ctx = drawSectionTitle(ctx, t(locale, "referrer"));
  ctx = drawKV(ctx, t(locale, "type"), referrer.typeLabel);
  ctx = drawKV(ctx, t(locale, "name"), referrer.name);
  if (referrer.specialty) ctx = drawKV(ctx, t(locale, "specialty"), safeOneLine(referrer.specialty, 64));
  if (referrer.phone) ctx = drawKV(ctx, t(locale, "phone"), safeOneLine(referrer.phone, 32));
  if (referrer.email) ctx = drawKV(ctx, t(locale, "email"), safeOneLine(referrer.email, 64));
  if (referrer.address) ctx = drawKV(ctx, t(locale, "address"), safeOneLine(referrer.address, 120));

  ctx.y -= 6;

  // Receiver
  ctx = drawSectionTitle(ctx, t(locale, "receiver"));
  ctx = drawKV(ctx, t(locale, "type"), receiver.typeLabel);
  ctx = drawKV(ctx, t(locale, "name"), receiver.name);
  if (receiver.specialty) ctx = drawKV(ctx, t(locale, "specialty"), safeOneLine(receiver.specialty, 64));
  if (receiver.phone) ctx = drawKV(ctx, t(locale, "phone"), safeOneLine(receiver.phone, 32));
  if (receiver.email) ctx = drawKV(ctx, t(locale, "email"), safeOneLine(receiver.email, 64));
  if (receiver.address) ctx = drawKV(ctx, t(locale, "address"), safeOneLine(receiver.address, 120));

  ctx.y -= 6;

  // Clinical
  ctx = drawSectionTitle(ctx, t(locale, "clinicalSection"));
  ctx = drawKV(ctx, t(locale, "reason"), safeOneLine(referral.reason, 400), { valueMaxWidth: 360 });
  if (referral.clinical_notes) {
    ctx = drawKV(ctx, t(locale, "clinicalNotes"), safeOneLine(referral.clinical_notes, 900), { valueMaxWidth: 360 });
  }
  if (referral.diagnosis_codes && Array.isArray(referral.diagnosis_codes) && referral.diagnosis_codes.length) {
    ctx = drawKV(
      ctx,
      t(locale, "diagnosisCodes"),
      referral.diagnosis_codes.map((c: any) => safeOneLine(c, 24)).join(", "),
      { valueMaxWidth: 360 },
    );
  }

  ctx.y -= 10;

  // Verification block
  ctx = drawSectionTitle(ctx, t(locale, "verifyTitle"));

  const verificationUrl = `https://docito.app/verify/referral?ref=${encodeURIComponent(referralNumber)}&code=${encodeURIComponent(verificationCode)}`;
  const qrDataUrl = await QRCode.toDataURL(verificationUrl, { margin: 1, width: 240 });
  const qrBase64 = qrDataUrl.split(",")[1] || "";
  const qrBytes = b64ToBytes(qrBase64);
  const qrImage = await pdf.embedPng(qrBytes);

  const qrSize = 120;
  const qrX = page.getWidth() - margin - qrSize;
  const qrY = Math.max(ctx.y - qrSize + 10, margin + 70);

  page.drawImage(qrImage, { x: qrX, y: qrY, width: qrSize, height: qrSize });

  ctx = drawParagraph(ctx, t(locale, "verifyText"), {
    maxWidth: page.getWidth() - margin * 2 - qrSize - 18,
  });
  ctx = drawKV(ctx, t(locale, "verificationCode"), verificationCode, { valueMaxWidth: 260 });

  // Footer
  const footerY = margin - 10;
  page.drawLine({
    start: { x: margin, y: footerY + 18 },
    end: { x: page.getWidth() - margin, y: footerY + 18 },
    thickness: 1,
    color: rgb(0.9, 0.9, 0.9),
  });

  page.drawText(`${t(locale, "generatedBy")} • ${formatDateTimeLike(new Date(), locale)}`, {
    x: margin,
    y: footerY,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  const urlText = "docito.app";
  const urlW = font.widthOfTextAtSize(urlText, 9);
  page.drawText(urlText, {
    x: page.getWidth() - margin - urlW,
    y: footerY,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  return await pdf.save();
}

serve(async (req) => {
  const { response, context, validatedBody } = await secureHandler(req, "generate-referral-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "standard",
    validationSchema: schema,
    logRequests: true,
  });

  if (response) return response;
  if (!context || !validatedBody) return errorResponse("Internal server error", 500);

  const { referral_id, locale } = validatedBody as ReqBody;
  const lang = normalizeLocale(locale);

  // Reject patient-only users
  const roles = new Set((context.roles || []) as string[]);
  const hasNonPatientRole = Array.from(roles).some((r) => ALLOWED_NON_PATIENT_ROLES.has(r));
  if (!hasNonPatientRole) {
    return errorResponse("Forbidden", 403);
  }

  // Ensure requester can access the referral via RLS (use user-scoped client)
  const { data: referral, error: refErr } = await context.supabase
    .from("referrals")
    .select("*")
    .eq("id", referral_id)
    .maybeSingle();

  if (refErr || !referral) {
    return errorResponse("Referral not found", 404);
  }

  const service = context.serviceClient;

  // Ensure verification_code exists for verifiability
  let verificationCode = (referral as any).verification_code as string | null;
  if (!verificationCode) {
    verificationCode = generateVerificationCode();
    try {
      await service.from("referrals").update({ verification_code: verificationCode }).eq("id", referral_id);
    } catch {
      // ignore (still return PDF with generated code)
    }
  }

  const patient = await fetchPatientInfo(service, referral);

  const referrer = await fetchEntityInfo(
    service,
    lang,
    (referral as any).referrer_type || null,
    (referral as any).referrer_entity_id || null,
    (referral as any).referrer_user_id || null,
  );

  const receiver = await fetchEntityInfo(
    service,
    lang,
    (referral as any).receiver_type || null,
    (referral as any).receiver_entity_id || null,
    (referral as any).receiver_user_id || null,
  );

  const pdfBytes = await buildPdf({
    locale: lang,
    referral,
    verificationCode,
    patient,
    referrer,
    receiver,
  });

  const filename = `referral_${safeOneLine((referral as any).referral_number || referral_id, 64)}.pdf`.replace(
    /[^a-zA-Z0-9._-]+/g,
    "_",
  );

  return new Response(pdfBytes as unknown as BodyInit, {
    status: 200,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
});
