// supabase/functions/invoice-generate-pdf/index.ts
/**
 * Invoice PDF generator — Docito
 * Produces a localized PDF for any row in `billing_invoices`.
 * Mirrors the prescription/treatment-plan/referral PDF style:
 *   - Blue header bar + Docito horizontal logo
 *   - Locale-aware (en/ru/uz/tr/ar/ja/ko/zh/es/pt/de) with proper font fallback
 *   - QR/verification footer for authenticity
 * Auth:
 *   - Owner of the entity (entity_id == userId for user-scoped invoices)
 *   - Practice/clinic admin or owner staff for facility-scoped invoices
 *   - super_admin
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, PDFFont, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";

import {
  secureHandler,
  errorResponse,
  corsHeaders,
} from "../_shared/security-middleware.ts";
import { sanitizeString } from "../_shared/input-validator.ts";
import {
  DOCITO_LOGO_PNG_BASE64,
  DOCITO_LOGO_FULL_PNG_BASE64,
  DOCITO_FONT_TTF_BASE64,
} from "./assets.ts";

type Locale = "en" | "ru" | "uz" | "tr" | "ar" | "ja" | "ko" | "zh" | "es" | "pt" | "de";

const schema = {
  invoice_id: { type: "uuid" as const, required: true },
  locale: { type: "string" as const, required: false, maxLength: 12, sanitize: true, trim: true },
};

const RTL_LOCALES = new Set<Locale>(["ar"]);
const CJK_LOCALES = new Set<Locale>(["ja", "ko", "zh"]);

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    invoice: "Invoice", invoiceNumber: "Invoice No.", billedTo: "Billed To",
    issuedAt: "Issued", dueAt: "Due", paidAt: "Paid",
    status: "Status", currency: "Currency", description: "Description",
    amountDue: "Amount Due", amountPaid: "Amount Paid", amountRemaining: "Balance Due",
    lineItems: "Line Items", item: "Item", quantity: "Qty", unitPrice: "Unit Price", total: "Total",
    subtotal: "Subtotal", verificationCode: "Verification Code", verifyAt: "Scan to verify",
    generatedBy: "Generated by Docito (docito.app)", confidential: "Confidential Invoice",
    notes: "Notes", thankYou: "Thank you for your business.", na: "—",
    page: "Page", of: "of",
  },
  ru: {
    invoice: "Счёт", invoiceNumber: "Номер счёта", billedTo: "Получатель",
    issuedAt: "Выставлен", dueAt: "Срок оплаты", paidAt: "Оплачен",
    status: "Статус", currency: "Валюта", description: "Описание",
    amountDue: "К оплате", amountPaid: "Оплачено", amountRemaining: "Остаток",
    lineItems: "Позиции", item: "Позиция", quantity: "Кол-во", unitPrice: "Цена", total: "Итого",
    subtotal: "Промежуточный итог", verificationCode: "Код проверки", verifyAt: "Сканируйте для проверки",
    generatedBy: "Сформировано в Docito (docito.app)", confidential: "Конфиденциальный счёт",
    notes: "Примечания", thankYou: "Благодарим за сотрудничество.", na: "—",
    page: "Стр.", of: "из",
  },
  uz: {
    invoice: "Hisob-faktura", invoiceNumber: "Hisob raqami", billedTo: "Qabul qiluvchi",
    issuedAt: "Sana", dueAt: "To'lash muddati", paidAt: "To'langan sana",
    status: "Holat", currency: "Valyuta", description: "Tavsif",
    amountDue: "To'lanishi kerak", amountPaid: "To'langan", amountRemaining: "Qoldiq",
    lineItems: "Pozitsiyalar", item: "Element", quantity: "Soni", unitPrice: "Narxi", total: "Jami",
    subtotal: "Oraliq jami", verificationCode: "Tasdiqlash kodi", verifyAt: "Tekshirish uchun skaner qiling",
    generatedBy: "Docito orqali yaratildi (docito.app)", confidential: "Maxfiy hisob-faktura",
    notes: "Izohlar", thankYou: "Hamkorligingiz uchun rahmat.", na: "—",
    page: "Sahifa", of: "/",
  },
  tr: {
    invoice: "Fatura", invoiceNumber: "Fatura No.", billedTo: "Fatura Edilen",
    issuedAt: "Düzenlendi", dueAt: "Son Ödeme", paidAt: "Ödendi",
    status: "Durum", currency: "Para Birimi", description: "Açıklama",
    amountDue: "Ödenecek Tutar", amountPaid: "Ödenen", amountRemaining: "Kalan",
    lineItems: "Kalemler", item: "Ürün", quantity: "Adet", unitPrice: "Birim Fiyat", total: "Toplam",
    subtotal: "Ara Toplam", verificationCode: "Doğrulama Kodu", verifyAt: "Doğrulamak için tarayın",
    generatedBy: "Docito tarafından oluşturuldu (docito.app)", confidential: "Gizli Fatura",
    notes: "Notlar", thankYou: "İşbirliğiniz için teşekkürler.", na: "—",
    page: "Sayfa", of: "/",
  },
  ar: {
    invoice: "فاتورة", invoiceNumber: "رقم الفاتورة", billedTo: "الفاتورة لـ",
    issuedAt: "تاريخ الإصدار", dueAt: "تاريخ الاستحقاق", paidAt: "تاريخ الدفع",
    status: "الحالة", currency: "العملة", description: "الوصف",
    amountDue: "المبلغ المستحق", amountPaid: "المبلغ المدفوع", amountRemaining: "الرصيد المتبقي",
    lineItems: "البنود", item: "البند", quantity: "الكمية", unitPrice: "سعر الوحدة", total: "الإجمالي",
    subtotal: "المجموع الفرعي", verificationCode: "رمز التحقق", verifyAt: "امسح للتحقق",
    generatedBy: "تم الإنشاء بواسطة Docito (docito.app)", confidential: "فاتورة سرية",
    notes: "ملاحظات", thankYou: "شكراً لتعاملكم معنا.", na: "—",
    page: "صفحة", of: "من",
  },
  ja: {
    invoice: "請求書", invoiceNumber: "請求書番号", billedTo: "請求先",
    issuedAt: "発行日", dueAt: "支払期日", paidAt: "支払日",
    status: "ステータス", currency: "通貨", description: "摘要",
    amountDue: "請求金額", amountPaid: "支払済", amountRemaining: "残額",
    lineItems: "明細", item: "項目", quantity: "数量", unitPrice: "単価", total: "金額",
    subtotal: "小計", verificationCode: "検証コード", verifyAt: "スキャンして確認",
    generatedBy: "Docito で生成 (docito.app)", confidential: "機密請求書",
    notes: "備考", thankYou: "ご利用ありがとうございます。", na: "—",
    page: "ページ", of: "/",
  },
  ko: {
    invoice: "청구서", invoiceNumber: "청구서 번호", billedTo: "청구 대상",
    issuedAt: "발행일", dueAt: "지급 기한", paidAt: "지급일",
    status: "상태", currency: "통화", description: "설명",
    amountDue: "청구 금액", amountPaid: "지급액", amountRemaining: "잔액",
    lineItems: "항목", item: "품목", quantity: "수량", unitPrice: "단가", total: "합계",
    subtotal: "소계", verificationCode: "검증 코드", verifyAt: "스캔하여 확인",
    generatedBy: "Docito에서 생성 (docito.app)", confidential: "기밀 청구서",
    notes: "메모", thankYou: "이용해 주셔서 감사합니다.", na: "—",
    page: "페이지", of: "/",
  },
  zh: {
    invoice: "发票", invoiceNumber: "发票编号", billedTo: "开票对象",
    issuedAt: "开票日期", dueAt: "到期日", paidAt: "支付日期",
    status: "状态", currency: "货币", description: "描述",
    amountDue: "应付金额", amountPaid: "已付金额", amountRemaining: "余额",
    lineItems: "明细", item: "项目", quantity: "数量", unitPrice: "单价", total: "金额",
    subtotal: "小计", verificationCode: "验证代码", verifyAt: "扫描验证",
    generatedBy: "由 Docito 生成 (docito.app)", confidential: "机密发票",
    notes: "备注", thankYou: "感谢您的惠顾。", na: "—",
    page: "第", of: "/",
  },
  es: {
    invoice: "Factura", invoiceNumber: "N. de factura", billedTo: "Facturado a",
    issuedAt: "Emitida", dueAt: "Vencimiento", paidAt: "Pagada",
    status: "Estado", currency: "Moneda", description: "Descripción",
    amountDue: "Monto adeudado", amountPaid: "Monto pagado", amountRemaining: "Saldo pendiente",
    lineItems: "Conceptos", item: "Concepto", quantity: "Cant.", unitPrice: "Precio unitario", total: "Total",
    subtotal: "Subtotal", verificationCode: "Código de verificación", verifyAt: "Escanear para verificar",
    generatedBy: "Generado por Docito (docito.app)", confidential: "Factura confidencial",
    notes: "Notas", thankYou: "Gracias por su preferencia.", na: "—",
    page: "Página", of: "de",
  },
  pt: {
    invoice: "Fatura", invoiceNumber: "N. da fatura", billedTo: "Faturado para",
    issuedAt: "Emitida", dueAt: "Vencimento", paidAt: "Paga",
    status: "Status", currency: "Moeda", description: "Descrição",
    amountDue: "Valor devido", amountPaid: "Valor pago", amountRemaining: "Saldo devedor",
    lineItems: "Itens", item: "Item", quantity: "Qtd.", unitPrice: "Preço unitário", total: "Total",
    subtotal: "Subtotal", verificationCode: "Código de verificação", verifyAt: "Escanear para verificar",
    generatedBy: "Gerado por Docito (docito.app)", confidential: "Fatura confidencial",
    notes: "Notas", thankYou: "Obrigado pela sua preferência.", na: "—",
    page: "Página", of: "de",
  },
  de: {
    invoice: "Rechnung", invoiceNumber: "Rechnungsnr.", billedTo: "Rechnungsempfänger",
    issuedAt: "Ausgestellt", dueAt: "Fällig", paidAt: "Bezahlt am",
    status: "Status", currency: "Währung", description: "Beschreibung",
    amountDue: "Fälliger Betrag", amountPaid: "Bezahlt", amountRemaining: "Restbetrag",
    lineItems: "Positionen", item: "Position", quantity: "Menge", unitPrice: "Einzelpreis", total: "Summe",
    subtotal: "Zwischensumme", verificationCode: "Verifizierungscode", verifyAt: "Scannen zur Verifizierung",
    generatedBy: "Erstellt von Docito (docito.app)", confidential: "Vertrauliche Rechnung",
    notes: "Anmerkungen", thankYou: "Vielen Dank für Ihr Vertrauen.", na: "—",
    page: "Seite", of: "von",
  },
};

function i(locale: Locale, key: string): string {
  return I18N[locale]?.[key] ?? I18N.en[key] ?? key;
}

function normalizeLocale(v?: string): Locale {
  const r = (sanitizeString(v || "", 12) || "").toLowerCase();
  if (r.startsWith("ru")) return "ru"; if (r.startsWith("uz")) return "uz";
  if (r.startsWith("tr")) return "tr"; if (r.startsWith("ar")) return "ar";
  if (r.startsWith("ja")) return "ja"; if (r.startsWith("ko")) return "ko";
  if (r.startsWith("zh")) return "zh"; if (r.startsWith("es")) return "es";
  if (r.startsWith("pt")) return "pt"; if (r.startsWith("de")) return "de";
  return "en";
}

function safe(v: unknown, max = 500): string {
  const s = typeof v === "string" ? v : v == null ? "" : String(v);
  return sanitizeString(s, max) || "";
}

function b64(s: string): Uint8Array {
  const clean = (s || "").replace(/\s+/g, "");
  if (!clean) return new Uint8Array(0);
  try {
    const bin = atob(clean);
    const out = new Uint8Array(bin.length);
    for (let j = 0; j < bin.length; j++) out[j] = bin.charCodeAt(j);
    return out;
  } catch { return new Uint8Array(0); }
}

function fmtDate(v: unknown, locale: Locale): string {
  const s = typeof v === "string" ? v : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return safe(s, 32);
  const y = d.getUTCFullYear(), m = String(d.getUTCMonth() + 1).padStart(2, "0"), dd = String(d.getUTCDate()).padStart(2, "0");
  return (locale === "ru" || locale === "uz") ? `${dd}.${m}.${y}` : `${y}-${m}-${dd}`;
}

function fmtMoney(cents: number, currency: string): string {
  const amount = (Number(cents) || 0) / 100;
  const cc = (currency || "USD").toUpperCase();
  try {
    return new Intl.NumberFormat("en-US", { style: "currency", currency: cc }).format(amount);
  } catch {
    return `${amount.toFixed(2)} ${cc}`;
  }
}

function sanitizePdf(s: string): string {
  return String(s || "")
    .replace(/\u2013/g, "-").replace(/\u2014/g, "--")
    .replace(/\u2018/g, "'").replace(/\u2019/g, "'")
    .replace(/\u201C/g, '"').replace(/\u201D/g, '"')
    .replace(/\u2026/g, "...").replace(/\u00A0/g, " ");
}

async function loadFont(pdf: PDFDocument, locale: Locale): Promise<PDFFont> {
  pdf.registerFontkit(fontkit);
  try {
    let bytes: Uint8Array;
    if (locale === "ar") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf")).arrayBuffer().then(a => new Uint8Array(a));
    else if (locale === "ja") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf")).arrayBuffer().then(a => new Uint8Array(a));
    else if (locale === "ko") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf")).arrayBuffer().then(a => new Uint8Array(a));
    else if (locale === "zh") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf")).arrayBuffer().then(a => new Uint8Array(a));
    else bytes = b64(DOCITO_FONT_TTF_BASE64);
    if (bytes.length > 0) return await pdf.embedFont(bytes, { subset: true });
  } catch { /* fallback */ }
  return await pdf.embedFont(StandardFonts.Helvetica);
}

function wrap(text: string, font: PDFFont, size: number, maxW: number, locale: Locale): string[] {
  if (!text) return [];
  const cjk = CJK_LOCALES.has(locale);
  const meas = (s: string) => { try { return font.widthOfTextAtSize(s, size); } catch { return s.length * size * 0.6; } };
  const lines: string[] = [];
  for (const para of text.replace(/\r\n/g, "\n").split("\n")) {
    if (!para.trim()) { lines.push(""); continue; }
    const tokens = cjk ? Array.from(para) : para.trim().split(/\s+/).filter(Boolean);
    let cur = "";
    for (const tok of tokens) {
      const next = cur + (cur && !cjk ? " " : "") + tok;
      if (!cur || meas(next) <= maxW) cur = next;
      else { if (cur) lines.push(cur); cur = tok; }
    }
    if (cur) lines.push(cur);
  }
  return lines;
}

serve(async (req) => {
  const { response, context, validatedBody } = await secureHandler(req, "invoice-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "expensive",
    validationSchema: schema,
  });

  if (response) return response;
  if (!context || !validatedBody) return errorResponse("Internal server error", 500);

  try {
    const { userId, roles, serviceClient: svc } = context;
    const body = validatedBody as { invoice_id: string; locale?: string };

    let locale: Locale = normalizeLocale(body.locale);
    if (!body.locale) {
      try {
        const { data: prof } = await svc.from("profiles").select("language").eq("user_id", userId).maybeSingle();
        locale = normalizeLocale((prof as any)?.language) || "en";
      } catch { /* ignore */ }
    }

    // Fetch invoice
    const { data: inv, error: invErr } = await svc
      .from("billing_invoices")
      .select("*")
      .eq("id", body.invoice_id)
      .maybeSingle();

    if (invErr) return errorResponse("Failed to fetch invoice", 500);
    if (!inv) return errorResponse("Invoice not found", 404);

    const r: any = inv;

    // Authorization
    const isSuperAdmin = (roles || []).includes("super_admin");
    let allowed = isSuperAdmin;

    if (!allowed && r.entity_type === "user" && r.entity_id === userId) allowed = true;

    if (!allowed && (r.entity_type === "practice" || r.entity_type === "clinic")) {
      const { data: prac } = await svc.from("practices").select("id").eq("id", r.entity_id).eq("admin_id", userId).maybeSingle();
      if (prac) allowed = true;
      if (!allowed) {
        const { data: staff } = await svc.from("clinic_staff").select("id").eq("practice_id", r.entity_id).eq("user_id", userId).eq("status", "active").maybeSingle();
        if (staff) allowed = true;
      }
    }

    if (!allowed && r.entity_type === "doctor") {
      const { data: doc } = await svc.from("doctors").select("id").eq("id", r.entity_id).eq("user_id", userId).maybeSingle();
      if (doc) allowed = true;
    }

    if (!allowed && r.entity_type === "pharmacy") {
      const { data: ph } = await svc.from("pharmacies").select("id").eq("id", r.entity_id).eq("admin_id", userId).maybeSingle();
      if (ph) allowed = true;
    }

    if (!allowed) return errorResponse("Forbidden", 403);

    // Resolve "billed to" name
    let billedToName = "—";
    try {
      if (r.entity_type === "user") {
        const { data: prof } = await svc.from("profiles").select("full_name, email").eq("user_id", r.entity_id).maybeSingle();
        billedToName = safe((prof as any)?.full_name || (prof as any)?.email, 200) || "—";
      } else if (r.entity_type === "practice" || r.entity_type === "clinic") {
        const { data: p } = await svc.from("practices").select("name").eq("id", r.entity_id).maybeSingle();
        billedToName = safe((p as any)?.name, 200) || "—";
      } else if (r.entity_type === "doctor") {
        const { data: d } = await svc.from("doctors").select("user_id").eq("id", r.entity_id).maybeSingle();
        if ((d as any)?.user_id) {
          const { data: prof } = await svc.from("profiles").select("full_name").eq("user_id", (d as any).user_id).maybeSingle();
          billedToName = safe((prof as any)?.full_name, 200) || "—";
        }
      } else if (r.entity_type === "pharmacy") {
        const { data: p } = await svc.from("pharmacies").select("name").eq("id", r.entity_id).maybeSingle();
        billedToName = safe((p as any)?.name, 200) || "—";
      }
    } catch { /* ignore */ }

    const verificationCode = safe((r.metadata?.verification_code) || r.id.slice(0, 12), 80);
    const siteBase = (Deno.env.get("PUBLIC_SITE_URL") || "https://docito.app").replace(/\/$/, "");
    const verifyUrl = `${siteBase}/verify?type=invoice&code=${encodeURIComponent(r.id)}`;

    // PDF layout constants
    const W = 595.28, H = 841.89;
    const margin = 44;
    const HEADER_H = 38;
    const FOOTER_H = 100;

    const pdf = await PDFDocument.create();
    const font = await loadFont(pdf, locale);
    const rtl = RTL_LOCALES.has(locale);

    const blue = rgb(0.145, 0.388, 0.922);
    const blueLight = rgb(0.93, 0.96, 1.0);
    const textDark = rgb(0.05, 0.05, 0.05);
    const textMuted = rgb(0.35, 0.35, 0.35);
    const borderLight = rgb(0.88, 0.88, 0.88);

    const fullLogoBytes = b64(DOCITO_LOGO_FULL_PNG_BASE64);
    let fullLogo: any = null; let fullLogoW = 0; const fullLogoH = 24;
    if (fullLogoBytes.length) { try { fullLogo = await pdf.embedPng(fullLogoBytes); fullLogoW = (fullLogo.width / fullLogo.height) * fullLogoH; } catch { /* ignore */ } }

    const iconBytes = b64(DOCITO_LOGO_PNG_BASE64);
    let iconLogo: any = null; const iconLogoW = 16; let iconLogoH = 16;
    if (iconBytes.length) { try { iconLogo = await pdf.embedPng(iconBytes); iconLogoH = (iconLogo.height / iconLogo.width) * iconLogoW; } catch { /* ignore */ } }

    let qrImg: any = null;
    const QR_SIZE = 80;
    try {
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 200, errorCorrectionLevel: "M" });
      const qrB64 = qrDataUrl.split(",")[1] || "";
      if (qrB64) qrImg = await pdf.embedPng(b64(qrB64));
    } catch { /* ignore */ }

    let page = pdf.addPage([W, H]);
    let y = H - margin;

    const wrappedLines = (text: string, maxW: number, size = 9.5) => wrap(sanitizePdf(text), font, size, maxW, locale);

    const drawHeader = () => {
      page.drawRectangle({ x: 0, y: H - HEADER_H, width: W, height: HEADER_H, color: blue });
      if (fullLogo && fullLogoW > 0) {
        page.drawImage(fullLogo, { x: margin, y: H - HEADER_H + (HEADER_H - fullLogoH) / 2, width: fullLogoW, height: fullLogoH });
      } else {
        try { page.drawText("DOCITO", { x: margin, y: H - HEADER_H + 14, size: 14, font, color: rgb(1, 1, 1) }); } catch { /* ignore */ }
      }
      const label = sanitizePdf(i(locale, "invoice"));
      try { const lw = font.widthOfTextAtSize(label, 11); page.drawText(label, { x: W - margin - lw, y: H - HEADER_H + (HEADER_H + 11) / 2 - 4, size: 11, font, color: rgb(1, 1, 1) }); } catch { /* ignore */ }
    };

    const drawVerifyFooter = (pg: typeof page, pageNum: number, pageCount: number) => {
      const fY = margin;
      pg.drawLine({ start: { x: margin, y: fY + FOOTER_H }, end: { x: W - margin, y: fY + FOOTER_H }, thickness: 0.8, color: borderLight });

      const qrX = W - margin - QR_SIZE;
      const qrY = fY + (FOOTER_H - QR_SIZE) / 2;
      if (qrImg) pg.drawImage(qrImg, { x: qrX, y: qrY, width: QR_SIZE, height: QR_SIZE });

      const textAreaW = W - margin * 2 - QR_SIZE - 16;
      let leftX = margin;
      if (iconLogo) {
        pg.drawImage(iconLogo, { x: leftX, y: fY + FOOTER_H - iconLogoH - 4, width: iconLogoW, height: iconLogoH });
        leftX += iconLogoW + 5;
      }
      try { pg.drawText(sanitizePdf(i(locale, "confidential")), { x: leftX, y: fY + FOOTER_H - 12, size: 8, font, color: textDark }); } catch { /* ignore */ }
      try { pg.drawText(sanitizePdf(i(locale, "generatedBy")), { x: leftX, y: fY + FOOTER_H - 22, size: 7.5, font, color: textMuted }); } catch { /* ignore */ }

      const vcLine = sanitizePdf(`${i(locale, "verificationCode")}: ${verificationCode}`);
      const vuLine = sanitizePdf(`${i(locale, "verifyAt")}: ${verifyUrl}`);
      try { pg.drawText(vcLine, { x: margin, y: fY + FOOTER_H - 42, size: 8.5, font, color: textDark }); } catch { /* ignore */ }
      try {
        const vuLines = wrap(vuLine, font, 7.5, textAreaW, locale);
        let yy = fY + FOOTER_H - 54;
        for (const line of vuLines) { try { pg.drawText(line, { x: margin, y: yy, size: 7.5, font, color: textMuted }); } catch { /* ignore */ } yy -= 9; }
      } catch { /* ignore */ }

      const pgLabel = `${i(locale, "page")} ${pageNum} ${i(locale, "of")} ${pageCount}`;
      try { const lw = font.widthOfTextAtSize(pgLabel, 8); pg.drawText(pgLabel, { x: W - margin - lw, y: fY + 6, size: 8, font, color: textMuted }); } catch { /* ignore */ }
    };

    const bodyBottom = margin + FOOTER_H + 8;

    const newPage = () => {
      page = pdf.addPage([W, H]);
      y = H - margin;
      drawHeader();
      y = H - HEADER_H - 18;
    };

    const ensure = (needed: number) => { if (y - needed < bodyBottom) newPage(); };

    const section = (key: string) => {
      ensure(28);
      y -= 8;
      const label = sanitizePdf(i(locale, key));
      try { const lw = font.widthOfTextAtSize(label, 11); page.drawText(label, { x: rtl ? W - margin - lw : margin, y, size: 11, font, color: blue }); } catch { /* ignore */ }
      page.drawLine({ start: { x: margin, y: y - 3 }, end: { x: W - margin, y: y - 3 }, thickness: 0.8, color: borderLight });
      y -= 11 + 10;
    };

    const LW = 148, VX = margin + LW, VMW = W - margin - VX;

    const kv = (key: string, value: string | null | undefined) => {
      ensure(14);
      const label = sanitizePdf(i(locale, key));
      const val = (value || "").trim() || i(locale, "na");
      const lines = wrappedLines(val, VMW, 9.5);
      try { page.drawText(label, { x: rtl ? W - margin - font.widthOfTextAtSize(label, 9.5) : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
      let yy = y;
      for (const line of lines) {
        try { page.drawText(line, { x: rtl ? W - margin - LW - font.widthOfTextAtSize(line, 9.5) : VX, y: yy, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        yy -= 13;
      }
      y = yy;
    };

    // Page 1
    drawHeader();
    y = H - HEADER_H - 20;

    const titleTxt = sanitizePdf(i(locale, "invoice"));
    try { const tw = font.widthOfTextAtSize(titleTxt, 20); page.drawText(titleTxt, { x: rtl ? W - margin - tw : margin, y, size: 20, font, color: blue }); } catch { /* ignore */ }
    y -= 24;
    const invNum = sanitizePdf(`${i(locale, "invoiceNumber")}: ${safe(r.id, 60)}`);
    try { const sw = font.widthOfTextAtSize(invNum, 9.5); page.drawText(invNum, { x: rtl ? W - margin - sw : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
    y -= 8;
    page.drawRectangle({ x: margin, y, width: W - margin * 2, height: 2, color: blue });
    y -= 16;

    // Summary box
    ensure(72);
    const boxH = 64;
    const boxY = y - boxH;
    page.drawRectangle({ x: margin, y: boxY, width: W - margin * 2, height: boxH, color: blueLight, borderColor: borderLight, borderWidth: 0.8 });
    let mY = y - 14;
    const mX = margin + 12;
    const writeSummary = (lk: string, v: string) => {
      const lbl = sanitizePdf(`${i(locale, lk)}: `);
      try { page.drawText(lbl, { x: mX, y: mY, size: 8.5, font, color: textMuted }); } catch { /* ignore */ }
      try { const lw = font.widthOfTextAtSize(lbl, 8.5); page.drawText(sanitizePdf(v || "—"), { x: mX + lw, y: mY, size: 9, font, color: textDark }); } catch { /* ignore */ }
      mY -= 13;
    };
    writeSummary("billedTo", billedToName);
    writeSummary("issuedAt", fmtDate(r.created_at, locale));
    if (r.due_at) writeSummary("dueAt", fmtDate(r.due_at, locale));
    if (r.paid_at) writeSummary("paidAt", fmtDate(r.paid_at, locale));

    y = boxY - 16;

    // Details
    section("description");
    kv("status", safe(r.status, 60));
    kv("currency", safe(r.currency, 10).toUpperCase());
    if (r.description) kv("description", safe(r.description, 600));

    // Line items
    const lineItems: any[] = Array.isArray(r.line_items) ? r.line_items : [];
    if (lineItems.length > 0) {
      section("lineItems");
      for (const item of lineItems) {
        ensure(26);
        const desc = sanitizePdf(safe(item.description || item.name || item.product_name || "Item", 200));
        const qty = item.quantity != null ? String(item.quantity) : "1";
        const unit = item.unit_amount != null ? fmtMoney(item.unit_amount, r.currency || "USD") : (item.amount != null ? fmtMoney(item.amount, r.currency || "USD") : "—");
        const tot = item.amount != null ? fmtMoney(item.amount, r.currency || "USD") : "—";

        try { page.drawText(desc.slice(0, 70), { x: margin, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        try { page.drawText(qty, { x: W - margin - 200, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        try { page.drawText(unit, { x: W - margin - 140, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        try {
          const tw = font.widthOfTextAtSize(tot, 9.5);
          page.drawText(tot, { x: W - margin - tw, y, size: 9.5, font, color: textDark });
        } catch { /* ignore */ }
        y -= 14;
      }
      y -= 4;
      page.drawLine({ start: { x: margin, y }, end: { x: W - margin, y }, thickness: 0.5, color: borderLight });
      y -= 12;
    }

    // Totals
    section("amountDue");
    kv("amountDue", fmtMoney(r.amount_due_cents, r.currency || "USD"));
    if ((r.amount_paid_cents || 0) > 0) kv("amountPaid", fmtMoney(r.amount_paid_cents, r.currency || "USD"));
    kv("amountRemaining", fmtMoney(r.amount_remaining_cents, r.currency || "USD"));

    // Notes / thank you
    ensure(20);
    y -= 8;
    try {
      const ty = sanitizePdf(i(locale, "thankYou"));
      page.drawText(ty, { x: margin, y, size: 9.5, font, color: textMuted });
    } catch { /* ignore */ }

    // Footer on every page
    const pageCount = pdf.getPageCount();
    for (let p = 0; p < pageCount; p++) {
      drawVerifyFooter(pdf.getPage(p), p + 1, pageCount);
    }

    const pdfBytes = await pdf.save();
    const safeName = safe(r.id, 40).replace(/[^a-zA-Z0-9_-]/g, "_");

    return new Response(pdfBytes as unknown as BodyInit, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="invoice-${safeName}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    console.error("invoice-generate-pdf error:", e);
    return errorResponse("Failed to generate PDF", 500);
  }
});
