// supabase/functions/prescription-generate-pdf/index.ts
/**
 * Prescription PDF generator — Docito
 *
 * Matches brand style of treatment-plan and referral PDFs:
 *  - Blue header bar + Docito horizontal logo
 *  - Blue section headings + gray underline
 *  - QR code + verification block on every PDF (scannable authenticity check)
 *  - Docito icon stamp in footer + page X of Y
 *
 * Auth: doctor who wrote it | patient it belongs to | pharmacy staff | super_admin
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, PDFFont, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";

import {
  secureHandler,
  errorResponse,
  corsHeaders,
} from "../_shared/security-middleware.ts";
import { sanitizeString } from "../_shared/input-validator.ts";
import {
  DOCITO_LOGO_PNG_BASE64,
  DOCITO_LOGO_FULL_PNG_BASE64,
  DOCITO_FONT_TTF_BASE64,
} from "./assets.ts";

// ─── Types ────────────────────────────────────────────────────────────────────

type Locale = "en" | "ru" | "uz" | "tr" | "ar" | "ja" | "ko" | "zh" | "es" | "pt" | "de";

const schema = {
  prescription_id: { type: "uuid" as const, required: true },
  locale: { type: "string" as const, required: false, maxLength: 12, sanitize: true, trim: true },
};

const RTL_LOCALES = new Set<Locale>(["ar"]);
const CJK_LOCALES = new Set<Locale>(["ja", "ko", "zh"]);

// ─── i18n ─────────────────────────────────────────────────────────────────────

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    prescription:"Prescription",prescriptionNumber:"Prescription No.",
    verificationCode:"Verification Code",verifyAt:"Scan to verify",
    generatedBy:"Generated by Docito (docito.app)",
    patient:"Patient",prescribedBy:"Prescribed By",
    pharmacy:"Pharmacy",details:"Prescription Details",
    medications:"Medications",
    status:"Status",diagnosisCode:"Diagnosis Code",
    prescribedAt:"Prescribed",expiresAt:"Expires",
    refills:"Refills",notes:"Notes",
    medication:"Medication",dosage:"Dosage",frequency:"Frequency",
    quantity:"Quantity",unit:"Unit",instructions:"Instructions",
    substitutionsAllowed:"Substitutions Allowed",
    yes:"Yes",no:"No",na:"—",
    confidential:"Confidential Medical Prescription",
  },
  ru: {
    prescription:"Рецепт",prescriptionNumber:"Номер рецепта",
    verificationCode:"Код проверки",verifyAt:"Сканируйте для проверки",
    generatedBy:"Сформировано в Docito (docito.app)",
    patient:"Пациент",prescribedBy:"Врач",
    pharmacy:"Аптека",details:"Детали рецепта",
    medications:"Препараты",
    status:"Статус",diagnosisCode:"Код диагноза",
    prescribedAt:"Назначено",expiresAt:"Действительно до",
    refills:"Повторные выдачи",notes:"Примечания",
    medication:"Препарат",dosage:"Дозировка",frequency:"Частота",
    quantity:"Количество",unit:"Ед. изм.",instructions:"Инструкции",
    substitutionsAllowed:"Замена разрешена",
    yes:"Да",no:"Нет",na:"—",
    confidential:"Конфиденциальный медицинский рецепт",
  },
  uz: {
    prescription:"Retsept",prescriptionNumber:"Retsept raqami",
    verificationCode:"Tekshiruv kodi",verifyAt:"Tekshirish uchun skaner qiling",
    generatedBy:"Docito orqali yaratildi (docito.app)",
    patient:"Bemor",prescribedBy:"Shifokor",
    pharmacy:"Dorixona",details:"Retsept tafsilotlari",
    medications:"Dorilar",
    status:"Holat",diagnosisCode:"Tashxis kodi",
    prescribedAt:"Buyurilgan",expiresAt:"Amal qilish muddati",
    refills:"Qayta olish",notes:"Izohlar",
    medication:"Dori",dosage:"Dozasi",frequency:"Chastotasi",
    quantity:"Miqdori",unit:"Birlik",instructions:"Ko'rsatmalar",
    substitutionsAllowed:"Almashtirish ruxsat etilgan",
    yes:"Ha",no:"Yo'q",na:"—",
    confidential:"Maxfiy tibbiy retsept",
  },
  tr: {
    prescription:"Recete",prescriptionNumber:"Recete No.",
    verificationCode:"Dogrulama Kodu",verifyAt:"Dogrulamak icin tarayin",
    generatedBy:"Docito tarafindan olusturuldu (docito.app)",
    patient:"Hasta",prescribedBy:"Yazan Doktor",
    pharmacy:"Eczane",details:"Recete Detaylari",
    medications:"Ilaclar",
    status:"Durum",diagnosisCode:"Tani Kodu",
    prescribedAt:"Yazildi",expiresAt:"Gecerlilik",
    refills:"Tekrar Cekme",notes:"Notlar",
    medication:"Ilac",dosage:"Dozaj",frequency:"Siklik",
    quantity:"Miktar",unit:"Birim",instructions:"Talimatlar",
    substitutionsAllowed:"Muadil Kabul",
    yes:"Evet",no:"Hayir",na:"—",
    confidential:"Gizli Tip Recetesi",
  },
  ar: {
    prescription:"وصفة طبية",prescriptionNumber:"رقم الوصفة",
    verificationCode:"رمز التحقق",verifyAt:"امسح للتحقق",
    generatedBy:"تم الانشاء بواسطة Docito (docito.app)",
    patient:"المريض",prescribedBy:"الطبيب",
    pharmacy:"الصيدلية",details:"تفاصيل الوصفة",
    medications:"الادوية",
    status:"الحالة",diagnosisCode:"رمز التشخيص",
    prescribedAt:"تاريخ الوصفة",expiresAt:"تاريخ الانتهاء",
    refills:"اعادة الصرف",notes:"ملاحظات",
    medication:"الدواء",dosage:"الجرعة",frequency:"التكرار",
    quantity:"الكمية",unit:"الوحدة",instructions:"التعليمات",
    substitutionsAllowed:"الابدال مسموح",
    yes:"نعم",no:"لا",na:"—",
    confidential:"وصفة طبية سرية",
  },
  ja: {
    prescription:"処方箋",prescriptionNumber:"処方番号",
    verificationCode:"検証コード",verifyAt:"スキャンして確認",
    generatedBy:"Docito で生成 (docito.app)",
    patient:"患者",prescribedBy:"処方医",
    pharmacy:"薬局",details:"処方詳細",
    medications:"薬",
    status:"ステータス",diagnosisCode:"診断コード",
    prescribedAt:"処方日",expiresAt:"有効期限",
    refills:"再処方",notes:"備考",
    medication:"薬",dosage:"用量",frequency:"頻度",
    quantity:"数量",unit:"単位",instructions:"指示",
    substitutionsAllowed:"代替品可",
    yes:"はい",no:"いいえ",na:"—",
    confidential:"機密医療処方箋",
  },
  ko: {
    prescription:"처방전",prescriptionNumber:"처방 번호",
    verificationCode:"검증 코드",verifyAt:"스캔하여 확인",
    generatedBy:"Docito에서 생성 (docito.app)",
    patient:"환자",prescribedBy:"처방 의사",
    pharmacy:"약국",details:"처방 세부",
    medications:"약품",
    status:"상태",diagnosisCode:"진단 코드",
    prescribedAt:"처방일",expiresAt:"만료일",
    refills:"재처방",notes:"비고",
    medication:"약품",dosage:"용량",frequency:"빈도",
    quantity:"수량",unit:"단위",instructions:"지시사항",
    substitutionsAllowed:"대체 허용",
    yes:"예",no:"아니오",na:"—",
    confidential:"기밀 의료 처방전",
  },
  zh: {
    prescription:"处方",prescriptionNumber:"处方编号",
    verificationCode:"验证代码",verifyAt:"扫描验证",
    generatedBy:"由 Docito 生成 (docito.app)",
    patient:"患者",prescribedBy:"开方医生",
    pharmacy:"药房",details:"处方详情",
    medications:"药品",
    status:"状态",diagnosisCode:"诊断代码",
    prescribedAt:"开方日期",expiresAt:"有效期",
    refills:"再次配药",notes:"备注",
    medication:"药品",dosage:"剂量",frequency:"频率",
    quantity:"数量",unit:"单位",instructions:"用药说明",
    substitutionsAllowed:"允许替代",
    yes:"是",no:"否",na:"—",
    confidential:"机密医疗处方",
  },
  es: {
    prescription:"Receta",prescriptionNumber:"N. de receta",
    verificationCode:"Codigo de verificacion",verifyAt:"Escanear para verificar",
    generatedBy:"Generado por Docito (docito.app)",
    patient:"Paciente",prescribedBy:"Medico prescriptor",
    pharmacy:"Farmacia",details:"Detalles de la receta",
    medications:"Medicamentos",
    status:"Estado",diagnosisCode:"Codigo de diagnostico",
    prescribedAt:"Fecha de prescripcion",expiresAt:"Fecha de vencimiento",
    refills:"Recargas",notes:"Notas",
    medication:"Medicamento",dosage:"Dosis",frequency:"Frecuencia",
    quantity:"Cantidad",unit:"Unidad",instructions:"Instrucciones",
    substitutionsAllowed:"Sustituciones permitidas",
    yes:"Si",no:"No",na:"—",
    confidential:"Receta medica confidencial",
  },
  pt: {
    prescription:"Receita",prescriptionNumber:"N. da receita",
    verificationCode:"Codigo de verificacao",verifyAt:"Escanear para verificar",
    generatedBy:"Gerado por Docito (docito.app)",
    patient:"Paciente",prescribedBy:"Medico",
    pharmacy:"Farmacia",details:"Detalhes da receita",
    medications:"Medicamentos",
    status:"Status",diagnosisCode:"Codigo de diagnostico",
    prescribedAt:"Data da prescricao",expiresAt:"Data de validade",
    refills:"Recargas",notes:"Notas",
    medication:"Medicamento",dosage:"Dose",frequency:"Frequencia",
    quantity:"Quantidade",unit:"Unidade",instructions:"Instrucoes",
    substitutionsAllowed:"Substituicoes permitidas",
    yes:"Sim",no:"Nao",na:"—",
    confidential:"Receita medica confidencial",
  },
  de: {
    prescription:"Rezept",prescriptionNumber:"Rezept-Nr.",
    verificationCode:"Verifizierungscode",verifyAt:"Scannen zur Verifizierung",
    generatedBy:"Erstellt von Docito (docito.app)",
    patient:"Patient",prescribedBy:"Verschreibender Arzt",
    pharmacy:"Apotheke",details:"Rezeptdetails",
    medications:"Medikamente",
    status:"Status",diagnosisCode:"Diagnosecode",
    prescribedAt:"Ausgestellt",expiresAt:"Gültig bis",
    refills:"Wiederholungen",notes:"Notizen",
    medication:"Medikament",dosage:"Dosierung",frequency:"Häufigkeit",
    quantity:"Menge",unit:"Einheit",instructions:"Anweisungen",
    substitutionsAllowed:"Substitution erlaubt",
    yes:"Ja",no:"Nein",na:"—",
    confidential:"Vertrauliches medizinisches Rezept",
  },
};

function i(locale: Locale, key: string): string {
  return I18N[locale]?.[key] ?? I18N.en[key] ?? key;
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function normalizeLocale(v?: string): Locale {
  const r = (sanitizeString(v || "", 12) || "").toLowerCase();
  if (r.startsWith("ru")) return "ru"; if (r.startsWith("uz")) return "uz";
  if (r.startsWith("tr")) return "tr"; if (r.startsWith("ar")) return "ar";
  if (r.startsWith("ja")) return "ja"; if (r.startsWith("ko")) return "ko";
  if (r.startsWith("zh")) return "zh"; if (r.startsWith("es")) return "es";
  if (r.startsWith("pt")) return "pt"; if (r.startsWith("de")) return "de";
  return "en";
}

function safe(v: unknown, max = 500): string {
  const s = typeof v === "string" ? v : v == null ? "" : String(v);
  return sanitizeString(s, max) || "";
}

function b64(s: string): Uint8Array {
  const clean = (s || "").replace(/\s+/g, "");
  if (!clean) return new Uint8Array(0);
  try {
    const bin = atob(clean);
    const out = new Uint8Array(bin.length);
    for (let j = 0; j < bin.length; j++) out[j] = bin.charCodeAt(j);
    return out;
  } catch { return new Uint8Array(0); }
}

function fmtDate(v: unknown, locale: Locale): string {
  const s = typeof v === "string" ? v : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return safe(s, 32);
  const y = d.getUTCFullYear(), m = String(d.getUTCMonth()+1).padStart(2,"0"), dd = String(d.getUTCDate()).padStart(2,"0");
  return (locale === "ru" || locale === "uz") ? `${dd}.${m}.${y}` : `${y}-${m}-${dd}`;
}

function sanitizePdf(s: string): string {
  return String(s||"")
    .replace(/\u2013/g,"-").replace(/\u2014/g,"--")
    .replace(/\u2018/g,"'").replace(/\u2019/g,"'")
    .replace(/\u201C/g,'"').replace(/\u201D/g,'"')
    .replace(/\u2026/g,"...").replace(/\u00A0/g," ");
}

async function loadFont(pdf: PDFDocument, locale: Locale): Promise<PDFFont> {
  pdf.registerFontkit(fontkit);
  try {
    let bytes: Uint8Array;
    if (locale === "ar") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf")).arrayBuffer().then(a=>new Uint8Array(a));
    else if (locale === "ja") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf")).arrayBuffer().then(a=>new Uint8Array(a));
    else if (locale === "ko") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf")).arrayBuffer().then(a=>new Uint8Array(a));
    else if (locale === "zh") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf")).arrayBuffer().then(a=>new Uint8Array(a));
    else bytes = b64(DOCITO_FONT_TTF_BASE64);
    if (bytes.length > 0) return await pdf.embedFont(bytes, { subset: true });
  } catch { /* fallback */ }
  return await pdf.embedFont(StandardFonts.Helvetica);
}

function wrap(text: string, font: PDFFont, size: number, maxW: number, locale: Locale): string[] {
  if (!text) return [];
  const cjk = CJK_LOCALES.has(locale);
  const meas = (s: string) => { try { return font.widthOfTextAtSize(s, size); } catch { return s.length * size * 0.6; } };
  const lines: string[] = [];
  for (const para of text.replace(/\r\n/g,"\n").split("\n")) {
    if (!para.trim()) { lines.push(""); continue; }
    const tokens = cjk ? Array.from(para) : para.trim().split(/\s+/).filter(Boolean);
    let cur = "";
    for (const tok of tokens) {
      const next = cur + (cur && !cjk ? " " : "") + tok;
      if (!cur || meas(next) <= maxW) cur = next;
      else { if (cur) lines.push(cur); cur = tok; }
    }
    if (cur) lines.push(cur);
  }
  return lines;
}

// ─── Main handler ─────────────────────────────────────────────────────────────

serve(async (req) => {
  const { response, context, validatedBody } = await secureHandler(req, "prescription-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "expensive",
    validationSchema: schema,
  });

  if (response) return response;
  if (!context || !validatedBody) return errorResponse("Internal server error", 500);

  try {
    const { userId, roles, serviceClient: svc } = context;
    const body = validatedBody as { prescription_id: string; locale?: string };

    let locale: Locale = normalizeLocale(body.locale);
    if (!body.locale) {
      try {
        const { data: prof } = await svc.from("profiles").select("language").eq("user_id", userId).maybeSingle();
        locale = normalizeLocale((prof as any)?.language) || "en";
      } catch { /* ignore */ }
    }

    // ── Fetch prescription + items ───────────────────────────────────────────
    const { data: rx, error: rxErr } = await svc
      .from("prescriptions")
      .select(`
        id, prescription_number, verification_code, status,
        patient_id, doctor_id, pharmacy_id,
        prescribed_at, expires_at,
        refills_remaining, refills_total, notes, diagnosis_code,
        patient:patient_id(full_name, email, phone),
        doctor:doctor_id(specialty, user_id),
        pharmacy:pharmacy_id(name, address, phone),
        prescription_items(
          id, medication_name, medication_code, dosage, frequency,
          quantity, unit, instructions, substitutions_allowed
        )
      `)
      .eq("id", body.prescription_id)
      .maybeSingle();

    if (rxErr) return errorResponse("Failed to fetch prescription", 500);
    if (!rx) return errorResponse("Prescription not found", 404);

    const r: any = rx;

    // ── Authorization ────────────────────────────────────────────────────────
    const isSuperAdmin = (roles || []).includes("super_admin");
    let allowed = isSuperAdmin;

    if (!allowed && r.patient_id === userId) allowed = true;

    if (!allowed && r.doctor_id) {
      const { data: doc } = await svc.from("doctors").select("id").eq("id", r.doctor_id).eq("user_id", userId).maybeSingle();
      if (doc) allowed = true;
    }

    if (!allowed && r.pharmacy_id) {
      const { data: ps } = await svc.from("pharmacy_staff").select("id").eq("pharmacy_id", r.pharmacy_id).eq("user_id", userId).eq("status", "active").maybeSingle();
      if (ps) allowed = true;
      const { data: ph } = await svc.from("pharmacies").select("id").eq("id", r.pharmacy_id).eq("admin_id", userId).maybeSingle();
      if (ph) allowed = true;
    }

    if (!allowed) return errorResponse("Forbidden", 403);

    // ── Resolve doctor name ──────────────────────────────────────────────────
    let doctorName = "";
    if (r.doctor?.user_id) {
      try {
        const { data: dp } = await svc.from("profiles").select("full_name").eq("user_id", r.doctor.user_id).maybeSingle();
        doctorName = safe((dp as any)?.full_name, 120);
      } catch { /* ignore */ }
    }

    const verificationCode = safe(r.verification_code || r.prescription_number, 80);
    const siteBase = (Deno.env.get("PUBLIC_SITE_URL") || "https://docito.app").replace(/\/$/, "");
    const verifyUrl = `${siteBase}/verify?type=prescription&code=${encodeURIComponent(verificationCode)}`;

    // ─── PDF layout constants ─────────────────────────────────────────────────
    const W = 595.28, H = 841.89;
    const margin = 44;
    const HEADER_H = 38;
    const FOOTER_H = 100; // enough room for verify block + QR

    const pdf = await PDFDocument.create();
    const font = await loadFont(pdf, locale);
    const rtl = RTL_LOCALES.has(locale);

    const blue = rgb(0.145, 0.388, 0.922);
    const blueLight = rgb(0.93, 0.96, 1.0);
    const textDark = rgb(0.05, 0.05, 0.05);
    const textMuted = rgb(0.35, 0.35, 0.35);
    const borderLight = rgb(0.88, 0.88, 0.88);

    // ── Embed logos ───────────────────────────────────────────────────────────
    const fullLogoBytes = b64(DOCITO_LOGO_FULL_PNG_BASE64);
    let fullLogo: any = null; let fullLogoW = 0; const fullLogoH = 24;
    if (fullLogoBytes.length) { try { fullLogo = await pdf.embedPng(fullLogoBytes); fullLogoW = (fullLogo.width / fullLogo.height) * fullLogoH; } catch { /* ignore */ } }

    const iconBytes = b64(DOCITO_LOGO_PNG_BASE64);
    let iconLogo: any = null; const iconLogoW = 16; let iconLogoH = 16;
    if (iconBytes.length) { try { iconLogo = await pdf.embedPng(iconBytes); iconLogoH = (iconLogo.height / iconLogo.width) * iconLogoW; } catch { /* ignore */ } }

    // ── QR code (embed once, reuse image across pages) ────────────────────────
    let qrImg: any = null;
    const QR_SIZE = 80;
    try {
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 200, errorCorrectionLevel: "M" });
      const qrB64 = qrDataUrl.split(",")[1] || "";
      if (qrB64) qrImg = await pdf.embedPng(b64(qrB64));
    } catch { /* ignore */ }

    // ── Page management ───────────────────────────────────────────────────────
    let page = pdf.addPage([W, H]);
    let y = H - margin;

    const txt = (text: string, x: number, yy: number, size: number, color = textDark) => {
      const v = sanitizePdf(String(text || ""));
      try { const w = font.widthOfTextAtSize(v, size); page.drawText(v, { x: rtl ? x - w : x, y: yy, size, font, color }); } catch { /* ignore */ }
    };
    const txtR = (text: string, edge: number, yy: number, size: number, color = textDark) => {
      const v = sanitizePdf(String(text || ""));
      try { const w = font.widthOfTextAtSize(v, size); page.drawText(v, { x: edge - w, y: yy, size, font, color }); } catch { /* ignore */ }
    };
    const wrappedLines = (text: string, maxW: number, size = 9.5) => wrap(sanitizePdf(text), font, size, maxW, locale);

    const drawHeader = () => {
      page.drawRectangle({ x: 0, y: H - HEADER_H, width: W, height: HEADER_H, color: blue });
      if (fullLogo && fullLogoW > 0) {
        page.drawImage(fullLogo, { x: margin, y: H - HEADER_H + (HEADER_H - fullLogoH) / 2, width: fullLogoW, height: fullLogoH });
      } else {
        txt("DOCITO", margin, H - HEADER_H + 14, 14, rgb(1, 1, 1));
      }
      const label = sanitizePdf(i(locale, "prescription"));
      try { const lw = font.widthOfTextAtSize(label, 11); page.drawText(label, { x: W - margin - lw, y: H - HEADER_H + (HEADER_H + 11) / 2 - 4, size: 11, font, color: rgb(1, 1, 1) }); } catch { /* ignore */ }
    };

    // ── Verification + QR footer block (drawn on EVERY page at end) ───────────
    const drawVerifyFooter = (pg: typeof page, pageNum: number, pageCount: number) => {
      const fY = margin;

      // Gray divider
      pg.drawLine({ start: { x: margin, y: fY + FOOTER_H }, end: { x: W - margin, y: fY + FOOTER_H }, thickness: 0.8, color: borderLight });

      // QR on right side
      const qrX = W - margin - QR_SIZE;
      const qrY = fY + (FOOTER_H - QR_SIZE) / 2;
      if (qrImg) pg.drawImage(qrImg, { x: qrX, y: qrY, width: QR_SIZE, height: QR_SIZE });

      // Left: confidential + verification info
      const textAreaW = W - margin * 2 - QR_SIZE - 16;

      // Icon + confidential label
      let leftX = margin;
      if (iconLogo) {
        pg.drawImage(iconLogo, { x: leftX, y: fY + FOOTER_H - iconLogoH - 4, width: iconLogoW, height: iconLogoH });
        leftX += iconLogoW + 5;
      }
      const confText = sanitizePdf(i(locale, "confidential"));
      try { pg.drawText(confText, { x: leftX, y: fY + FOOTER_H - 12, size: 8, font, color: textDark }); } catch { /* ignore */ }
      try { pg.drawText(sanitizePdf(i(locale, "generatedBy")), { x: leftX, y: fY + FOOTER_H - 22, size: 7.5, font, color: textMuted }); } catch { /* ignore */ }

      // Verification code + URL
      const vcLine = sanitizePdf(`${i(locale, "verificationCode")}: ${verificationCode}`);
      const vuLine = sanitizePdf(`${i(locale, "verifyAt")}: ${verifyUrl}`);
      try { pg.drawText(vcLine, { x: margin, y: fY + FOOTER_H - 42, size: 8.5, font, color: textDark }); } catch { /* ignore */ }
      try {
        const vuLines = wrap(vuLine, font, 7.5, textAreaW, locale);
        let yy = fY + FOOTER_H - 54;
        for (const line of vuLines) { try { pg.drawText(line, { x: margin, y: yy, size: 7.5, font, color: textMuted }); } catch { /* ignore */ } yy -= 9; }
      } catch { /* ignore */ }

      // Page number
      const pgLabel = `Page ${pageNum} of ${pageCount}`;
      try { const lw = font.widthOfTextAtSize(pgLabel, 8); pg.drawText(pgLabel, { x: W - margin - lw, y: fY + 6, size: 8, font, color: textMuted }); } catch { /* ignore */ }
    };

    const bodyBottom = margin + FOOTER_H + 8;

    const newPage = () => {
      page = pdf.addPage([W, H]);
      y = H - margin;
      drawHeader();
      y = H - HEADER_H - 18;
    };

    const ensure = (needed: number) => { if (y - needed < bodyBottom) newPage(); };

    const section = (key: string) => {
      ensure(28);
      y -= 8;
      const label = sanitizePdf(i(locale, key));
      try { const lw = font.widthOfTextAtSize(label, 11); page.drawText(label, { x: rtl ? W - margin - lw : margin, y, size: 11, font, color: blue }); } catch { /* ignore */ }
      page.drawLine({ start: { x: margin, y: y - 3 }, end: { x: W - margin, y: y - 3 }, thickness: 0.8, color: borderLight });
      y -= 11 + 10;
    };

    const LW = 148, VX = margin + LW, VMW = W - margin - VX;

    const kv = (key: string, value: string | null | undefined) => {
      ensure(14);
      const label = sanitizePdf(i(locale, key));
      const val = (value || "").trim() || i(locale, "na");
      const lines = wrappedLines(val, VMW, 9.5);
      try { page.drawText(label, { x: rtl ? W - margin - font.widthOfTextAtSize(label, 9.5) : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
      let yy = y;
      for (const line of lines) {
        try { page.drawText(line, { x: rtl ? W - margin - LW - font.widthOfTextAtSize(line, 9.5) : VX, y: yy, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        yy -= 13;
      }
      y = yy;
    };

    // ══════════════════════════════════════════════════════════════════════════
    //  PAGE 1: Header + verification box + content
    // ══════════════════════════════════════════════════════════════════════════
    drawHeader();
    y = H - HEADER_H - 20;

    // Title
    const titleTxt = sanitizePdf(i(locale, "prescription"));
    try { const tw = font.widthOfTextAtSize(titleTxt, 20); page.drawText(titleTxt, { x: rtl ? W - margin - tw : margin, y, size: 20, font, color: blue }); } catch { /* ignore */ }
    y -= 24;
    const rxNum = sanitizePdf(`${i(locale, "prescriptionNumber")}: ${safe(r.prescription_number, 80)}`);
    try { const sw = font.widthOfTextAtSize(rxNum, 9.5); page.drawText(rxNum, { x: rtl ? W - margin - sw : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
    y -= 8;
    page.drawRectangle({ x: margin, y, width: W - margin * 2, height: 2, color: blue });
    y -= 16;

    // ── Inline verify block (first page only) ─────────────────────────────────
    ensure(88);
    const boxH = 80;
    const boxY = y - boxH;
    page.drawRectangle({ x: margin, y: boxY, width: W - margin * 2, height: boxH, color: blueLight, borderColor: borderLight, borderWidth: 0.8 });

    const qrX = rtl ? margin + 8 : W - margin - QR_SIZE - 8;
    if (qrImg) page.drawImage(qrImg, { x: qrX, y: boxY + (boxH - QR_SIZE + 8) / 2, width: QR_SIZE - 8, height: QR_SIZE - 8 });

    let mY = y - 14;
    const mX = rtl ? W - margin - 10 : margin + 10;
    const mW = W - margin * 2 - QR_SIZE - 20;

    const mLine = (lk: string, v: string) => {
      const lbl = sanitizePdf(`${i(locale, lk)}: `);
      try { page.drawText(lbl, { x: rtl ? mX - font.widthOfTextAtSize(lbl, 8) : mX, y: mY, size: 8, font, color: textMuted }); } catch { /* ignore */ }
      mY -= 10;
      const lines = wrap(sanitizePdf(v), font, 9, mW, locale);
      for (const line of lines) {
        try { page.drawText(line, { x: rtl ? mX - font.widthOfTextAtSize(line, 9) : mX + 8, y: mY, size: 9, font, color: textDark }); } catch { /* ignore */ }
        mY -= 11;
      }
      mY -= 3;
    };
    mLine("prescriptionNumber", safe(r.prescription_number, 80) || "—");
    mLine("verificationCode", verificationCode || "—");
    mLine("verifyAt", verifyUrl);

    y = boxY - 16;

    // ── Prescription details section ──────────────────────────────────────────
    section("details");
    kv("status", safe(r.status, 60));
    kv("prescribedAt", fmtDate(r.prescribed_at, locale));
    kv("expiresAt", fmtDate(r.expires_at, locale));
    kv("refills", r.refills_total > 0 ? `${r.refills_remaining} / ${r.refills_total}` : "—");
    if (r.diagnosis_code) kv("diagnosisCode", safe(r.diagnosis_code, 40));

    // ── Patient section ───────────────────────────────────────────────────────
    section("patient");
    kv("patient", safe(r.patient?.full_name, 120) || "—");
    if (r.patient?.phone) kv("phone", safe(r.patient.phone, 40));
    if (r.patient?.email) kv("email", safe(r.patient.email, 200));

    // ── Prescribed by ─────────────────────────────────────────────────────────
    section("prescribedBy");
    kv("prescribedBy", doctorName || "—");
    if (r.doctor?.specialty) kv("specialty", safe(r.doctor.specialty, 100));

    // ── Pharmacy ──────────────────────────────────────────────────────────────
    if (r.pharmacy) {
      section("pharmacy");
      kv("pharmacy", safe(r.pharmacy.name, 120) || "—");
      if (r.pharmacy.address) kv("address", safe(r.pharmacy.address, 200));
      if (r.pharmacy.phone) kv("phone", safe(r.pharmacy.phone, 40));
    }

    // ── Notes ─────────────────────────────────────────────────────────────────
    if (r.notes) {
      section("notes");
      ensure(20);
      const lines = wrappedLines(safe(r.notes, 2000), W - margin * 2 - 8, 9.5);
      for (const line of lines) {
        ensure(14);
        try { page.drawText(line, { x: rtl ? W - margin - 8 - font.widthOfTextAtSize(line, 9.5) : margin + 8, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        y -= 13;
      }
    }

    // ── Medications ───────────────────────────────────────────────────────────
    const items: any[] = Array.isArray(r.prescription_items) ? r.prescription_items : [];
    if (items.length > 0) {
      section("medications");

      for (let idx = 0; idx < items.length; idx++) {
        const item = items[idx];
        ensure(60);

        // Numbered drug box
        const boxTop = y + 4;
        const numLabel = sanitizePdf(`${idx + 1}.`);
        const numLabelSize = 11;
        try { page.drawText(numLabel, { x: margin, y: y, size: numLabelSize, font, color: blue }); } catch { /* ignore */ }

        const medName = sanitizePdf(safe(item.medication_name, 150));
        try {
          const mw = font.widthOfTextAtSize(medName, 10.5);
          page.drawText(medName, { x: rtl ? W - margin - 20 - mw : margin + 20, y, size: 10.5, font, color: textDark });
        } catch { /* ignore */ }
        y -= 14;

        // Sub-details in pairs
        const subKV = (lk: string, v: string) => {
          ensure(12);
          const lbl = sanitizePdf(`${i(locale, lk)}: `);
          const val = sanitizePdf(v || "—");
          try { page.drawText(lbl, { x: margin + 20, y, size: 8.5, font, color: textMuted }); } catch { /* ignore */ }
          try { const lw = font.widthOfTextAtSize(lbl, 8.5); page.drawText(val, { x: margin + 20 + lw, y, size: 8.5, font, color: textDark }); } catch { /* ignore */ }
          y -= 12;
        };

        subKV("dosage", safe(item.dosage, 80));
        subKV("frequency", safe(item.frequency, 80));
        subKV("quantity", item.quantity != null ? `${item.quantity}${item.unit ? ` ${safe(item.unit, 30)}` : ""}` : "—");
        if (item.instructions) subKV("instructions", safe(item.instructions, 300));
        subKV("substitutionsAllowed", item.substitutions_allowed ? i(locale, "yes") : i(locale, "no"));

        // Light separator between drugs
        if (idx < items.length - 1) {
          ensure(8);
          page.drawLine({ start: { x: margin + 20, y: y }, end: { x: W - margin, y: y }, thickness: 0.5, color: borderLight });
          y -= 10;
        } else {
          y -= 6;
        }
      }
    }

    // ── Draw verify footer on ALL pages ───────────────────────────────────────
    const pageCount = pdf.getPageCount();
    for (let p = 0; p < pageCount; p++) {
      drawVerifyFooter(pdf.getPage(p), p + 1, pageCount);
    }

    const pdfBytes = await pdf.save();
    const safeName = safe(r.prescription_number || r.id, 40).replace(/[^a-zA-Z0-9_-]/g, "_");

    return new Response(pdfBytes as unknown as BodyInit, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="prescription-${safeName}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    console.error("prescription-generate-pdf error:", e);
    return errorResponse("Failed to generate PDF", 500);
  }
});
