import jsPDF from 'jspdf';

export interface InvoiceLineItem {
  name: string;
  amount: number;
  quantity?: number;
  code?: string;
}

export interface InvoicePaymentRow {
  date: string;
  method: string;
  amount: number;
}

export interface InvoiceData {
  invoiceNumber: string;
  patientName: string;
  appointmentDate?: string;
  doctorName?: string;
  clinicName?: string;
  clinicAddress?: string;
  currency?: string;
  clinicLogoUrl?: string;
  clinicPhone?: string;
  items: InvoiceLineItem[];
  totalBilled: number;
  totalDiscount: number;
  totalPaid: number;
  outstanding: number;
  payments?: InvoicePaymentRow[];
}

type Locale = 'en' | 'ru' | 'uz' | 'ar' | 'tr' | 'es' | 'de' | 'zh' | 'pt' | 'ja' | 'ko';

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    invoice: 'INVOICE', invoiceNumber: 'Invoice No.', date: 'Date', dueDate: 'Due Date',
    billTo: 'Bill To', appointment: 'Appointment', doctor: 'Doctor:', code: 'Code',
    description: 'Description', amount: 'Amount', subtotal: 'Subtotal', discount: 'Discount',
    total: 'Total Due', amountPaid: 'Amount Paid', outstanding: 'Outstanding Balance',
    paymentHistory: 'Payment History', paidOn: 'Paid on', via: 'via',
    thankYou: 'Thank you for your trust.', generatedBy: 'Generated by Docito · docito.app',
    confidential: 'Confidential', page: 'Page', of: 'of',
  },
  ru: {
    invoice: 'СЧЁТ', invoiceNumber: '№ счёта', date: 'Дата', dueDate: 'Срок оплаты',
    billTo: 'Получатель', appointment: 'Приём', doctor: 'Врач:', code: 'Код',
    description: 'Описание', amount: 'Сумма', subtotal: 'Промежуточный итог', discount: 'Скидка',
    total: 'К оплате', amountPaid: 'Оплачено', outstanding: 'Остаток к оплате',
    paymentHistory: 'История платежей', paidOn: 'Оплачено', via: 'через',
    thankYou: 'Благодарим за доверие.', generatedBy: 'Сформировано Docito · docito.app',
    confidential: 'Конфиденциально', page: 'Страница', of: 'из',
  },
  uz: {
    invoice: 'HISOB', invoiceNumber: 'Hisob raqami', date: 'Sana', dueDate: "To'lov muddati",
    billTo: 'Qabul qiluvchi', appointment: 'Qabul', doctor: 'Shifokor:', code: 'Kod',
    description: 'Tavsif', amount: 'Summa', subtotal: 'Oraliq jami', discount: 'Chegirma',
    total: "To'lov summasi", amountPaid: "To'langan", outstanding: 'Qoldiq',
    paymentHistory: "To'lovlar tarixi", paidOn: "To'langan sana", via: 'orqali',
    thankYou: 'Ishonchingiz uchun rahmat.', generatedBy: 'Docito · docito.app tomonidan',
    confidential: 'Maxfiy', page: 'Bet', of: '/',
  },
  ar: {
    invoice: 'فاتورة', invoiceNumber: 'رقم الفاتورة', date: 'التاريخ', dueDate: 'تاريخ الاستحقاق',
    billTo: 'إلى', appointment: 'الموعد', doctor: 'الطبيب:', code: 'الرمز',
    description: 'الوصف', amount: 'المبلغ', subtotal: 'المجموع الفرعي', discount: 'الخصم',
    total: 'المجموع المستحق', amountPaid: 'المبلغ المدفوع', outstanding: 'الرصيد المستحق',
    paymentHistory: 'سجل الدفع', paidOn: 'دُفع في', via: 'عبر',
    thankYou: 'شكراً لثقتكم.', generatedBy: 'تم إنشاؤها بواسطة Docito · docito.app',
    confidential: 'سري', page: 'صفحة', of: 'من',
  },
  tr: {
    invoice: 'FATURA', invoiceNumber: 'Fatura No', date: 'Tarih', dueDate: 'Son Ödeme',
    billTo: 'Alıcı', appointment: 'Randevu', doctor: 'Doktor:', code: 'Kod',
    description: 'Açıklama', amount: 'Tutar', subtotal: 'Ara Toplam', discount: 'İndirim',
    total: 'Ödenecek Tutar', amountPaid: 'Ödenen Tutar', outstanding: 'Bakiye',
    paymentHistory: 'Ödeme Geçmişi', paidOn: 'Ödendi', via: 'ile',
    thankYou: 'Güveniniz için teşekkürler.', generatedBy: 'Docito · docito.app tarafından',
    confidential: 'Gizli', page: 'Sayfa', of: '/',
  },
  es: {
    invoice: 'FACTURA', invoiceNumber: 'N.º de factura', date: 'Fecha', dueDate: 'Vencimiento',
    billTo: 'Facturar a', appointment: 'Cita', doctor: 'Doctor:', code: 'Código',
    description: 'Descripción', amount: 'Monto', subtotal: 'Subtotal', discount: 'Descuento',
    total: 'Total a Pagar', amountPaid: 'Monto Pagado', outstanding: 'Saldo Pendiente',
    paymentHistory: 'Historial de Pagos', paidOn: 'Pagado el', via: 'vía',
    thankYou: 'Gracias por su confianza.', generatedBy: 'Generado por Docito · docito.app',
    confidential: 'Confidencial', page: 'Página', of: 'de',
  },
  de: {
    invoice: 'RECHNUNG', invoiceNumber: 'Rechnungsnr.', date: 'Datum', dueDate: 'Fällig am',
    billTo: 'Rechnung an', appointment: 'Termin', doctor: 'Arzt:', code: 'Code',
    description: 'Beschreibung', amount: 'Betrag', subtotal: 'Zwischensumme', discount: 'Rabatt',
    total: 'Fälliger Betrag', amountPaid: 'Bezahlt', outstanding: 'Offener Saldo',
    paymentHistory: 'Zahlungshistorie', paidOn: 'Bezahlt am', via: 'über',
    thankYou: 'Vielen Dank für Ihr Vertrauen.', generatedBy: 'Erstellt von Docito · docito.app',
    confidential: 'Vertraulich', page: 'Seite', of: 'von',
  },
  zh: {
    invoice: '发票', invoiceNumber: '发票号', date: '日期', dueDate: '到期日',
    billTo: '收件方', appointment: '预约', doctor: '医生:', code: '代码',
    description: '描述', amount: '金额', subtotal: '小计', discount: '折扣',
    total: '应付金额', amountPaid: '已付金额', outstanding: '未付余额',
    paymentHistory: '付款历史', paidOn: '付款日', via: '通过',
    thankYou: '感谢您的信任。', generatedBy: '由 Docito · docito.app 生成',
    confidential: '保密', page: '第', of: '页 / 共',
  },
  pt: {
    invoice: 'FATURA', invoiceNumber: 'Nº da Fatura', date: 'Data', dueDate: 'Vencimento',
    billTo: 'Faturar para', appointment: 'Consulta', doctor: 'Médico:', code: 'Código',
    description: 'Descrição', amount: 'Valor', subtotal: 'Subtotal', discount: 'Desconto',
    total: 'Total a Pagar', amountPaid: 'Valor Pago', outstanding: 'Saldo Devedor',
    paymentHistory: 'Histórico de Pagamentos', paidOn: 'Pago em', via: 'via',
    thankYou: 'Obrigado pela sua confiança.', generatedBy: 'Gerado por Docito · docito.app',
    confidential: 'Confidencial', page: 'Página', of: 'de',
  },
  ja: {
    invoice: '請求書', invoiceNumber: '請求書番号', date: '日付', dueDate: '支払期日',
    billTo: '請求先', appointment: '予約', doctor: '医師:', code: 'コード',
    description: '説明', amount: '金額', subtotal: '小計', discount: '割引',
    total: 'お支払い合計', amountPaid: '支払済額', outstanding: '未払い残高',
    paymentHistory: '支払い履歴', paidOn: '支払日', via: '経由',
    thankYou: 'ご信頼ありがとうございます。', generatedBy: 'Docito · docito.app により作成',
    confidential: '機密', page: 'ページ', of: '/',
  },
  ko: {
    invoice: '청구서', invoiceNumber: '청구서 번호', date: '날짜', dueDate: '지급 기한',
    billTo: '수신자', appointment: '예약', doctor: '의사:', code: '코드',
    description: '설명', amount: '금액', subtotal: '소계', discount: '할인',
    total: '총 청구액', amountPaid: '지급 금액', outstanding: '미납 잔액',
    paymentHistory: '결제 내역', paidOn: '지급일', via: '경유',
    thankYou: '신뢰해 주셔서 감사합니다.', generatedBy: 'Docito · docito.app 생성',
    confidential: '기밀', page: '페이지', of: '/',
  },
};

function normalizeLocale(v?: string): Locale {
  const c = (v || 'en').split('-')[0].toLowerCase();
  const supported: Locale[] = ['en','ru','uz','ar','tr','es','de','zh','pt','ja','ko'];
  return (supported as string[]).includes(c) ? (c as Locale) : 'en';
}

function tr(locale: Locale, key: string): string {
  return I18N[locale]?.[key] ?? I18N.en[key] ?? key;
}

const money = (n: number, currency = 'USD') => {
  try {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(n || 0);
  } catch {
    return `${(n || 0).toFixed(2)} ${currency}`;
  }
};

export async function generateInvoicePdf(data: InvoiceData, lang: string = 'en') {
  const locale = normalizeLocale(lang);
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = pdf.internal.pageSize.getWidth();
  const margin = 15;
  let y = margin;

  if (data.clinicLogoUrl) {
    try {
      const res = await fetch(data.clinicLogoUrl);
      if (res.ok) {
        const blob = await res.blob();
        const dataUrl: string = await new Promise((resolve, reject) => {
          const r = new FileReader();
          r.onloadend = () => resolve(r.result as string);
          r.onerror = () => reject(new Error('read failed'));
          r.readAsDataURL(blob);
        });
        const fmt = (data.clinicLogoUrl.toLowerCase().endsWith('.png') ? 'PNG' : 'JPEG');
        pdf.addImage(dataUrl, fmt, pageW - 55, 8, 40, 14);
      }
    } catch { /* silent */ }
  }

  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text(tr(locale, 'invoice'), margin, y);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const issueDate = new Date().toLocaleDateString();
  pdf.text(`#${data.invoiceNumber}`, pageW - margin, y, { align: 'right' });
  y += 6;
  pdf.text(`${tr(locale, 'date')}: ${issueDate}`, pageW - margin, y, { align: 'right' });
  y += 10;

  if (data.clinicName) {
    pdf.setFont('helvetica', 'bold');
    pdf.text(data.clinicName, margin, y);
    y += 5;
  }
  if (data.clinicAddress) {
    pdf.setFont('helvetica', 'normal');
    pdf.text(data.clinicAddress, margin, y);
    y += 5;
  }
  if (data.clinicPhone) {
    pdf.setFont('helvetica', 'normal');
    pdf.text(data.clinicPhone, margin, y);
    y += 5;
  }

  y += 4;
  pdf.setDrawColor(220);
  pdf.line(margin, y, pageW - margin, y);
  y += 6;

  pdf.setFont('helvetica', 'bold');
  pdf.text(tr(locale, 'billTo'), margin, y);
  pdf.text(tr(locale, 'appointment'), pageW / 2, y);
  y += 5;
  pdf.setFont('helvetica', 'normal');
  pdf.text(data.patientName || '—', margin, y);
  pdf.text(`${data.appointmentDate || ''}`, pageW / 2, y);
  y += 5;
  if (data.doctorName) {
    pdf.text(`${tr(locale, 'doctor')} ${data.doctorName}`, pageW / 2, y);
    y += 5;
  }

  y += 6;

  pdf.setFillColor(245, 247, 250);
  pdf.rect(margin, y - 4, pageW - margin * 2, 8, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.text(tr(locale, 'code'), margin + 2, y + 1);
  pdf.text(tr(locale, 'description'), margin + 28, y + 1);
  pdf.text(tr(locale, 'amount'), pageW - margin - 2, y + 1, { align: 'right' });
  y += 8;

  pdf.setFont('helvetica', 'normal');
  for (const item of data.items) {
    if (y > 250) { pdf.addPage(); y = margin; }
    const lines = pdf.splitTextToSize(item.name, pageW - margin * 2 - 65);
    pdf.text(item.code || '—', margin + 2, y);
    pdf.text(lines, margin + 28, y);
    pdf.text(money(item.amount, data.currency), pageW - margin - 2, y, { align: 'right' });
    y += Math.max(6, lines.length * 5);
  }

  y += 4;
  pdf.line(margin, y, pageW - margin, y);
  y += 6;

  const totalsX = pageW - margin - 60;
  const labelTotals: Array<[string, number]> = [
    [tr(locale, 'subtotal'), data.totalBilled],
    [tr(locale, 'discount'), -Math.abs(data.totalDiscount || 0)],
    [tr(locale, 'amountPaid'), -Math.abs(data.totalPaid || 0)],
  ];
  pdf.setFont('helvetica', 'normal');
  for (const [label, amt] of labelTotals) {
    pdf.text(label, totalsX, y);
    pdf.text(money(amt, data.currency), pageW - margin - 2, y, { align: 'right' });
    y += 6;
  }
  pdf.setFont('helvetica', 'bold');
  pdf.text(tr(locale, 'outstanding'), totalsX, y);
  pdf.text(money(data.outstanding, data.currency), pageW - margin - 2, y, { align: 'right' });
  y += 10;

  if (data.payments && data.payments.length > 0) {
    pdf.setFont('helvetica', 'bold');
    pdf.text(tr(locale, 'paymentHistory'), margin, y);
    y += 6;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    for (const p of data.payments) {
      if (y > 270) { pdf.addPage(); y = margin; }
      const dateStr = p.date ? new Date(p.date).toLocaleDateString() : '';
      pdf.text(`${dateStr} · ${p.method}`, margin + 2, y);
      pdf.text(money(p.amount, data.currency), pageW - margin - 2, y, { align: 'right' });
      y += 5;
    }
  }

  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(8);
  pdf.setTextColor(140);
  pdf.text(tr(locale, 'thankYou'), margin, 285);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(160);
  pdf.text(tr(locale, 'generatedBy'), margin, 290);
  pdf.setTextColor(0);

  const fname = `invoice_${data.invoiceNumber}_${(data.patientName || 'patient').replace(/\s+/g, '_')}.pdf`;
  pdf.save(fname);
}
