// supabase/functions/superbill-generate-pdf/index.ts
// Superbill PDF generator for insurance reimbursement.
// Produces a localized PDF for any row in `superbills`.

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, PDFFont, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";

import {
  secureHandler,
  errorResponse,
  corsHeaders,
} from "../_shared/security-middleware.ts";
import { sanitizeString } from "../_shared/input-validator.ts";
import {
  DOCITO_LOGO_PNG_BASE64,
  DOCITO_LOGO_FULL_PNG_BASE64,
  DOCITO_FONT_TTF_BASE64,
} from "../invoice-generate-pdf/assets.ts";

type Locale = "en" | "ru" | "uz" | "tr" | "ar" | "ja" | "ko" | "zh" | "es" | "pt" | "de";

const schema = {
  superbill_id: { type: "uuid" as const, required: true },
  locale: { type: "string" as const, required: false, maxLength: 12, sanitize: true, trim: true },
};

const CJK = new Set<Locale>(["ja", "ko", "zh"]);
const RTL = new Set<Locale>(["ar"]);

const T: Record<Locale, Record<string, string>> = {
  en: { title: "Superbill", number: "Superbill No.", patient: "Patient", provider: "Provider", clinic: "Clinic", serviceDate: "Service Date", dx: "Diagnosis Codes (ICD-10)", cpt: "Procedure Codes (CPT/HCPCS)", code: "Code", desc: "Description", units: "Units", fee: "Fee", total: "Total", status: "Status", currency: "Currency", notes: "Notes", verify: "Verification Code", scan: "Scan to verify", confidential: "Confidential Superbill", generatedBy: "Generated by Docito (docito.app)", reimbursementNote: "Submit this superbill to your insurance carrier for reimbursement.", page: "Page", of: "of", na: "—" },
  ru: { title: "Суперсчёт", number: "№ суперсчёта", patient: "Пациент", provider: "Врач", clinic: "Клиника", serviceDate: "Дата услуги", dx: "Диагнозы (МКБ-10)", cpt: "Коды процедур (CPT/HCPCS)", code: "Код", desc: "Описание", units: "Кол-во", fee: "Стоимость", total: "Итого", status: "Статус", currency: "Валюта", notes: "Примечания", verify: "Код проверки", scan: "Сканируйте для проверки", confidential: "Конфиденциальный суперсчёт", generatedBy: "Сформировано в Docito (docito.app)", reimbursementNote: "Передайте суперсчёт в страховую компанию для возмещения.", page: "Стр.", of: "из", na: "—" },
  uz: { title: "Superbill", number: "Superbill №", patient: "Bemor", provider: "Shifokor", clinic: "Klinika", serviceDate: "Xizmat sanasi", dx: "Tashxis kodlari (ICD-10)", cpt: "Protsedura kodlari (CPT)", code: "Kod", desc: "Tavsif", units: "Soni", fee: "Narx", total: "Jami", status: "Holat", currency: "Valyuta", notes: "Izohlar", verify: "Tasdiq kodi", scan: "Tekshirish uchun skaner qiling", confidential: "Maxfiy superbill", generatedBy: "Docito orqali yaratildi (docito.app)", reimbursementNote: "Qoplash uchun ushbu superbill-ni sug'urta kompaniyangizga taqdim eting.", page: "Sahifa", of: "/", na: "—" },
  tr: { title: "Superbill", number: "Superbill No.", patient: "Hasta", provider: "Doktor", clinic: "Klinik", serviceDate: "Hizmet Tarihi", dx: "Tanı Kodları (ICD-10)", cpt: "Prosedür Kodları (CPT)", code: "Kod", desc: "Açıklama", units: "Adet", fee: "Ücret", total: "Toplam", status: "Durum", currency: "Para Birimi", notes: "Notlar", verify: "Doğrulama Kodu", scan: "Doğrulamak için tarayın", confidential: "Gizli Superbill", generatedBy: "Docito tarafından oluşturuldu (docito.app)", reimbursementNote: "Geri ödeme için bu superbill'i sigorta şirketinize iletin.", page: "Sayfa", of: "/", na: "—" },
  ar: { title: "فاتورة تأمين", number: "رقم الفاتورة", patient: "المريض", provider: "الطبيب", clinic: "العيادة", serviceDate: "تاريخ الخدمة", dx: "أكواد التشخيص (ICD-10)", cpt: "أكواد الإجراءات (CPT)", code: "الكود", desc: "الوصف", units: "الكمية", fee: "الرسوم", total: "الإجمالي", status: "الحالة", currency: "العملة", notes: "ملاحظات", verify: "رمز التحقق", scan: "امسح للتحقق", confidential: "فاتورة تأمين سرية", generatedBy: "تم الإنشاء بواسطة Docito (docito.app)", reimbursementNote: "قدم هذه الفاتورة إلى شركة التأمين لاسترداد المبلغ.", page: "صفحة", of: "من", na: "—" },
  ja: { title: "スーパービル", number: "スーパービル番号", patient: "患者", provider: "医師", clinic: "クリニック", serviceDate: "サービス日", dx: "診断コード (ICD-10)", cpt: "手技コード (CPT)", code: "コード", desc: "摘要", units: "数量", fee: "料金", total: "合計", status: "ステータス", currency: "通貨", notes: "備考", verify: "検証コード", scan: "スキャンして確認", confidential: "機密スーパービル", generatedBy: "Docito で生成 (docito.app)", reimbursementNote: "保険会社に提出して払い戻しを受けてください。", page: "ページ", of: "/", na: "—" },
  ko: { title: "수퍼빌", number: "수퍼빌 번호", patient: "환자", provider: "의사", clinic: "클리닉", serviceDate: "서비스 날짜", dx: "진단 코드 (ICD-10)", cpt: "시술 코드 (CPT)", code: "코드", desc: "설명", units: "수량", fee: "요금", total: "합계", status: "상태", currency: "통화", notes: "메모", verify: "검증 코드", scan: "스캔하여 확인", confidential: "기밀 수퍼빌", generatedBy: "Docito에서 생성 (docito.app)", reimbursementNote: "보험사에 제출하여 환급을 받으세요.", page: "페이지", of: "/", na: "—" },
  zh: { title: "超级账单", number: "超级账单编号", patient: "患者", provider: "医生", clinic: "诊所", serviceDate: "服务日期", dx: "诊断代码 (ICD-10)", cpt: "操作代码 (CPT)", code: "代码", desc: "描述", units: "数量", fee: "费用", total: "总计", status: "状态", currency: "货币", notes: "备注", verify: "验证代码", scan: "扫描验证", confidential: "机密超级账单", generatedBy: "由 Docito 生成 (docito.app)", reimbursementNote: "请将此超级账单提交至保险公司以申请理赔。", page: "第", of: "/", na: "—" },
  es: { title: "Superbill", number: "N. de Superbill", patient: "Paciente", provider: "Médico", clinic: "Clínica", serviceDate: "Fecha del servicio", dx: "Códigos de diagnóstico (ICD-10)", cpt: "Códigos de procedimiento (CPT)", code: "Código", desc: "Descripción", units: "Unid.", fee: "Tarifa", total: "Total", status: "Estado", currency: "Moneda", notes: "Notas", verify: "Código de verificación", scan: "Escanear para verificar", confidential: "Superbill confidencial", generatedBy: "Generado por Docito (docito.app)", reimbursementNote: "Envíe este superbill a su aseguradora para el reembolso.", page: "Página", of: "de", na: "—" },
  pt: { title: "Superbill", number: "N. do Superbill", patient: "Paciente", provider: "Médico", clinic: "Clínica", serviceDate: "Data do serviço", dx: "Códigos de diagnóstico (ICD-10)", cpt: "Códigos de procedimento (CPT)", code: "Código", desc: "Descrição", units: "Qtd.", fee: "Valor", total: "Total", status: "Status", currency: "Moeda", notes: "Notas", verify: "Código de verificação", scan: "Escanear para verificar", confidential: "Superbill confidencial", generatedBy: "Gerado por Docito (docito.app)", reimbursementNote: "Envie este superbill à sua seguradora para reembolso.", page: "Página", of: "de", na: "—" },
  de: { title: "Superbill", number: "Superbill-Nr.", patient: "Patient", provider: "Arzt", clinic: "Klinik", serviceDate: "Leistungsdatum", dx: "Diagnose-Codes (ICD-10)", cpt: "Behandlungscodes (CPT)", code: "Code", desc: "Beschreibung", units: "Menge", fee: "Betrag", total: "Summe", status: "Status", currency: "Währung", notes: "Anmerkungen", verify: "Verifizierungscode", scan: "Scannen zur Verifizierung", confidential: "Vertraulicher Superbill", generatedBy: "Erstellt von Docito (docito.app)", reimbursementNote: "Reichen Sie diesen Superbill bei Ihrer Versicherung zur Erstattung ein.", page: "Seite", of: "von", na: "—" },
};

const tr = (l: Locale, k: string) => T[l]?.[k] ?? T.en[k] ?? k;
const normalize = (v?: string): Locale => {
  const r = (sanitizeString(v || "", 12) || "").toLowerCase();
  for (const c of ["ru","uz","tr","ar","ja","ko","zh","es","pt","de"] as Locale[]) if (r.startsWith(c)) return c;
  return "en";
};
const safe = (v: unknown, max = 500) => sanitizeString(typeof v === "string" ? v : v == null ? "" : String(v), max) || "";
const b64 = (s: string): Uint8Array => { const c = (s||"").replace(/\s+/g,""); if (!c) return new Uint8Array(0); try { const bin = atob(c); const out = new Uint8Array(bin.length); for (let i=0;i<bin.length;i++) out[i]=bin.charCodeAt(i); return out; } catch { return new Uint8Array(0); } };
const fmtMoney = (cents: number, currency: string) => { const a=(Number(cents)||0)/100; const cc=(currency||"USD").toUpperCase(); try { return new Intl.NumberFormat("en-US",{style:"currency",currency:cc}).format(a); } catch { return `${a.toFixed(2)} ${cc}`; } };
const sanitizePdf = (s: string) => String(s||"").replace(/\u2013/g,"-").replace(/\u2014/g,"--").replace(/\u2018|\u2019/g,"'").replace(/\u201C|\u201D/g,'"').replace(/\u2026/g,"...").replace(/\u00A0/g," ");

async function loadFont(pdf: PDFDocument, locale: Locale): Promise<PDFFont> {
  pdf.registerFontkit(fontkit);
  try {
    let bytes: Uint8Array;
    if (locale === "ar") bytes = new Uint8Array(await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf")).arrayBuffer());
    else if (locale === "ja") bytes = new Uint8Array(await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf")).arrayBuffer());
    else if (locale === "ko") bytes = new Uint8Array(await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf")).arrayBuffer());
    else if (locale === "zh") bytes = new Uint8Array(await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf")).arrayBuffer());
    else bytes = b64(DOCITO_FONT_TTF_BASE64);
    if (bytes.length > 0) return await pdf.embedFont(bytes, { subset: true });
  } catch { /* fallthrough */ }
  return await pdf.embedFont(StandardFonts.Helvetica);
}

function wrap(text: string, font: PDFFont, size: number, maxW: number, locale: Locale): string[] {
  if (!text) return [];
  const cjk = CJK.has(locale);
  const meas = (s: string) => { try { return font.widthOfTextAtSize(s, size); } catch { return s.length * size * 0.6; } };
  const out: string[] = [];
  for (const para of text.replace(/\r\n/g, "\n").split("\n")) {
    if (!para.trim()) { out.push(""); continue; }
    const tokens = cjk ? Array.from(para) : para.trim().split(/\s+/).filter(Boolean);
    let cur = "";
    for (const tok of tokens) {
      const next = cur + (cur && !cjk ? " " : "") + tok;
      if (!cur || meas(next) <= maxW) cur = next;
      else { if (cur) out.push(cur); cur = tok; }
    }
    if (cur) out.push(cur);
  }
  return out;
}

serve(async (req) => {
  const { response, context, validatedBody } = await secureHandler(req, "superbill-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "expensive",
    validationSchema: schema,
  });
  if (response) return response;
  if (!context || !validatedBody) return errorResponse("Internal server error", 500);

  try {
    const { userId, roles, serviceClient: svc } = context;
    const body = validatedBody as { superbill_id: string; locale?: string };
    let locale: Locale = normalize(body.locale);
    if (!body.locale) {
      try {
        const { data: prof } = await svc.from("profiles").select("language").eq("user_id", userId).maybeSingle();
        locale = normalize((prof as any)?.language) || "en";
      } catch { /* ignore */ }
    }

    const { data: sb, error: sbErr } = await svc.from("superbills").select("*").eq("id", body.superbill_id).maybeSingle();
    if (sbErr) return errorResponse("Failed to fetch superbill", 500);
    if (!sb) return errorResponse("Superbill not found", 404);
    const r: any = sb;

    // Authorization: super admin / patient / doctor owner / clinic admin or billing staff
    const isSuper = (roles || []).includes("super_admin");
    let allowed = isSuper;
    if (!allowed && r.patient_id === userId) allowed = true;
    if (!allowed && r.doctor_id) {
      const { data: doc } = await svc.from("doctors").select("id").eq("id", r.doctor_id).eq("user_id", userId).maybeSingle();
      if (doc) allowed = true;
    }
    if (!allowed && r.practice_id) {
      const { data: p } = await svc.from("practices").select("id").eq("id", r.practice_id).eq("admin_id", userId).maybeSingle();
      if (p) allowed = true;
      if (!allowed) {
        const { data: st } = await svc.from("clinic_staff").select("id").eq("practice_id", r.practice_id).eq("user_id", userId).eq("status", "active").maybeSingle();
        if (st) allowed = true;
      }
    }
    if (!allowed) return errorResponse("Forbidden", 403);

    // Resolve names
    let patientName = "—", doctorName = "—", clinicName = "—";
    try {
      if (r.patient_id) {
        const { data: prof } = await svc.from("profiles").select("full_name").eq("user_id", r.patient_id).maybeSingle();
        patientName = safe((prof as any)?.full_name, 200) || "—";
      }
      if (r.doctor_id) {
        const { data: d } = await svc.from("doctors").select("user_id, full_name").eq("id", r.doctor_id).maybeSingle();
        const dn = (d as any)?.full_name;
        if (dn) doctorName = safe(dn, 200);
        else if ((d as any)?.user_id) {
          const { data: prof } = await svc.from("profiles").select("full_name").eq("user_id", (d as any).user_id).maybeSingle();
          doctorName = safe((prof as any)?.full_name, 200) || "—";
        }
      }
      if (r.practice_id) {
        const { data: pr } = await svc.from("practices").select("name").eq("id", r.practice_id).maybeSingle();
        clinicName = safe((pr as any)?.name, 200) || "—";
      }
    } catch { /* ignore */ }

    const siteBase = (Deno.env.get("PUBLIC_SITE_URL") || "https://docito.app").replace(/\/$/, "");
    const verifyUrl = `${siteBase}/verify?type=superbill&code=${encodeURIComponent(r.id)}`;
    const verificationCode = safe(r.metadata?.verification_code || r.id.slice(0, 12), 80);

    const W = 595.28, H = 841.89, margin = 44, HEADER_H = 38, FOOTER_H = 100;
    const pdf = await PDFDocument.create();
    const font = await loadFont(pdf, locale);
    const rtl = RTL.has(locale);

    const blue = rgb(0.145, 0.388, 0.922);
    const blueLight = rgb(0.93, 0.96, 1.0);
    const textDark = rgb(0.05, 0.05, 0.05);
    const textMuted = rgb(0.35, 0.35, 0.35);
    const borderLight = rgb(0.88, 0.88, 0.88);

    const fullLogoBytes = b64(DOCITO_LOGO_FULL_PNG_BASE64);
    let fullLogo: any = null; let fullLogoW = 0; const fullLogoH = 24;
    if (fullLogoBytes.length) { try { fullLogo = await pdf.embedPng(fullLogoBytes); fullLogoW = (fullLogo.width / fullLogo.height) * fullLogoH; } catch { /* ignore */ } }

    const iconBytes = b64(DOCITO_LOGO_PNG_BASE64);
    let iconLogo: any = null; const iconLogoW = 16; let iconLogoH = 16;
    if (iconBytes.length) { try { iconLogo = await pdf.embedPng(iconBytes); iconLogoH = (iconLogo.height / iconLogo.width) * iconLogoW; } catch { /* ignore */ } }

    let qrImg: any = null;
    const QR_SIZE = 80;
    try {
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 200, errorCorrectionLevel: "M" });
      const qrB64 = qrDataUrl.split(",")[1] || "";
      if (qrB64) qrImg = await pdf.embedPng(b64(qrB64));
    } catch { /* ignore */ }

    let page = pdf.addPage([W, H]);
    let y = H - margin;

    const drawHeader = () => {
      page.drawRectangle({ x: 0, y: H - HEADER_H, width: W, height: HEADER_H, color: blue });
      if (fullLogo && fullLogoW > 0) page.drawImage(fullLogo, { x: margin, y: H - HEADER_H + (HEADER_H - fullLogoH) / 2, width: fullLogoW, height: fullLogoH });
      const lbl = sanitizePdf(tr(locale, "title"));
      try { const lw = font.widthOfTextAtSize(lbl, 11); page.drawText(lbl, { x: W - margin - lw, y: H - HEADER_H + (HEADER_H + 11) / 2 - 4, size: 11, font, color: rgb(1, 1, 1) }); } catch { /* ignore */ }
    };
    const drawFooter = (pg: typeof page, n: number, c: number) => {
      const fY = margin;
      pg.drawLine({ start: { x: margin, y: fY + FOOTER_H }, end: { x: W - margin, y: fY + FOOTER_H }, thickness: 0.8, color: borderLight });
      const qrX = W - margin - QR_SIZE;
      const qrY = fY + (FOOTER_H - QR_SIZE) / 2;
      if (qrImg) pg.drawImage(qrImg, { x: qrX, y: qrY, width: QR_SIZE, height: QR_SIZE });
      let leftX = margin;
      if (iconLogo) { pg.drawImage(iconLogo, { x: leftX, y: fY + FOOTER_H - iconLogoH - 4, width: iconLogoW, height: iconLogoH }); leftX += iconLogoW + 5; }
      try { pg.drawText(sanitizePdf(tr(locale, "confidential")), { x: leftX, y: fY + FOOTER_H - 12, size: 8, font, color: textDark }); } catch { /* ignore */ }
      try { pg.drawText(sanitizePdf(tr(locale, "generatedBy")), { x: leftX, y: fY + FOOTER_H - 22, size: 7.5, font, color: textMuted }); } catch { /* ignore */ }
      try { pg.drawText(sanitizePdf(`${tr(locale, "verify")}: ${verificationCode}`), { x: margin, y: fY + FOOTER_H - 42, size: 8.5, font, color: textDark }); } catch { /* ignore */ }
      try {
        const vu = sanitizePdf(`${tr(locale, "scan")}: ${verifyUrl}`);
        const lines = wrap(vu, font, 7.5, W - margin * 2 - QR_SIZE - 16, locale);
        let yy = fY + FOOTER_H - 54;
        for (const line of lines) { try { pg.drawText(line, { x: margin, y: yy, size: 7.5, font, color: textMuted }); } catch { /* ignore */ } yy -= 9; }
      } catch { /* ignore */ }
      const pl = `${tr(locale, "page")} ${n} ${tr(locale, "of")} ${c}`;
      try { const lw = font.widthOfTextAtSize(pl, 8); pg.drawText(pl, { x: W - margin - lw, y: fY + 6, size: 8, font, color: textMuted }); } catch { /* ignore */ }
    };

    const bodyBottom = margin + FOOTER_H + 8;
    const newPage = () => { page = pdf.addPage([W, H]); y = H - margin; drawHeader(); y = H - HEADER_H - 18; };
    const ensure = (n: number) => { if (y - n < bodyBottom) newPage(); };
    const section = (key: string) => {
      ensure(28); y -= 8;
      const lbl = sanitizePdf(tr(locale, key));
      try { const lw = font.widthOfTextAtSize(lbl, 11); page.drawText(lbl, { x: rtl ? W - margin - lw : margin, y, size: 11, font, color: blue }); } catch { /* ignore */ }
      page.drawLine({ start: { x: margin, y: y - 3 }, end: { x: W - margin, y: y - 3 }, thickness: 0.8, color: borderLight });
      y -= 21;
    };
    const LW = 148, VX = margin + LW, VMW = W - margin - VX;
    const kv = (key: string, value: string | null | undefined) => {
      ensure(14);
      const lbl = sanitizePdf(tr(locale, key));
      const val = (value || "").trim() || tr(locale, "na");
      const lines = wrap(sanitizePdf(val), font, 9.5, VMW, locale);
      try { page.drawText(lbl, { x: rtl ? W - margin - font.widthOfTextAtSize(lbl, 9.5) : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
      let yy = y;
      for (const line of lines) {
        try { page.drawText(line, { x: rtl ? W - margin - LW - font.widthOfTextAtSize(line, 9.5) : VX, y: yy, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        yy -= 13;
      }
      y = yy;
    };

    // Page 1
    drawHeader();
    y = H - HEADER_H - 20;

    const titleTxt = sanitizePdf(tr(locale, "title"));
    try { const tw = font.widthOfTextAtSize(titleTxt, 20); page.drawText(titleTxt, { x: rtl ? W - margin - tw : margin, y, size: 20, font, color: blue }); } catch { /* ignore */ }
    y -= 24;
    const num = sanitizePdf(`${tr(locale, "number")}: ${safe(r.superbill_number || r.id, 60)}`);
    try { const sw = font.widthOfTextAtSize(num, 9.5); page.drawText(num, { x: rtl ? W - margin - sw : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
    y -= 8;
    page.drawRectangle({ x: margin, y, width: W - margin * 2, height: 2, color: blue });
    y -= 16;

    // Summary box
    ensure(82);
    const boxH = 74;
    const boxY = y - boxH;
    page.drawRectangle({ x: margin, y: boxY, width: W - margin * 2, height: boxH, color: blueLight, borderColor: borderLight, borderWidth: 0.8 });
    let mY = y - 14; const mX = margin + 12;
    const writeS = (lk: string, v: string) => {
      const lbl = sanitizePdf(`${tr(locale, lk)}: `);
      try { page.drawText(lbl, { x: mX, y: mY, size: 8.5, font, color: textMuted }); } catch { /* ignore */ }
      try { const lw = font.widthOfTextAtSize(lbl, 8.5); page.drawText(sanitizePdf(v || "—"), { x: mX + lw, y: mY, size: 9, font, color: textDark }); } catch { /* ignore */ }
      mY -= 13;
    };
    writeS("patient", patientName);
    writeS("provider", doctorName);
    writeS("clinic", clinicName);
    writeS("serviceDate", String(r.service_date || ""));
    writeS("status", String(r.status || ""));
    y = boxY - 16;

    // Diagnosis codes
    const dxArr: any[] = Array.isArray(r.diagnosis_codes) ? r.diagnosis_codes : [];
    if (dxArr.length > 0) {
      section("dx");
      for (const dx of dxArr) {
        ensure(14);
        const c = safe((typeof dx === "string" ? dx : dx.code) || "", 20);
        const d = safe((typeof dx === "string" ? "" : dx.description) || "", 200);
        try { page.drawText(c, { x: margin, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        if (d) try { page.drawText(d.slice(0, 90), { x: margin + 80, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
        y -= 13;
      }
    }

    // Line items / CPT
    const items: any[] = Array.isArray(r.line_items) ? r.line_items : [];
    section("cpt");
    // table header
    ensure(18);
    try { page.drawText(sanitizePdf(tr(locale, "code")), { x: margin, y, size: 9, font, color: textMuted }); } catch { /* ignore */ }
    try { page.drawText(sanitizePdf(tr(locale, "desc")), { x: margin + 80, y, size: 9, font, color: textMuted }); } catch { /* ignore */ }
    try { page.drawText(sanitizePdf(tr(locale, "units")), { x: W - margin - 160, y, size: 9, font, color: textMuted }); } catch { /* ignore */ }
    try {
      const lblFee = sanitizePdf(tr(locale, "fee"));
      const lw = font.widthOfTextAtSize(lblFee, 9);
      page.drawText(lblFee, { x: W - margin - lw, y, size: 9, font, color: textMuted });
    } catch { /* ignore */ }
    y -= 12;
    page.drawLine({ start: { x: margin, y }, end: { x: W - margin, y }, thickness: 0.4, color: borderLight });
    y -= 10;

    let total = 0;
    for (const it of items) {
      ensure(16);
      const code = safe(it.code || "", 16);
      const desc = sanitizePdf(safe(it.description || it.name || "", 220));
      const units = it.units != null ? String(it.units) : (it.quantity != null ? String(it.quantity) : "1");
      const feeCents = Number(it.fee_cents ?? (it.amount != null ? it.amount : (it.unit_amount != null ? Number(it.unit_amount) * Number(units || 1) : 0))) || 0;
      total += feeCents;
      const feeStr = fmtMoney(feeCents, r.currency || "usd");
      try { page.drawText(code, { x: margin, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
      try { page.drawText(desc.slice(0, 70), { x: margin + 80, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
      try { page.drawText(units, { x: W - margin - 160, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
      try { const lw = font.widthOfTextAtSize(feeStr, 9.5); page.drawText(feeStr, { x: W - margin - lw, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
      y -= 14;
    }

    // Total
    y -= 4;
    page.drawLine({ start: { x: margin, y }, end: { x: W - margin, y }, thickness: 0.6, color: borderLight });
    y -= 14;
    const totalCents = r.total_amount_cents || total;
    const tlbl = sanitizePdf(tr(locale, "total"));
    const tstr = fmtMoney(totalCents, r.currency || "usd");
    try { page.drawText(tlbl, { x: margin, y, size: 11, font, color: blue }); } catch { /* ignore */ }
    try { const lw = font.widthOfTextAtSize(tstr, 11); page.drawText(tstr, { x: W - margin - lw, y, size: 11, font, color: blue }); } catch { /* ignore */ }
    y -= 18;

    if (r.notes) { section("notes"); kv("notes", safe(r.notes, 800)); }

    // Reimbursement note
    ensure(20); y -= 6;
    try { page.drawText(sanitizePdf(tr(locale, "reimbursementNote")), { x: margin, y, size: 9, font, color: textMuted }); } catch { /* ignore */ }

    const pageCount = pdf.getPageCount();
    for (let p = 0; p < pageCount; p++) drawFooter(pdf.getPage(p), p + 1, pageCount);

    const pdfBytes = await pdf.save();
    // Persist verification code if missing
    try {
      if (!r.metadata?.verification_code) {
        await svc.from("superbills").update({ metadata: { ...(r.metadata || {}), verification_code: verificationCode } }).eq("id", r.id);
      }
    } catch { /* ignore */ }

    return new Response(pdfBytes as unknown as BodyInit, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="superbill-${safe(r.id, 40).replace(/[^a-zA-Z0-9_-]/g, "_")}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    console.error("superbill-generate-pdf error:", e);
    return errorResponse("Failed to generate PDF", 500);
  }
});
