export { VisitPage } from "./VisitPage";
export { VisitHeader } from "./VisitHeader";
export { VisitSidebar } from "./VisitSidebar";
export { EnhancedDentalChart as DentalChart } from "@/components/dental";
export { DiagnosisTab } from "./tabs/DiagnosisTab";
export { TreatmentTab } from "./tabs/TreatmentTab";
export { PrescriptionTab } from "./tabs/PrescriptionTab";
export { FilesTab } from "./tabs/FilesTab";
export { NotesTab } from "./tabs/NotesTab";
export * from "./types";
