// supabase/functions/patient-profile-generate-pdf/index.ts
/**
 * Patient Profile PDF generator — Docito
 *
 * Generates a branded, verifiable patient summary PDF.
 * Issues a patient_pdf_token (stored in DB), encodes it in a QR code
 * on every page so recipients can verify the document's authenticity
 * by visiting: https://docito.app/verify?type=patient&token=PT-XXXX
 *
 * Auth: doctor who requested it (must have relationship with patient) | super_admin
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, PDFFont, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";

import {
  secureHandler,
  errorResponse,
  corsHeaders,
} from "../_shared/security-middleware.ts";
import { sanitizeString } from "../_shared/input-validator.ts";
import {
  DOCITO_LOGO_PNG_BASE64,
  DOCITO_LOGO_FULL_PNG_BASE64,
  DOCITO_FONT_TTF_BASE64,
} from "./assets.ts";

// ─── Types ────────────────────────────────────────────────────────────────────

type Locale = "en" | "ru" | "uz" | "tr" | "ar" | "ja" | "ko" | "zh" | "es" | "pt" | "de";

const schema = {
  patient_id: { type: "uuid" as const, required: true },
  locale: { type: "string" as const, required: false, maxLength: 12, sanitize: true, trim: true },
};

const RTL_LOCALES = new Set<Locale>(["ar"]);
const CJK_LOCALES = new Set<Locale>(["ja", "ko", "zh"]);

// ─── i18n ─────────────────────────────────────────────────────────────────────

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    title:"Patient Profile",generatedBy:"Generated by Docito (docito.app)",
    verificationCode:"Verification Code",verifyAt:"Scan to verify authenticity",
    personalInfo:"Personal Information",
    name:"Full Name",dob:"Date of Birth",age:"Age",gender:"Gender",
    phone:"Phone",email:"Email",address:"Address",
    medicalInfo:"Medical Information",
    bloodGroup:"Blood Group",allergies:"Allergies",
    medicalHistory:"Medical History",dentalHistory:"Dental History",
    currentMedications:"Current Medications",
    emergency:"Emergency Contact",
    emergencyName:"Contact Name",emergencyPhone:"Contact Phone",
    recentAppointments:"Recent Appointments",
    date:"Date",status:"Status",notes:"Notes",
    activePrescriptions:"Active Prescriptions",
    medication:"Medication",dosage:"Dosage",frequency:"Frequency",
    startDate:"Start Date",endDate:"End Date",instructions:"Instructions",
    na:"—",yrs:"yrs",
    confidential:"Confidential Patient Record — Docito",
  },
  ru: {
    title:"Профиль пациента",generatedBy:"Сформировано в Docito (docito.app)",
    verificationCode:"Код проверки",verifyAt:"Сканируйте для проверки",
    personalInfo:"Личная информация",
    name:"ФИО",dob:"Дата рождения",age:"Возраст",gender:"Пол",
    phone:"Телефон",email:"Email",address:"Адрес",
    medicalInfo:"Медицинская информация",
    bloodGroup:"Группа крови",allergies:"Аллергии",
    medicalHistory:"История болезни",dentalHistory:"Стоматологическая история",
    currentMedications:"Текущие препараты",
    emergency:"Экстренный контакт",
    emergencyName:"Имя контакта",emergencyPhone:"Телефон контакта",
    recentAppointments:"Последние визиты",
    date:"Дата",status:"Статус",notes:"Заметки",
    activePrescriptions:"Активные рецепты",
    medication:"Препарат",dosage:"Дозировка",frequency:"Частота",
    startDate:"Начало",endDate:"Конец",instructions:"Инструкции",
    na:"—",yrs:"лет",
    confidential:"Конфиденциальная запись пациента — Docito",
  },
  uz: {
    title:"Bemor profili",generatedBy:"Docito orqali yaratildi (docito.app)",
    verificationCode:"Tekshiruv kodi",verifyAt:"Haqiqiyligini tekshirish uchun skaner qiling",
    personalInfo:"Shaxsiy ma'lumotlar",
    name:"To'liq ism",dob:"Tug'ilgan sana",age:"Yoshi",gender:"Jinsi",
    phone:"Telefon",email:"Email",address:"Manzil",
    medicalInfo:"Tibbiy ma'lumotlar",
    bloodGroup:"Qon guruhi",allergies:"Allergiyalar",
    medicalHistory:"Kasallik tarixi",dentalHistory:"Stomatologik tarixi",
    currentMedications:"Joriy dorilar",
    emergency:"Favqulodda aloqa",
    emergencyName:"Aloqa ismi",emergencyPhone:"Aloqa telefoni",
    recentAppointments:"Oxirgi tashriflar",
    date:"Sana",status:"Holat",notes:"Izohlar",
    activePrescriptions:"Faol retseptlar",
    medication:"Dori",dosage:"Dozasi",frequency:"Chastotasi",
    startDate:"Boshlanish",endDate:"Tugash",instructions:"Ko'rsatmalar",
    na:"—",yrs:"yosh",
    confidential:"Maxfiy bemor yozuvi — Docito",
  },
  tr: {
    title:"Hasta Profili",generatedBy:"Docito tarafindan olusturuldu (docito.app)",
    verificationCode:"Dogrulama Kodu",verifyAt:"Dogrulamak icin tarayin",
    personalInfo:"Kisisel Bilgiler",
    name:"Ad Soyad",dob:"Dogum Tarihi",age:"Yas",gender:"Cinsiyet",
    phone:"Telefon",email:"E-posta",address:"Adres",
    medicalInfo:"Saglik Bilgileri",
    bloodGroup:"Kan Grubu",allergies:"Alerjiler",
    medicalHistory:"Tip Gecmisi",dentalHistory:"Dis Gecmisi",
    currentMedications:"Mevcut Ilaclar",
    emergency:"Acil Kisi",
    emergencyName:"Kisi Adi",emergencyPhone:"Kisi Telefonu",
    recentAppointments:"Son Randevular",
    date:"Tarih",status:"Durum",notes:"Notlar",
    activePrescriptions:"Aktif Receteler",
    medication:"Ilac",dosage:"Doz",frequency:"Siklik",
    startDate:"Baslangic",endDate:"Bitis",instructions:"Talimatlar",
    na:"—",yrs:"yas",
    confidential:"Gizli Hasta Kaydi — Docito",
  },
  ar: {
    title:"ملف المريض",generatedBy:"تم الانشاء بواسطة Docito (docito.app)",
    verificationCode:"رمز التحقق",verifyAt:"امسح للتحقق من الاصالة",
    personalInfo:"المعلومات الشخصية",
    name:"الاسم الكامل",dob:"تاريخ الميلاد",age:"العمر",gender:"الجنس",
    phone:"الهاتف",email:"البريد الالكتروني",address:"العنوان",
    medicalInfo:"المعلومات الطبية",
    bloodGroup:"فصيلة الدم",allergies:"الحساسية",
    medicalHistory:"التاريخ المرضي",dentalHistory:"التاريخ الاسناني",
    currentMedications:"الادوية الحالية",
    emergency:"جهة الطوارئ",
    emergencyName:"اسم جهة الاتصال",emergencyPhone:"هاتف جهة الاتصال",
    recentAppointments:"المواعيد الاخيرة",
    date:"التاريخ",status:"الحالة",notes:"ملاحظات",
    activePrescriptions:"الوصفات الفعالة",
    medication:"الدواء",dosage:"الجرعة",frequency:"التكرار",
    startDate:"البداية",endDate:"النهاية",instructions:"التعليمات",
    na:"—",yrs:"سنة",
    confidential:"سجل مريض سري — Docito",
  },
  ja: {
    title:"患者プロフィール",generatedBy:"Docito で生成 (docito.app)",
    verificationCode:"検証コード",verifyAt:"スキャンして真正性を確認",
    personalInfo:"個人情報",
    name:"氏名",dob:"生年月日",age:"年齢",gender:"性別",
    phone:"電話",email:"メール",address:"住所",
    medicalInfo:"医療情報",
    bloodGroup:"血液型",allergies:"アレルギー",
    medicalHistory:"病歴",dentalHistory:"歯科病歴",
    currentMedications:"現在の薬",
    emergency:"緊急連絡先",
    emergencyName:"連絡先名",emergencyPhone:"連絡先電話",
    recentAppointments:"最近の受診",
    date:"日付",status:"状態",notes:"メモ",
    activePrescriptions:"有効な処方",
    medication:"薬",dosage:"用量",frequency:"頻度",
    startDate:"開始",endDate:"終了",instructions:"指示",
    na:"—",yrs:"歳",
    confidential:"機密患者記録 — Docito",
  },
  ko: {
    title:"환자 프로필",generatedBy:"Docito에서 생성 (docito.app)",
    verificationCode:"검증 코드",verifyAt:"스캔하여 진위 확인",
    personalInfo:"개인 정보",
    name:"성명",dob:"생년월일",age:"나이",gender:"성별",
    phone:"전화",email:"이메일",address:"주소",
    medicalInfo:"의료 정보",
    bloodGroup:"혈액형",allergies:"알레르기",
    medicalHistory:"병력",dentalHistory:"치과 병력",
    currentMedications:"현재 약물",
    emergency:"비상 연락처",
    emergencyName:"연락처 이름",emergencyPhone:"연락처 전화",
    recentAppointments:"최근 진료",
    date:"날짜",status:"상태",notes:"메모",
    activePrescriptions:"활성 처방",
    medication:"약품",dosage:"용량",frequency:"빈도",
    startDate:"시작",endDate:"종료",instructions:"지시사항",
    na:"—",yrs:"세",
    confidential:"기밀 환자 기록 — Docito",
  },
  zh: {
    title:"患者档案",generatedBy:"由 Docito 生成 (docito.app)",
    verificationCode:"验证代码",verifyAt:"扫描验证真实性",
    personalInfo:"个人信息",
    name:"姓名",dob:"出生日期",age:"年龄",gender:"性别",
    phone:"电话",email:"邮箱",address:"地址",
    medicalInfo:"医疗信息",
    bloodGroup:"血型",allergies:"过敏",
    medicalHistory:"病史",dentalHistory:"牙科病史",
    currentMedications:"当前用药",
    emergency:"紧急联系人",
    emergencyName:"联系人姓名",emergencyPhone:"联系人电话",
    recentAppointments:"近期就诊",
    date:"日期",status:"状态",notes:"备注",
    activePrescriptions:"有效处方",
    medication:"药品",dosage:"剂量",frequency:"频率",
    startDate:"开始",endDate:"结束",instructions:"用药说明",
    na:"—",yrs:"岁",
    confidential:"机密患者档案 — Docito",
  },
  es: {
    title:"Perfil del Paciente",generatedBy:"Generado por Docito (docito.app)",
    verificationCode:"Codigo de verificacion",verifyAt:"Escanear para verificar",
    personalInfo:"Informacion Personal",
    name:"Nombre completo",dob:"Fecha de nacimiento",age:"Edad",gender:"Genero",
    phone:"Telefono",email:"Email",address:"Direccion",
    medicalInfo:"Informacion Medica",
    bloodGroup:"Grupo sanguineo",allergies:"Alergias",
    medicalHistory:"Historia medica",dentalHistory:"Historia dental",
    currentMedications:"Medicamentos actuales",
    emergency:"Contacto de emergencia",
    emergencyName:"Nombre del contacto",emergencyPhone:"Telefono del contacto",
    recentAppointments:"Citas recientes",
    date:"Fecha",status:"Estado",notes:"Notas",
    activePrescriptions:"Recetas activas",
    medication:"Medicamento",dosage:"Dosis",frequency:"Frecuencia",
    startDate:"Inicio",endDate:"Fin",instructions:"Instrucciones",
    na:"—",yrs:"anos",
    confidential:"Registro confidencial del paciente — Docito",
  },
  pt: {
    title:"Perfil do Paciente",generatedBy:"Gerado por Docito (docito.app)",
    verificationCode:"Codigo de verificacao",verifyAt:"Escanear para verificar",
    personalInfo:"Informacoes Pessoais",
    name:"Nome completo",dob:"Data de nascimento",age:"Idade",gender:"Genero",
    phone:"Telefone",email:"Email",address:"Endereco",
    medicalInfo:"Informacoes Medicas",
    bloodGroup:"Tipo sanguineo",allergies:"Alergias",
    medicalHistory:"Historico medico",dentalHistory:"Historico dental",
    currentMedications:"Medicamentos atuais",
    emergency:"Contato de emergencia",
    emergencyName:"Nome do contato",emergencyPhone:"Telefone do contato",
    recentAppointments:"Consultas recentes",
    date:"Data",status:"Status",notes:"Notas",
    activePrescriptions:"Receitas ativas",
    medication:"Medicamento",dosage:"Dose",frequency:"Frequencia",
    startDate:"Inicio",endDate:"Fim",instructions:"Instrucoes",
    na:"—",yrs:"anos",
    confidential:"Registro confidencial do paciente — Docito",
  },
  de: {
    title:"Patientenprofil",generatedBy:"Erstellt von Docito (docito.app)",
    verificationCode:"Verifizierungscode",verifyAt:"Scannen zur Echtheitsprufung",
    personalInfo:"Personliche Informationen",
    name:"Vollstandiger Name",dob:"Geburtsdatum",age:"Alter",gender:"Geschlecht",
    phone:"Telefon",email:"E-Mail",address:"Adresse",
    medicalInfo:"Medizinische Informationen",
    bloodGroup:"Blutgruppe",allergies:"Allergien",
    medicalHistory:"Krankengeschichte",dentalHistory:"Zahngeschichte",
    currentMedications:"Aktuelle Medikamente",
    emergency:"Notfallkontakt",
    emergencyName:"Kontaktname",emergencyPhone:"Kontakttelefon",
    recentAppointments:"Aktuelle Termine",
    date:"Datum",status:"Status",notes:"Notizen",
    activePrescriptions:"Aktive Rezepte",
    medication:"Medikament",dosage:"Dosierung",frequency:"Haufigkeit",
    startDate:"Beginn",endDate:"Ende",instructions:"Anweisungen",
    na:"—",yrs:"J",
    confidential:"Vertrauliche Patientenakte — Docito",
  },
};

function i(locale: Locale, key: string): string {
  return I18N[locale]?.[key] ?? I18N.en[key] ?? key;
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function normalizeLocale(v?: string): Locale {
  const r = (sanitizeString(v || "", 12) || "").toLowerCase();
  if (r.startsWith("ru")) return "ru"; if (r.startsWith("uz")) return "uz";
  if (r.startsWith("tr")) return "tr"; if (r.startsWith("ar")) return "ar";
  if (r.startsWith("ja")) return "ja"; if (r.startsWith("ko")) return "ko";
  if (r.startsWith("zh")) return "zh"; if (r.startsWith("es")) return "es";
  if (r.startsWith("pt")) return "pt"; if (r.startsWith("de")) return "de";
  return "en";
}

function safe(v: unknown, max = 500): string {
  const s = typeof v === "string" ? v : v == null ? "" : String(v);
  return sanitizeString(s, max) || "";
}

function b64(s: string): Uint8Array {
  const clean = (s || "").replace(/\s+/g, "");
  if (!clean) return new Uint8Array(0);
  try { const bin = atob(clean); const out = new Uint8Array(bin.length); for (let j = 0; j < bin.length; j++) out[j] = bin.charCodeAt(j); return out; }
  catch { return new Uint8Array(0); }
}

function sanitizePdf(s: string): string {
  return String(s||"").replace(/\u2013/g,"-").replace(/\u2014/g,"--").replace(/\u2018/g,"'").replace(/\u2019/g,"'").replace(/\u201C/g,'"').replace(/\u201D/g,'"').replace(/\u2026/g,"...").replace(/\u00A0/g," ");
}

function fmtDate(v: unknown, locale: Locale): string {
  const s = typeof v === "string" ? v : "";
  if (!s) return "";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return safe(s, 32);
  const y = d.getUTCFullYear(), m = String(d.getUTCMonth()+1).padStart(2,"0"), dd2 = String(d.getUTCDate()).padStart(2,"0");
  return (locale === "ru" || locale === "uz") ? `${dd2}.${m}.${y}` : `${y}-${m}-${dd2}`;
}

async function loadFont(pdf: PDFDocument, locale: Locale): Promise<PDFFont> {
  pdf.registerFontkit(fontkit);
  try {
    let bytes: Uint8Array;
    if (locale === "ar") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf")).arrayBuffer().then(a=>new Uint8Array(a));
    else if (locale === "ja") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf")).arrayBuffer().then(a=>new Uint8Array(a));
    else if (locale === "ko") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf")).arrayBuffer().then(a=>new Uint8Array(a));
    else if (locale === "zh") bytes = await (await fetch("https://raw.githubusercontent.com/googlefonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf")).arrayBuffer().then(a=>new Uint8Array(a));
    else bytes = b64(DOCITO_FONT_TTF_BASE64);
    if (bytes.length > 0) return await pdf.embedFont(bytes, { subset: true });
  } catch { /* fallback */ }
  return await pdf.embedFont(StandardFonts.Helvetica);
}

function wrap(text: string, font: PDFFont, size: number, maxW: number, locale: Locale): string[] {
  if (!text) return [];
  const cjk = CJK_LOCALES.has(locale);
  const meas = (s: string) => { try { return font.widthOfTextAtSize(s, size); } catch { return s.length * size * 0.6; } };
  const lines: string[] = [];
  for (const para of text.replace(/\r\n/g,"\n").split("\n")) {
    if (!para.trim()) { lines.push(""); continue; }
    const tokens = cjk ? Array.from(para) : para.trim().split(/\s+/).filter(Boolean);
    let cur = "";
    for (const tok of tokens) {
      const next = cur + (cur && !cjk ? " " : "") + tok;
      if (!cur || meas(next) <= maxW) cur = next;
      else { if (cur) lines.push(cur); cur = tok; }
    }
    if (cur) lines.push(cur);
  }
  return lines;
}

// ─── Main handler ─────────────────────────────────────────────────────────────

serve(async (req) => {
  const { response, context, validatedBody } = await secureHandler(req, "patient-profile-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "expensive",
    validationSchema: schema,
  });

  if (response) return response;
  if (!context || !validatedBody) return errorResponse("Internal server error", 500);

  try {
    const { userId, roles, serviceClient: svc } = context;
    const body = validatedBody as { patient_id: string; locale?: string };

    let locale: Locale = normalizeLocale(body.locale);
    if (!body.locale) {
      try {
        const { data: prof } = await svc.from("profiles").select("language").eq("user_id", userId).maybeSingle();
        locale = normalizeLocale((prof as any)?.language) || "en";
      } catch { /* ignore */ }
    }

    // ── Authorization: doctor must have a patient relationship OR super_admin ──
    const isSuperAdmin = (roles || []).includes("super_admin");
    let doctorId: string | null = null;
    let doctorName = "";

    if (!isSuperAdmin) {
      const { data: doc } = await svc.from("doctors").select("id,specialty").eq("user_id", userId).maybeSingle();
      if (!doc) return errorResponse("Only doctors can generate patient profile PDFs", 403);
      doctorId = (doc as any).id;

      // Verify the doctor has an appointment or relationship with this patient
      const { data: rel } = await svc
        .from("appointments")
        .select("id")
        .eq("doctor_id", doctorId)
        .eq("patient_id", body.patient_id)
        .limit(1)
        .maybeSingle();

      // Also check doctor_patients table if it exists
      const { data: dp } = await svc
        .from("doctor_patients")
        .select("id")
        .eq("doctor_id", doctorId)
        .eq("patient_id", body.patient_id)
        .maybeSingle()
        .catch(() => ({ data: null }));

      if (!rel && !dp) return errorResponse("No patient relationship found", 403);

      // Get doctor name
      const { data: docProfile } = await svc.from("profiles").select("full_name").eq("user_id", userId).maybeSingle();
      doctorName = safe((docProfile as any)?.full_name, 120);
    }

    // ── Fetch patient data ────────────────────────────────────────────────────
    const { data: patient, error: ptErr } = await svc
      .from("profiles")
      .select("user_id, full_name, email, phone, date_of_birth, gender, address, blood_group, allergies, medical_history, dental_history, current_medications, emergency_contact_name, emergency_contact_phone")
      .eq("user_id", body.patient_id)
      .maybeSingle();

    if (ptErr || !patient) return errorResponse("Patient not found", 404);
    const p: any = patient;

    // Fetch recent appointments
    const { data: appointments } = await svc
      .from("appointments")
      .select("appointment_date, start_time, status, notes")
      .eq("patient_id", body.patient_id)
      .order("appointment_date", { ascending: false })
      .limit(10);

    // Fetch active prescriptions
    const { data: prescriptions } = await svc
      .from("prescriptions")
      .select("prescription_number, status, prescribed_at, expires_at, notes, prescription_items(medication_name, dosage, frequency, instructions)")
      .eq("patient_id", body.patient_id)
      .in("status", ["active", "pending"])
      .order("prescribed_at", { ascending: false })
      .limit(10);

    // ── Issue a patient_pdf_token ─────────────────────────────────────────────
    let token = "";
    try {
      const { data: tokenRow } = await svc
        .from("patient_pdf_tokens")
        .insert({
          patient_id: body.patient_id,
          doctor_id: doctorId,
        })
        .select("token")
        .single();
      token = (tokenRow as any)?.token || "";
    } catch { /* non-critical, QR will still work with a UUID fallback */ }

    if (!token) token = `PT-${crypto.randomUUID().replace(/-/g,"").substring(0,12).toUpperCase()}`;

    const siteBase = (Deno.env.get("PUBLIC_SITE_URL") || "https://docito.app").replace(/\/$/, "");
    const verifyUrl = `${siteBase}/verify?type=patient&token=${encodeURIComponent(token)}&pid=${encodeURIComponent(body.patient_id)}`;

    // ─── PDF constants ────────────────────────────────────────────────────────
    const W = 595.28, H = 841.89;
    const margin = 44;
    const HEADER_H = 38;
    const FOOTER_H = 100;

    const pdf = await PDFDocument.create();
    const font = await loadFont(pdf, locale);
    const rtl = RTL_LOCALES.has(locale);

    const blue = rgb(0.145, 0.388, 0.922);
    const blueLight = rgb(0.93, 0.96, 1.0);
    const textDark = rgb(0.05, 0.05, 0.05);
    const textMuted = rgb(0.35, 0.35, 0.35);
    const borderLight = rgb(0.88, 0.88, 0.88);

    // Embed logos
    const fullLogoBytes = b64(DOCITO_LOGO_FULL_PNG_BASE64);
    let fullLogo: any = null; let fullLogoW = 0; const fullLogoH = 24;
    if (fullLogoBytes.length) { try { fullLogo = await pdf.embedPng(fullLogoBytes); fullLogoW = (fullLogo.width / fullLogo.height) * fullLogoH; } catch { /* ignore */ } }

    const iconBytes = b64(DOCITO_LOGO_PNG_BASE64);
    let iconLogo: any = null; const iconLogoW = 16; let iconLogoH = 16;
    if (iconBytes.length) { try { iconLogo = await pdf.embedPng(iconBytes); iconLogoH = (iconLogo.height / iconLogo.width) * iconLogoW; } catch { /* ignore */ } }

    // QR code
    let qrImg: any = null;
    const QR_SIZE = 80;
    try {
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 200, errorCorrectionLevel: "M" });
      const qrB64 = qrDataUrl.split(",")[1] || "";
      if (qrB64) qrImg = await pdf.embedPng(b64(qrB64));
    } catch { /* ignore */ }

    // ── Page state ─────────────────────────────────────────────────────────────
    let page = pdf.addPage([W, H]);
    let y = H - margin;

    const txt = (text: string, x: number, yy: number, size: number, color = textDark) => {
      const v = sanitizePdf(String(text || ""));
      try { const w = font.widthOfTextAtSize(v, size); page.drawText(v, { x: rtl ? x - w : x, y: yy, size, font, color }); } catch { /* ignore */ }
    };

    const drawHeader = () => {
      page.drawRectangle({ x: 0, y: H - HEADER_H, width: W, height: HEADER_H, color: blue });
      if (fullLogo && fullLogoW > 0) {
        page.drawImage(fullLogo, { x: margin, y: H - HEADER_H + (HEADER_H - fullLogoH) / 2, width: fullLogoW, height: fullLogoH });
      } else {
        txt("DOCITO", margin, H - HEADER_H + 14, 14, rgb(1, 1, 1));
      }
      const label = sanitizePdf(i(locale, "title"));
      try { const lw = font.widthOfTextAtSize(label, 10); page.drawText(label, { x: W - margin - lw, y: H - HEADER_H + (HEADER_H + 10) / 2 - 4, size: 10, font, color: rgb(1, 1, 1) }); } catch { /* ignore */ }
    };

    const bodyBottom = margin + FOOTER_H + 8;

    const drawVerifyFooter = (pg: typeof page, pageNum: number, pageCount: number) => {
      const fY = margin;
      pg.drawLine({ start: { x: margin, y: fY + FOOTER_H }, end: { x: W - margin, y: fY + FOOTER_H }, thickness: 0.8, color: borderLight });

      const qrX = W - margin - QR_SIZE;
      const qrY = fY + (FOOTER_H - QR_SIZE) / 2;
      if (qrImg) pg.drawImage(qrImg, { x: qrX, y: qrY, width: QR_SIZE, height: QR_SIZE });

      const textAreaW = W - margin * 2 - QR_SIZE - 16;
      let leftX = margin;
      if (iconLogo) { pg.drawImage(iconLogo, { x: leftX, y: fY + FOOTER_H - iconLogoH - 4, width: iconLogoW, height: iconLogoH }); leftX += iconLogoW + 5; }

      try { pg.drawText(sanitizePdf(i(locale, "confidential")), { x: leftX, y: fY + FOOTER_H - 12, size: 8, font, color: textDark }); } catch { /* ignore */ }
      try { pg.drawText(sanitizePdf(i(locale, "generatedBy")), { x: leftX, y: fY + FOOTER_H - 22, size: 7.5, font, color: textMuted }); } catch { /* ignore */ }
      if (doctorName) { try { pg.drawText(sanitizePdf(`Prepared by: Dr. ${doctorName}`), { x: leftX, y: fY + FOOTER_H - 32, size: 7.5, font, color: textMuted }); } catch { /* ignore */ } }

      const vcLine = sanitizePdf(`${i(locale, "verificationCode")}: ${token}`);
      const vuLine = sanitizePdf(`${i(locale, "verifyAt")}: ${verifyUrl}`);
      try { pg.drawText(vcLine, { x: margin, y: fY + FOOTER_H - 50, size: 8.5, font, color: textDark }); } catch { /* ignore */ }
      const vuLines = wrap(vuLine, font, 7.5, textAreaW, locale);
      let vyy = fY + FOOTER_H - 62;
      for (const line of vuLines) { try { pg.drawText(line, { x: margin, y: vyy, size: 7.5, font, color: textMuted }); } catch { /* ignore */ } vyy -= 9; }

      const pgLabel = `Page ${pageNum} of ${pageCount}`;
      try { const lw = font.widthOfTextAtSize(pgLabel, 8); pg.drawText(pgLabel, { x: W - margin - lw, y: fY + 6, size: 8, font, color: textMuted }); } catch { /* ignore */ }
    };

    const newPage = () => {
      page = pdf.addPage([W, H]);
      y = H - margin;
      drawHeader();
      y = H - HEADER_H - 18;
    };

    const ensure = (needed: number) => { if (y - needed < bodyBottom) newPage(); };

    const section = (key: string) => {
      ensure(28);
      y -= 8;
      const label = sanitizePdf(i(locale, key));
      try { const lw = font.widthOfTextAtSize(label, 11); page.drawText(label, { x: rtl ? W - margin - lw : margin, y, size: 11, font, color: blue }); } catch { /* ignore */ }
      page.drawLine({ start: { x: margin, y: y - 3 }, end: { x: W - margin, y: y - 3 }, thickness: 0.8, color: borderLight });
      y -= 11 + 10;
    };

    const LW = 148, VX = margin + LW, VMW = W - margin - VX;

    const kv = (key: string, value: string | null | undefined) => {
      ensure(14);
      const label = sanitizePdf(i(locale, key));
      const val = (value || "").trim() || i(locale, "na");
      const lines = wrap(sanitizePdf(val), font, 9.5, VMW, locale);
      try { page.drawText(label, { x: rtl ? W - margin - font.widthOfTextAtSize(label, 9.5) : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
      let yy = y;
      for (const line of lines) {
        try { page.drawText(line, { x: rtl ? W - margin - LW - font.widthOfTextAtSize(line, 9.5) : VX, y: yy, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        yy -= 13;
      }
      y = yy;
    };

    const multilineKV = (key: string, value: string | null | undefined) => {
      if (!value?.trim()) { kv(key, null); return; }
      ensure(20);
      const label = sanitizePdf(i(locale, key));
      try { page.drawText(label, { x: rtl ? W - margin - font.widthOfTextAtSize(label, 9.5) : margin, y, size: 9.5, font, color: textMuted }); } catch { /* ignore */ }
      y -= 13;
      const lines = wrap(sanitizePdf(value), font, 9.5, W - margin * 2 - 8, locale);
      for (const line of lines) {
        ensure(13);
        try { page.drawText(line, { x: rtl ? W - margin - 8 - font.widthOfTextAtSize(line, 9.5) : margin + 8, y, size: 9.5, font, color: textDark }); } catch { /* ignore */ }
        y -= 13;
      }
    };

    // ══════════════════════════════════════════════════════════════════════════
    //  PAGE 1
    // ══════════════════════════════════════════════════════════════════════════
    drawHeader();
    y = H - HEADER_H - 20;

    // Title block
    const titleTxt = sanitizePdf(i(locale, "title"));
    try { const tw = font.widthOfTextAtSize(titleTxt, 20); page.drawText(titleTxt, { x: rtl ? W - margin - tw : margin, y, size: 20, font, color: blue }); } catch { /* ignore */ }
    y -= 24;

    const patientSubtitle = sanitizePdf(safe(p.full_name, 120));
    try { const sw = font.widthOfTextAtSize(patientSubtitle, 11); page.drawText(patientSubtitle, { x: rtl ? W - margin - sw : margin, y, size: 11, font, color: textDark }); } catch { /* ignore */ }
    y -= 8;
    page.drawRectangle({ x: margin, y, width: W - margin * 2, height: 2, color: blue });
    y -= 16;

    // ── Verification box (page 1 inline) ──────────────────────────────────────
    ensure(84);
    const vBoxH = 76;
    const vBoxY = y - vBoxH;
    page.drawRectangle({ x: margin, y: vBoxY, width: W - margin * 2, height: vBoxH, color: blueLight, borderColor: borderLight, borderWidth: 0.8 });

    const qrX = rtl ? margin + 8 : W - margin - QR_SIZE - 8;
    if (qrImg) page.drawImage(qrImg, { x: qrX, y: vBoxY + (vBoxH - QR_SIZE + 8) / 2, width: QR_SIZE - 8, height: QR_SIZE - 8 });

    let mY = y - 14;
    const mX = rtl ? W - margin - 10 : margin + 10;
    const mW = W - margin * 2 - QR_SIZE - 20;

    const mLine = (lk: string, v: string) => {
      const lbl = sanitizePdf(`${i(locale, lk)}: `);
      try { page.drawText(lbl, { x: rtl ? mX - font.widthOfTextAtSize(lbl, 8) : mX, y: mY, size: 8, font, color: textMuted }); } catch { /* ignore */ }
      mY -= 10;
      const lines = wrap(sanitizePdf(v), font, 8.5, mW, locale);
      for (const line of lines) {
        try { page.drawText(line, { x: rtl ? mX - font.widthOfTextAtSize(line, 8.5) : mX + 8, y: mY, size: 8.5, font, color: textDark }); } catch { /* ignore */ }
        mY -= 10;
      }
      mY -= 2;
    };
    mLine("verificationCode", token || "—");
    mLine("verifyAt", verifyUrl);

    y = vBoxY - 16;

    // ── Personal Information ──────────────────────────────────────────────────
    section("personalInfo");
    kv("name", safe(p.full_name, 120));
    if (p.date_of_birth) kv("dob", fmtDate(p.date_of_birth, locale));
    if (p.gender) kv("gender", safe(p.gender, 40));
    if (p.phone) kv("phone", safe(p.phone, 40));
    if (p.email) kv("email", safe(p.email, 200));
    if (p.address) kv("address", safe(p.address, 300));

    // ── Medical Information ───────────────────────────────────────────────────
    section("medicalInfo");
    if (p.blood_group) kv("bloodGroup", safe(p.blood_group, 20));
    if (p.allergies) multilineKV("allergies", safe(p.allergies, 2000));
    if (p.medical_history) multilineKV("medicalHistory", safe(p.medical_history, 4000));
    if (p.dental_history) multilineKV("dentalHistory", safe(p.dental_history, 2000));
    if (p.current_medications) multilineKV("currentMedications", safe(p.current_medications, 2000));

    // ── Emergency Contact ─────────────────────────────────────────────────────
    if (p.emergency_contact_name || p.emergency_contact_phone) {
      section("emergency");
      if (p.emergency_contact_name) kv("emergencyName", safe(p.emergency_contact_name, 120));
      if (p.emergency_contact_phone) kv("emergencyPhone", safe(p.emergency_contact_phone, 40));
    }

    // ── Recent Appointments ───────────────────────────────────────────────────
    const appts: any[] = Array.isArray(appointments) ? appointments : [];
    if (appts.length > 0) {
      section("recentAppointments");
      for (const a of appts.slice(0, 8)) {
        ensure(22);
        const dateStr = fmtDate(a.appointment_date, locale) + (a.start_time ? ` ${safe(a.start_time, 10)}` : "");
        const statusStr = safe(a.status, 40);
        const row = sanitizePdf(`${dateStr}  |  ${statusStr}`);
        try { page.drawText(row, { x: margin + 8, y, size: 9, font, color: textDark }); } catch { /* ignore */ }
        y -= 12;
        if (a.notes) {
          const noteLines = wrap(sanitizePdf(safe(a.notes, 300)), font, 8.5, W - margin * 2 - 16, locale);
          for (const line of noteLines.slice(0, 2)) {
            ensure(12);
            try { page.drawText(line, { x: margin + 16, y, size: 8.5, font, color: textMuted }); } catch { /* ignore */ }
            y -= 11;
          }
        }
        y -= 3;
      }
    }

    // ── Active Prescriptions ──────────────────────────────────────────────────
    const rxs: any[] = Array.isArray(prescriptions) ? prescriptions : [];
    if (rxs.length > 0) {
      section("activePrescriptions");
      for (const rx of rxs.slice(0, 6)) {
        ensure(24);
        const rxNum = sanitizePdf(safe(rx.prescription_number, 40));
        const rxStatus = sanitizePdf(safe(rx.status, 30));
        const rxDate = fmtDate(rx.prescribed_at, locale);
        try { page.drawText(`${rxNum}  |  ${rxStatus}  |  ${rxDate}`, { x: margin + 8, y, size: 9, font, color: textDark }); } catch { /* ignore */ }
        y -= 12;
        const items: any[] = Array.isArray(rx.prescription_items) ? rx.prescription_items : [];
        for (const item of items.slice(0, 3)) {
          ensure(12);
          const itemLine = sanitizePdf(`• ${safe(item.medication_name, 80)}  ${safe(item.dosage, 40)}  ${safe(item.frequency, 40)}`);
          try { page.drawText(itemLine, { x: margin + 16, y, size: 8.5, font, color: textMuted }); } catch { /* ignore */ }
          y -= 11;
        }
        y -= 4;
      }
    }

    // ── Draw verification footer on ALL pages ─────────────────────────────────
    const pageCount = pdf.getPageCount();
    for (let pg = 0; pg < pageCount; pg++) {
      drawVerifyFooter(pdf.getPage(pg), pg + 1, pageCount);
    }

    const pdfBytes = await pdf.save();
    const safeName = sanitizePdf(safe(p.full_name, 40)).replace(/[^a-zA-Z0-9_-]/g, "_");

    return new Response(pdfBytes as unknown as BodyInit, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="patient-profile-${safeName}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    console.error("patient-profile-generate-pdf error:", e);
    return errorResponse("Failed to generate PDF", 500);
  }
});
