// File: supabase/functions/treatment-plan-generate-pdf/index.ts

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, rgb } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";

import {
  corsHeaders,
  errorResponse,
  secureHandler,
} from "../_shared/security-middleware.ts";
import type { ValidationSchema } from "../_shared/input-validator.ts";

// Reuse Docito branded assets already in the repo (keeps design consistent)
import { DOCITO_FONT_TTF_BASE64, DOCITO_LOGO_PNG_BASE64 } from "../referral-generate-pdf/assets.ts";

type Locale = "en" | "ru" | "uz" | "tr" | "ar" | "ja" | "ko" | "zh" | "es" | "pt" | "de";

type ReqBody = {
  treatment_plan_id: string;
  locale?: string;
};

const schema: ValidationSchema<ReqBody> = {
  treatment_plan_id: { type: "uuid", required: true },
  locale: { type: "string", required: false, minLength: 2, maxLength: 12, sanitize: true, trim: true },
};

function b64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function normalizeLocale(raw?: string | null): Locale {
  const s = (raw || "").toLowerCase().trim();
  if (s.startsWith("ru")) return "ru";
  if (s.startsWith("uz")) return "uz";
  if (s.startsWith("tr")) return "tr";
  if (s.startsWith("ar")) return "ar";
  if (s.startsWith("ja") || s.startsWith("jp")) return "ja";
  if (s.startsWith("ko") || s.startsWith("kr")) return "ko";
  if (s.startsWith("zh")) return "zh";
  if (s.startsWith("es")) return "es";
  if (s.startsWith("pt")) return "pt";
  if (s === "deutsch" || s.startsWith("de")) return "de";
  return "en";
}

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    title: "Treatment Plan",
    planId: "Plan ID",
    verification: "Verification",
    verificationCode: "Verification Code",
    verifyAt: "Verify at",
    createdAt: "Created At",
    updatedAt: "Updated At",
    publishedAt: "Published At",
    completedAt: "Completed At",
    status: "Status",
    totalCost: "Total Cost",
    name: "Title",
    description: "Description",
    notes: "Notes",
    patient: "Patient",
    doctor: "Doctor",
    specialty: "Specialty",
    phone: "Phone",
    email: "Email",
    dob: "Date of Birth",
    gender: "Gender",
    address: "Address",
    procedures: "Procedures",
    medications: "Medications",
    consentForms: "Consent Forms",
    attachments: "Attachments",
    na: "—",
    generatedBy: "Generated by Docito (docito.app)",
    colN: "#",
    colProcedure: "Procedure",
    colTooth: "Tooth",
    colStatus: "Status",
    colCost: "Cost",
  },
  ru: {
    title: "План лечения",
    planId: "ID плана",
    verification: "Проверка",
    verificationCode: "Код проверки",
    verifyAt: "Проверить на",
    createdAt: "Дата создания",
    updatedAt: "Обновлено",
    publishedAt: "Опубликовано",
    completedAt: "Завершено",
    status: "Статус",
    totalCost: "Итоговая стоимость",
    name: "Название",
    description: "Описание",
    notes: "Заметки",
    patient: "Пациент",
    doctor: "Врач",
    specialty: "Специальность",
    phone: "Телефон",
    email: "Email",
    dob: "Дата рождения",
    gender: "Пол",
    address: "Адрес",
    procedures: "Процедуры",
    medications: "Лекарства",
    consentForms: "Согласия",
    attachments: "Вложения",
    na: "—",
    generatedBy: "Сформировано в Docito (docito.app)",
    colN: "№",
    colProcedure: "Процедура",
    colTooth: "Зуб",
    colStatus: "Статус",
    colCost: "Стоимость",
  },
  uz: {
    title: "Davolash rejasi",
    planId: "Reja ID",
    verification: "Tasdiqlash",
    verificationCode: "Tasdiqlash kodi",
    verifyAt: "Tekshirish",
    createdAt: "Yaratilgan sana",
    updatedAt: "Yangilangan",
    publishedAt: "Eʼlon qilingan",
    completedAt: "Yakunlangan",
    status: "Holat",
    totalCost: "Umumiy narx",
    name: "Sarlavha",
    description: "Tavsif",
    notes: "Izohlar",
    patient: "Bemor",
    doctor: "Shifokor",
    specialty: "Mutaxassislik",
    phone: "Telefon",
    email: "Email",
    dob: "Tugʻilgan sana",
    gender: "Jins",
    address: "Manzil",
    procedures: "Muolajalar",
    medications: "Dori-darmonlar",
    consentForms: "Rozilik hujjatlari",
    attachments: "Fayllar",
    na: "—",
    generatedBy: "Docito orqali yaratildi (docito.app)",
    colN: "#",
    colProcedure: "Muolaja",
    colTooth: "Tish",
    colStatus: "Holat",
    colCost: "Narx",
  },

  // Placeholders for Bit 3 (full translations/fonts). For now, fall back to English strings.
  tr: {},
  ar: {},
  ja: {},
  ko: {},
  zh: {},
  es: {},
  pt: {},
  de: {},
};

function t(locale: Locale, key: string): string {
  return I18N[locale]?.[key] || I18N.en[key] || key;
}

function safeText(v: unknown, fallback: string): string {
  const s = typeof v === "string" ? v.trim() : "";
  return s.length ? s : fallback;
}

function safeArray(v: unknown): any[] {
  return Array.isArray(v) ? v : [];
}

function isoDateTime(v: unknown): string | null {
  const s = typeof v === "string" ? v.trim() : "";
  if (!s) return null;
  const d = new Date(s);
  if (isNaN(d.getTime())) return null;
  return d.toISOString().replace("T", " ").slice(0, 19) + "Z";
}

function money(v: unknown): string | null {
  if (typeof v === "number" && isFinite(v)) return v.toFixed(2);
  if (typeof v === "string") {
    const s = v.trim();
    if (!s) return null;
    const n = Number(s);
    if (isFinite(n)) return n.toFixed(2);
    return s;
  }
  return null;
}

function sanitizeFileName(name: string): string {
  return name.replace(/[^\w.\-]+/g, "_").slice(0, 120);
}

function wrapText(font: any, text: string, size: number, maxWidth: number): string[] {
  const clean = (text || "").replace(/\s+/g, " ").trim();
  if (!clean) return [];
  const words = clean.split(" ");
  const lines: string[] = [];
  let line = "";

  for (const w of words) {
    const cand = line ? `${line} ${w}` : w;
    const width = font.widthOfTextAtSize(cand, size);
    if (width > maxWidth) {
      if (line) lines.push(line);
      line = w;
    } else {
      line = cand;
    }
  }

  if (line) lines.push(line);
  return lines;
}

async function getUserPreferredLocale(serviceClient: any, userId: string): Promise<Locale> {
  // 1) user_preferences.preferred_language
  try {
    const { data, error } = await serviceClient
      .from("user_preferences")
      .select("preferred_language")
      .eq("user_id", userId)
      .maybeSingle();
    if (!error) {
      const lang = (data as any)?.preferred_language;
      if (typeof lang === "string" && lang.trim()) return normalizeLocale(lang);
    }
  } catch {
    // ignore
  }

  // 2) profiles.language (some deployments had this column)
  try {
    const { data, error } = await serviceClient
      .from("profiles")
      .select("language")
      .eq("user_id", userId)
      .maybeSingle();
    if (!error) {
      const lang = (data as any)?.language;
      if (typeof lang === "string" && lang.trim()) return normalizeLocale(lang);
    }
  } catch {
    // ignore
  }

  return "en";
}

async function getDoctorDisplay(serviceClient: any, doctorId: string, locale: Locale): Promise<{ name: string | null; specialty: string | null }>{
  const { data } = await serviceClient
    .from("doctors")
    .select("id, user_id, specialty, specialty_en, specialty_ru, specialty_uz")
    .eq("id", doctorId)
    .maybeSingle();

  const d = data as any;
  const userId = d?.user_id ? String(d.user_id) : null;

  let fullName: string | null = null;
  if (userId) {
    const { data: p } = await serviceClient
      .from("profiles")
      .select("full_name")
      .eq("user_id", userId)
      .maybeSingle();
    fullName = (p as any)?.full_name ? String((p as any).full_name) : null;
  }

  const specKey = locale === "ru" ? "specialty_ru" : locale === "uz" ? "specialty_uz" : "specialty_en";
  const specialty = (d as any)?.[specKey] ? String((d as any)[specKey]) : (d?.specialty ? String(d.specialty) : null);

  return { name: fullName, specialty };
}

async function fetchPlanWithAccess(context: any, planId: string): Promise<{ plan: any; doctorId: string | null } | null> {
  const { data: plan, error } = await context.serviceClient
    .from("treatment_plans")
    .select("*")
    .eq("id", planId)
    .maybeSingle();

  if (error) throw error;
  if (!plan) return null;

  const roles: string[] = context.roles || [];
  const userId: string | null = context.userId || null;
  if (!userId) return null;

  const rawDoctorId = (plan as any)?.doctor_id || (plan as any)?.dentist_id || null;
  const doctorId = rawDoctorId ? String(rawDoctorId) : null;

  // Super admin always allowed
  if (roles.includes("super_admin")) return { plan, doctorId };

  // Patient allowed if matches
  const patientId = (plan as any)?.patient_id ? String((plan as any).patient_id) : null;
  if (patientId && patientId === userId) return { plan, doctorId };

  // Doctor allowed if owns this plan (match doctors.id by user_id)
  const { data: d } = await context.serviceClient
    .from("doctors")
    .select("id")
    .eq("user_id", userId)
    .maybeSingle();

  const myDoctorId = (d as any)?.id ? String((d as any).id) : null;
  if (myDoctorId && doctorId && myDoctorId === doctorId) return { plan, doctorId };

  return null;
}

async function listPlanProcedures(serviceClient: any, planId: string): Promise<any[]> {
  // Order may drift; try sequence_order first, then created_at.
  const base = serviceClient.from("treatment_plan_procedures").select("*").eq("treatment_plan_id", planId);

  try {
    const r1 = await base.order("sequence_order", { ascending: true });
    if (!r1.error) return (r1.data || []) as any[];
  } catch {
    // ignore
  }

  const r2 = await base.order("created_at", { ascending: true });
  if (r2.error) throw r2.error;
  return (r2.data || []) as any[];
}

async function listPlanMedications(serviceClient: any, planId: string): Promise<any[]> {
  if (!planId) return [];
  try {
    const r = await serviceClient
      .from("treatment_plan_medications")
      .select("*")
      .eq("treatment_plan_id", planId)
      .order("created_at", { ascending: true });
    if (r.error) return [];
    return (r.data || []) as any[];
  } catch {
    return [];
  }
}

async function listPlanConsents(serviceClient: any, planId: string): Promise<any[]> {
  if (!planId) return [];
  try {
    const r = await serviceClient
      .from("consent_forms")
      .select("*")
      .eq("treatment_plan_id", planId)
      .order("created_at", { ascending: true });
    if (r.error) return [];
    return (r.data || []) as any[];
  } catch {
    return [];
  }
}

async function listPlanAttachments(serviceClient: any, planId: string): Promise<any[]> {
  if (!planId) return [];
  try {
    const r = await serviceClient
      .from("procedure_attachments")
      .select("*")
      .eq("treatment_plan_id", planId)
      .order("created_at", { ascending: true });
    if (r.error) return [];
    return (r.data || []) as any[];
  } catch {
    return [];
  }
}

async function buildPdf(params: {
  locale: Locale;
  plan: any;
  patientProfile: any | null;
  doctorDisplay: { name: string | null; specialty: string | null } | null;
  procedures: any[];
  medications: any[];
  consents: any[];
  attachments: any[];
}) {
  const W = 595.28; // A4
  const H = 841.89;
  const margin = 44;

  const pdf = await PDFDocument.create();
  pdf.registerFontkit(fontkit);

  const fontBytes = b64ToBytes(DOCITO_FONT_TTF_BASE64);
  const font = await pdf.embedFont(fontBytes, { subset: true });

  const logoBytes = b64ToBytes(DOCITO_LOGO_PNG_BASE64);
  const logo = await pdf.embedPng(logoBytes);

  const logoW = 42;
  const logoH = (logo.height / logo.width) * logoW;

  const planId = String(params.plan?.id || "");
  const verificationCode = safeText(params.plan?.verification_code, planId || t(params.locale, "na"));
  const verifyUrl = `https://docito.app/verify/treatment-plan?code=${encodeURIComponent(verificationCode)}`;

  let pageIndex = 0;
  let page = pdf.addPage([W, H]);
  let y = H - margin;

  const header = (continued = false) => {
    y = H - margin;

    page.drawImage(logo, { x: margin, y: y - logoH, width: logoW, height: logoH });

    page.drawText("docito.app", {
      x: W - margin - font.widthOfTextAtSize("docito.app", 10),
      y: y - 12,
      size: 10,
      font,
      color: rgb(0.25, 0.25, 0.25),
    });

    y -= logoH + 18;

    const title = continued ? `${t(params.locale, "title")} (${pageIndex + 1})` : t(params.locale, "title");
    page.drawText(title, {
      x: margin,
      y,
      size: 20,
      font,
      color: rgb(0.05, 0.05, 0.05),
    });

    y -= 18;

    page.drawLine({
      start: { x: margin, y },
      end: { x: W - margin, y },
      thickness: 1,
      color: rgb(0.85, 0.85, 0.85),
    });

    y -= 16;
  };

  const newPage = () => {
    pageIndex += 1;
    page = pdf.addPage([W, H]);
    header(true);
  };

  const ensureSpace = (needed: number) => {
    if (y - needed < margin + 90) newPage();
  };

  const colLabelX = margin;
  const colValueX = margin + 170;
  const maxValueW = W - margin - colValueX;
  const labelSize = 10;
  const valueSize = 10;
  const lineGap = 14;

  const drawKV = (label: string, value: string) => {
    const lines = wrapText(font, value, valueSize, maxValueW);
    const needed = Math.max(1, lines.length || 1) * lineGap + 2;
    ensureSpace(needed);

    page.drawText(label, { x: colLabelX, y, size: labelSize, font, color: rgb(0.25, 0.25, 0.25) });

    if (lines.length === 0) {
      page.drawText(t(params.locale, "na"), { x: colValueX, y, size: valueSize, font, color: rgb(0.05, 0.05, 0.05) });
      y -= lineGap;
      return;
    }

    for (let i = 0; i < lines.length; i++) {
      page.drawText(lines[i], { x: colValueX, y, size: valueSize, font, color: rgb(0.05, 0.05, 0.05) });
      y -= lineGap;
    }
  };

  const drawSection = (title: string) => {
    ensureSpace(40);
    y -= 6;
    page.drawText(title, { x: margin, y, size: 12, font, color: rgb(0.1, 0.1, 0.1) });
    y -= 10;
    page.drawLine({
      start: { x: margin, y },
      end: { x: W - margin, y },
      thickness: 0.8,
      color: rgb(0.9, 0.9, 0.9),
    });
    y -= 14;
  };

  const drawListItem = (text: string) => {
    const x = margin + 10;
    const maxW = W - margin - x;
    const lines = wrapText(font, text, 10, maxW);
    const needed = Math.max(1, lines.length) * 14 + 2;
    ensureSpace(needed);

    page.drawText("•", { x: margin, y, size: 11, font, color: rgb(0.25, 0.25, 0.25) });
    for (const ln of lines) {
      page.drawText(ln, { x, y, size: 10, font, color: rgb(0.05, 0.05, 0.05) });
      y -= 14;
    }
  };

  const drawProcedureTable = (rows: any[]) => {
    ensureSpace(60);

    const tableX = margin;
    const tableW = W - margin * 2;

    const c1 = 26;  // #
    const c2 = 260; // procedure
    const c3 = 70;  // tooth
    const c4 = 90;  // status
    const c5 = tableW - (c1 + c2 + c3 + c4); // cost

    const headerY = y;
    const rowH = 18;

    const drawHeaderCell = (text: string, x: number, w: number) => {
      page.drawText(text, { x: x + 4, y: headerY, size: 10, font, color: rgb(0.25, 0.25, 0.25) });
      page.drawLine({ start: { x, y: headerY - 6 }, end: { x: x + w, y: headerY - 6 }, thickness: 0.6, color: rgb(0.9, 0.9, 0.9) });
    };

    drawHeaderCell(t(params.locale, "colN"), tableX, c1);
    drawHeaderCell(t(params.locale, "colProcedure"), tableX + c1, c2);
    drawHeaderCell(t(params.locale, "colTooth"), tableX + c1 + c2, c3);
    drawHeaderCell(t(params.locale, "colStatus"), tableX + c1 + c2 + c3, c4);
    drawHeaderCell(t(params.locale, "colCost"), tableX + c1 + c2 + c3 + c4, c5);

    y -= 18;

    for (let i = 0; i < rows.length; i++) {
      const r = rows[i] || {};
      const idx = String(i + 1);

      const procName = safeText(
        r.display_name,
        safeText(r.procedure_name, safeText(r.name, t(params.locale, "na"))),
      );

      const tooth = Array.isArray(r.tooth_numbers) && r.tooth_numbers.length
        ? r.tooth_numbers.join(",")
        : safeText(r.tooth, t(params.locale, "na"));

      const status = safeText(r.status, t(params.locale, "na"));
      const costStr = safeText(r.cost, t(params.locale, "na"));

      const procLines = wrapText(font, procName, 10, c2 - 8);
      const linesCount = Math.max(1, procLines.length);
      const needed = linesCount * 14 + 10;
      ensureSpace(needed);

      // #
      page.drawText(idx, { x: tableX + 4, y, size: 10, font, color: rgb(0.05, 0.05, 0.05) });

      // Procedure (wrapped)
      let yy = y;
      for (const ln of procLines.length ? procLines : [t(params.locale, "na")]) {
        page.drawText(ln, { x: tableX + c1 + 4, y: yy, size: 10, font, color: rgb(0.05, 0.05, 0.05) });
        yy -= 14;
      }

      // Tooth / Status / Cost align to first line
      page.drawText(tooth, { x: tableX + c1 + c2 + 4, y, size: 10, font, color: rgb(0.05, 0.05, 0.05) });
      page.drawText(status, { x: tableX + c1 + c2 + c3 + 4, y, size: 10, font, color: rgb(0.05, 0.05, 0.05) });

      const costX = tableX + c1 + c2 + c3 + c4 + 4;
      page.drawText(costStr, { x: costX, y, size: 10, font, color: rgb(0.05, 0.05, 0.05) });

      // Row separator
      const sepY = y - (linesCount * 14) - 2;
      page.drawLine({
        start: { x: tableX, y: sepY },
        end: { x: tableX + tableW, y: sepY },
        thickness: 0.5,
        color: rgb(0.93, 0.93, 0.93),
      });

      y = sepY - 10;
    }
  };

  header(false);

  // ---- Plan details ----
  drawSection(t(params.locale, "title"));

  const status = safeText(params.plan?.status, t(params.locale, "na"));
  const createdAt = isoDateTime(params.plan?.created_at) || t(params.locale, "na");
  const updatedAt = isoDateTime(params.plan?.updated_at) || t(params.locale, "na");
  const publishedAt = isoDateTime(params.plan?.published_at) || t(params.locale, "na");
  const completedAt = isoDateTime(params.plan?.completed_at) || t(params.locale, "na");

  const title = safeText(params.plan?.title, t(params.locale, "na"));
  const description = safeText(params.plan?.description, "");
  const notes = safeText(params.plan?.notes, "");

  const totalCost = money(params.plan?.total_cost) || money(params.plan?.totalCost) || t(params.locale, "na");

  drawKV(t(params.locale, "planId"), safeText(planId, t(params.locale, "na")));
  drawKV(t(params.locale, "verificationCode"), safeText(verificationCode, t(params.locale, "na")));
  drawKV(t(params.locale, "status"), status);
  drawKV(t(params.locale, "createdAt"), createdAt);
  drawKV(t(params.locale, "updatedAt"), updatedAt);

  if (safeText(params.plan?.published_at, "").length) drawKV(t(params.locale, "publishedAt"), publishedAt);
  if (safeText(params.plan?.completed_at, "").length) drawKV(t(params.locale, "completedAt"), completedAt);

  drawKV(t(params.locale, "totalCost"), totalCost);
  drawKV(t(params.locale, "name"), title);

  if (description) drawKV(t(params.locale, "description"), description);
  if (notes) drawKV(t(params.locale, "notes"), notes);

  // ---- Patient ----
  drawSection(t(params.locale, "patient"));

  const p = params.patientProfile || null;
  drawKV(t(params.locale, "name"), safeText(p?.full_name, t(params.locale, "na")));
  drawKV(t(params.locale, "phone"), safeText(p?.phone, t(params.locale, "na")));
  drawKV(t(params.locale, "email"), safeText(p?.email, t(params.locale, "na")));
  drawKV(t(params.locale, "dob"), safeText(p?.date_of_birth, t(params.locale, "na")));
  drawKV(t(params.locale, "gender"), safeText(p?.gender, t(params.locale, "na")));
  drawKV(t(params.locale, "address"), safeText(p?.address, t(params.locale, "na")));

  // ---- Doctor ----
  drawSection(t(params.locale, "doctor"));
  drawKV(t(params.locale, "name"), safeText(params.doctorDisplay?.name, t(params.locale, "na")));
  drawKV(t(params.locale, "specialty"), safeText(params.doctorDisplay?.specialty, t(params.locale, "na")));

  // ---- Procedures ----
  drawSection(t(params.locale, "procedures"));
  if (params.procedures.length === 0) {
    drawKV(t(params.locale, "procedures"), t(params.locale, "na"));
  } else {
    drawProcedureTable(params.procedures);
  }

  // ---- Medications ----
  drawSection(t(params.locale, "medications"));
  if (params.medications.length === 0) {
    drawKV(t(params.locale, "medications"), t(params.locale, "na"));
  } else {
    for (const m of params.medications) {
      const name = safeText(m?.medication_name, safeText(m?.name, t(params.locale, "na")));
      const dosage = safeText(m?.dosage, "");
      const frequency = safeText(m?.frequency, "");
      const start = safeText(m?.start_date, "");
      const end = safeText(m?.end_date, "");
      const instr = safeText(m?.instructions, "");

      const parts = [
        name,
        dosage ? `• ${dosage}` : "",
        frequency ? `• ${frequency}` : "",
        start || end ? `• ${[start, end].filter(Boolean).join(" → ")}` : "",
        instr ? `• ${instr}` : "",
      ].filter(Boolean);

      drawListItem(parts.join(" "));
    }
  }

  // ---- Consent forms ----
  drawSection(t(params.locale, "consentForms"));
  if (params.consents.length === 0) {
    drawKV(t(params.locale, "consentForms"), t(params.locale, "na"));
  } else {
    for (const c of params.consents) {
      const titleC = safeText(c?.title, t(params.locale, "na"));
      const statusC = safeText(c?.status, t(params.locale, "na"));
      const signedAt = isoDateTime(c?.signed_at) || "";
      const line = `${titleC} • ${statusC}${signedAt ? ` • ${signedAt}` : ""}`;
      drawListItem(line);
    }
  }

  // ---- Attachments ----
  drawSection(t(params.locale, "attachments"));
  if (params.attachments.length === 0) {
    drawKV(t(params.locale, "attachments"), t(params.locale, "na"));
  } else {
    for (const a of params.attachments) {
      const file = safeText(a?.file_name, safeText(a?.name, t(params.locale, "na")));
      const type = safeText(a?.file_type, "");
      const size = typeof a?.file_size === "number" ? `${a.file_size} B` : safeText(a?.file_size, "");
      const line = [file, type ? `• ${type}` : "", size ? `• ${size}` : ""].filter(Boolean).join(" ");
      drawListItem(line);
    }
  }

  // ---- Footer verification (last page) ----
  ensureSpace(110);
  const footerY = margin + 30;

  page.drawLine({
    start: { x: margin, y: footerY + 70 },
    end: { x: W - margin, y: footerY + 70 },
    thickness: 0.8,
    color: rgb(0.9, 0.9, 0.9),
  });

  page.drawText(t(params.locale, "generatedBy"), {
    x: margin,
    y: footerY + 8,
    size: 9,
    font,
    color: rgb(0.35, 0.35, 0.35),
  });

  page.drawText(t(params.locale, "verification") + ":", {
    x: margin,
    y: footerY + 44,
    size: 10,
    font,
    color: rgb(0.25, 0.25, 0.25),
  });

  page.drawText(`${t(params.locale, "verificationCode")}: ${verificationCode}`, {
    x: margin,
    y: footerY + 30,
    size: 9,
    font,
    color: rgb(0.05, 0.05, 0.05),
  });

  page.drawText(`${t(params.locale, "verifyAt")}: ${verifyUrl}`, {
    x: margin,
    y: footerY + 18,
    size: 9,
    font,
    color: rgb(0.05, 0.05, 0.05),
  });

  try {
    const dataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1, width: 140 });
    const b64 = dataUrl.split(",")[1] || "";
    if (b64) {
      const qrBytes = b64ToBytes(b64);
      const qr = await pdf.embedPng(qrBytes);
      const qrW = 92;
      const qrH = 92;
      page.drawImage(qr, { x: W - margin - qrW, y: footerY + 6, width: qrW, height: qrH });
    }
  } catch {
    // ignore QR failures
  }

  return await pdf.save();
}

serve(async (req) => {
  const sec = await secureHandler(req, "treatment-plan-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "standard",
    validationSchema: schema,
  });

  if (sec.response) return sec.response;

  const context = sec.context!;
  const body = sec.validatedBody as ReqBody;

  try {
    const planId = body.treatment_plan_id;
    const locale = body.locale
      ? normalizeLocale(body.locale)
      : await getUserPreferredLocale(context.serviceClient, context.userId!);

    const access = await fetchPlanWithAccess(context, planId);
    if (!access) return errorResponse("Insufficient permissions", 403);

    const plan = access.plan;
    const patientId = plan?.patient_id ? String(plan.patient_id) : null;

    let patientProfile: any | null = null;
    if (patientId) {
      const { data } = await context.serviceClient
        .from("profiles")
        .select("*")
        .eq("user_id", patientId)
        .maybeSingle();
      patientProfile = (data as any) || null;
    }

    let doctorDisplay: { name: string | null; specialty: string | null } | null = null;
    if (access.doctorId) {
      doctorDisplay = await getDoctorDisplay(context.serviceClient, access.doctorId, locale);
    }

    const rawProcedures = await listPlanProcedures(context.serviceClient, planId);

    // If treatment_plan_procedures has procedure_id, map to procedures table for names/default cost if needed
    const procedureIds = Array.from(
      new Set(
        rawProcedures
          .map((p: any) => p?.procedure_id)
          .filter((x: any) => typeof x === "string" && x.length > 10),
      ),
    ) as string[];

    const catalogById = new Map<string, any>();
    if (procedureIds.length > 0) {
      try {
        const { data } = await context.serviceClient
          .from("procedures")
          .select("*")
          .in("id", procedureIds);
        for (const r of safeArray(data)) {
          if (r?.id) catalogById.set(String(r.id), r);
        }
      } catch {
        // ignore
      }
    }

    const procedures = rawProcedures.map((p: any) => {
      const pid = p?.procedure_id ? String(p.procedure_id) : null;
      const cat = pid ? catalogById.get(pid) : null;

      const displayName =
        safeText(p?.procedure_name, "") ||
        safeText(cat?.name, "") ||
        safeText(p?.name, "") ||
        safeText(cat?.procedure_name, "") ||
        "";

      const tooth_numbers = Array.isArray(p?.tooth_numbers) ? p.tooth_numbers : null;

      const costVal =
        money(p?.custom_cost) ||
        money(p?.cost) ||
        money(p?.custom_price) ||
        money(cat?.default_cost) ||
        money(cat?.default_price) ||
        null;

      return {
        ...p,
        display_name: displayName,
        tooth_numbers,
        cost: costVal || t(locale, "na"),
      };
    });

    const medications = await listPlanMedications(context.serviceClient, planId);
    const consents = await listPlanConsents(context.serviceClient, planId);
    const attachments = await listPlanAttachments(context.serviceClient, planId);

    const pdfBytes = await buildPdf({
      locale,
      plan,
      patientProfile,
      doctorDisplay,
      procedures,
      medications,
      consents,
      attachments,
    });

    const verificationCode = safeText(plan?.verification_code, safeText(plan?.id, "treatment_plan"));
    const fileName = sanitizeFileName(`treatment-plan_${verificationCode}.pdf`);

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (e) {
    console.error("treatment-plan-generate-pdf error:", e);
    return errorResponse("Failed to generate PDF", 500);
  }
});
