// Path: supabase/functions/treatment-plan-generate-pdf/index.ts

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { PDFDocument, PDFFont, PDFPage, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";
import QRCode from "https://esm.sh/qrcode@1.5.3";
import reshaper from "https://esm.sh/arabic-persian-reshaper@1.0.0";
import bidiFactory from "https://esm.sh/bidi-js@1.0.2";

import {
  corsHeaders,
  errorResponse,
  secureHandler,
} from "../_shared/security-middleware.ts";
import type { ValidationSchema } from "../_shared/input-validator.ts";

import { DOCITO_FONT_TTF_BASE64, DOCITO_LOGO_PNG_BASE64 } from "./assets.ts";

type Locale =
  | "en"
  | "ru"
  | "uz"
  | "tr"
  | "ar"
  | "ja"
  | "ko"
  | "zh"
  | "es"
  | "pt"
  | "de";

type ReqBody = {
  treatment_plan_id: string;
  locale?: string;
};

const schema: ValidationSchema<ReqBody> = {
  treatment_plan_id: { type: "uuid", required: true },
  locale: { type: "string", required: false, minLength: 2, maxLength: 16, sanitize: true, trim: true },
};

function b64ToBytes(b64: string): Uint8Array {
  try {
    const bin = atob(b64);
    if (bin.length < 16) throw new Error("base64 payload too small");
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  } catch {
    return new Uint8Array(0);
  }
}

function normalizeLocale(raw?: string | null): Locale {
  const s = (raw || "").toLowerCase().trim();
  if (s === "deutsch") return "de";
  if (s.startsWith("de")) return "de";
  if (s.startsWith("ru")) return "ru";
  if (s.startsWith("uz")) return "uz";
  if (s.startsWith("tr")) return "tr";
  if (s.startsWith("ar")) return "ar";
  if (s.startsWith("ja")) return "ja";
  if (s.startsWith("ko")) return "ko";
  if (s.startsWith("zh")) return "zh";
  if (s.startsWith("es")) return "es";
  if (s.startsWith("pt")) return "pt";
  return "en";
}

const I18N: Record<Locale, Record<string, string>> = {
  en: {
    title: "Treatment Plan",
    planId: "Plan ID",
    createdAt: "Created At",
    updatedAt: "Updated At",
    publishedAt: "Published At",
    completedAt: "Completed At",
    status: "Status",
    totalCost: "Total Cost",
    description: "Description",
    notes: "Notes",
    patient: "Patient",
    doctor: "Provider",
    specialty: "Specialty",
    phone: "Phone",
    email: "Email",
    dob: "Date of Birth",
    gender: "Gender",
    address: "Address",
    procedures: "Procedures",
    procedure: "Procedure",
    tooth: "Tooth/Teeth",
    cost: "Cost",
    procedureStatus: "Status",
    procedureNotes: "Notes",
    medications: "Medications",
    medication: "Medication",
    dosage: "Dosage",
    frequency: "Frequency",
    instructions: "Instructions",
    startDate: "Start Date",
    endDate: "End Date",
    medicationStatus: "Status",
    consentForms: "Consent Forms",
    consentTitle: "Title",
    consentStatus: "Status",
    signedAt: "Signed At",
    consentContent: "Content",
    attachments: "Attachments",
    fileName: "File",
    fileType: "Type",
    filePath: "Path",
    uploadedAt: "Uploaded At",
    fileDescription: "Description",
    dentalChart: "Dental Chart",
    teethInvolved: "Teeth involved",
    verification: "Verification",
    verificationCode: "Verification Code",
    verifyAt: "Verify at",
    generatedBy: "Generated by Docito (docito.app)",
    na: "—",
  },
  ru: {
    title: "План лечения",
    planId: "ID плана",
    createdAt: "Дата создания",
    updatedAt: "Дата обновления",
    publishedAt: "Дата публикации",
    completedAt: "Дата завершения",
    status: "Статус",
    totalCost: "Итоговая стоимость",
    description: "Описание",
    notes: "Заметки",
    patient: "Пациент",
    doctor: "Врач/провайдер",
    specialty: "Специальность",
    phone: "Телефон",
    email: "Email",
    dob: "Дата рождения",
    gender: "Пол",
    address: "Адрес",
    procedures: "Процедуры",
    procedure: "Процедура",
    tooth: "Зуб(ы)",
    cost: "Стоимость",
    procedureStatus: "Статус",
    procedureNotes: "Заметки",
    medications: "Назначения",
    medication: "Препарат",
    dosage: "Дозировка",
    frequency: "Частота",
    instructions: "Инструкции",
    startDate: "Начало",
    endDate: "Окончание",
    medicationStatus: "Статус",
    consentForms: "Согласия",
    consentTitle: "Название",
    consentStatus: "Статус",
    signedAt: "Подписано",
    consentContent: "Содержание",
    attachments: "Вложения",
    fileName: "Файл",
    fileType: "Тип",
    filePath: "Путь",
    uploadedAt: "Загружено",
    fileDescription: "Описание",
    dentalChart: "Зубная схема",
    teethInvolved: "Задействованные зубы",
    verification: "Проверка",
    verificationCode: "Код проверки",
    verifyAt: "Проверить на",
    generatedBy: "Сформировано в Docito (docito.app)",
    na: "—",
  },
  uz: {
    title: "Davolash rejasi",
    planId: "Reja ID",
    createdAt: "Yaratilgan sana",
    updatedAt: "Yangilangan sana",
    publishedAt: "E’lon qilingan sana",
    completedAt: "Yakunlangan sana",
    status: "Holat",
    totalCost: "Umumiy narx",
    description: "Tavsif",
    notes: "Qaydlar",
    patient: "Bemor",
    doctor: "Shifokor/Provayder",
    specialty: "Mutaxassislik",
    phone: "Telefon",
    email: "Email",
    dob: "Tug‘ilgan sana",
    gender: "Jins",
    address: "Manzil",
    procedures: "Protseduralar",
    procedure: "Protsedura",
    tooth: "Tish(lar)",
    cost: "Narx",
    procedureStatus: "Holat",
    procedureNotes: "Qaydlar",
    medications: "Dori-darmonlar",
    medication: "Dori",
    dosage: "Doza",
    frequency: "Qabul qilish tezligi",
    instructions: "Ko‘rsatmalar",
    startDate: "Boshlanish",
    endDate: "Tugash",
    medicationStatus: "Holat",
    consentForms: "Rozilik shakllari",
    consentTitle: "Sarlavha",
    consentStatus: "Holat",
    signedAt: "Imzolangan sana",
    consentContent: "Mazmuni",
    attachments: "Ilovalar",
    fileName: "Fayl",
    fileType: "Turi",
    filePath: "Yo‘l",
    uploadedAt: "Yuklangan sana",
    fileDescription: "Tavsif",
    dentalChart: "Tish jadvali",
    teethInvolved: "Qamrab olingan tishlar",
    verification: "Tasdiqlash",
    verificationCode: "Tasdiqlash kodi",
    verifyAt: "Tekshirish",
    generatedBy: "Docito orqali yaratildi (docito.app)",
    na: "—",
  },
  tr: {
    title: "Tedavi Planı",
    planId: "Plan ID",
    createdAt: "Oluşturulma Tarihi",
    updatedAt: "Güncellenme Tarihi",
    publishedAt: "Yayınlanma Tarihi",
    completedAt: "Tamamlanma Tarihi",
    status: "Durum",
    totalCost: "Toplam Tutar",
    description: "Açıklama",
    notes: "Notlar",
    patient: "Hasta",
    doctor: "Sağlayıcı",
    specialty: "Uzmanlık",
    phone: "Telefon",
    email: "E-posta",
    dob: "Doğum Tarihi",
    gender: "Cinsiyet",
    address: "Adres",
    procedures: "İşlemler",
    procedure: "İşlem",
    tooth: "Diş(ler)",
    cost: "Ücret",
    procedureStatus: "Durum",
    procedureNotes: "Notlar",
    medications: "İlaçlar",
    medication: "İlaç",
    dosage: "Doz",
    frequency: "Sıklık",
    instructions: "Talimatlar",
    startDate: "Başlangıç",
    endDate: "Bitiş",
    medicationStatus: "Durum",
    consentForms: "Onam Formları",
    consentTitle: "Başlık",
    consentStatus: "Durum",
    signedAt: "İmzalanma",
    consentContent: "İçerik",
    attachments: "Ekler",
    fileName: "Dosya",
    fileType: "Tür",
    filePath: "Yol",
    uploadedAt: "Yüklenme",
    fileDescription: "Açıklama",
    dentalChart: "Diş Şeması",
    teethInvolved: "İlgili dişler",
    verification: "Doğrulama",
    verificationCode: "Doğrulama Kodu",
    verifyAt: "Şurada doğrula",
    generatedBy: "Docito tarafından oluşturuldu (docito.app)",
    na: "—",
  },
  ar: {
    title: "خطة العلاج",
    planId: "معرّف الخطة",
    createdAt: "تاريخ الإنشاء",
    updatedAt: "تاريخ التحديث",
    publishedAt: "تاريخ النشر",
    completedAt: "تاريخ الإكمال",
    status: "الحالة",
    totalCost: "التكلفة الإجمالية",
    description: "الوصف",
    notes: "ملاحظات",
    patient: "المريض",
    doctor: "مقدّم الخدمة",
    specialty: "التخصص",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    dob: "تاريخ الميلاد",
    gender: "الجنس",
    address: "العنوان",
    procedures: "الإجراءات",
    procedure: "إجراء",
    tooth: "السن/الأسنان",
    cost: "التكلفة",
    procedureStatus: "الحالة",
    procedureNotes: "ملاحظات",
    medications: "الأدوية",
    medication: "دواء",
    dosage: "الجرعة",
    frequency: "الوتيرة",
    instructions: "التعليمات",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    medicationStatus: "الحالة",
    consentForms: "نماذج الموافقة",
    consentTitle: "العنوان",
    consentStatus: "الحالة",
    signedAt: "وقت التوقيع",
    consentContent: "المحتوى",
    attachments: "المرفقات",
    fileName: "الملف",
    fileType: "النوع",
    filePath: "المسار",
    uploadedAt: "تاريخ الرفع",
    fileDescription: "الوصف",
    dentalChart: "مخطط الأسنان",
    teethInvolved: "الأسنان المعنية",
    verification: "التحقق",
    verificationCode: "رمز التحقق",
    verifyAt: "تحقق عبر",
    generatedBy: "تم الإنشاء بواسطة Docito (docito.app)",
    na: "—",
  },
  ja: {
    title: "治療計画",
    planId: "計画ID",
    createdAt: "作成日時",
    updatedAt: "更新日時",
    publishedAt: "公開日時",
    completedAt: "完了日時",
    status: "ステータス",
    totalCost: "合計費用",
    description: "説明",
    notes: "メモ",
    patient: "患者",
    doctor: "提供者",
    specialty: "専門",
    phone: "電話",
    email: "メール",
    dob: "生年月日",
    gender: "性別",
    address: "住所",
    procedures: "処置",
    procedure: "処置",
    tooth: "歯",
    cost: "費用",
    procedureStatus: "ステータス",
    procedureNotes: "メモ",
    medications: "薬",
    medication: "薬",
    dosage: "用量",
    frequency: "頻度",
    instructions: "指示",
    startDate: "開始日",
    endDate: "終了日",
    medicationStatus: "ステータス",
    consentForms: "同意書",
    consentTitle: "タイトル",
    consentStatus: "ステータス",
    signedAt: "署名日時",
    consentContent: "内容",
    attachments: "添付ファイル",
    fileName: "ファイル",
    fileType: "種類",
    filePath: "パス",
    uploadedAt: "アップロード日時",
    fileDescription: "説明",
    dentalChart: "歯式",
    teethInvolved: "対象の歯",
    verification: "検証",
    verificationCode: "検証コード",
    verifyAt: "確認先",
    generatedBy: "Docitoで生成 (docito.app)",
    na: "—",
  },
  ko: {
    title: "치료 계획",
    planId: "계획 ID",
    createdAt: "생성일",
    updatedAt: "수정일",
    publishedAt: "게시일",
    completedAt: "완료일",
    status: "상태",
    totalCost: "총 비용",
    description: "설명",
    notes: "메모",
    patient: "환자",
    doctor: "제공자",
    specialty: "전문 분야",
    phone: "전화",
    email: "이메일",
    dob: "생년월일",
    gender: "성별",
    address: "주소",
    procedures: "시술",
    procedure: "시술",
    tooth: "치아",
    cost: "비용",
    procedureStatus: "상태",
    procedureNotes: "메모",
    medications: "약",
    medication: "약",
    dosage: "용량",
    frequency: "빈도",
    instructions: "지침",
    startDate: "시작일",
    endDate: "종료일",
    medicationStatus: "상태",
    consentForms: "동의서",
    consentTitle: "제목",
    consentStatus: "상태",
    signedAt: "서명일",
    consentContent: "내용",
    attachments: "첨부파일",
    fileName: "파일",
    fileType: "유형",
    filePath: "경로",
    uploadedAt: "업로드일",
    fileDescription: "설명",
    dentalChart: "치아 차트",
    teethInvolved: "관련 치아",
    verification: "검증",
    verificationCode: "검증 코드",
    verifyAt: "확인 주소",
    generatedBy: "Docito에서 생성 (docito.app)",
    na: "—",
  },
  zh: {
    title: "治疗计划",
    planId: "计划ID",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    publishedAt: "发布时间",
    completedAt: "完成时间",
    status: "状态",
    totalCost: "总费用",
    description: "描述",
    notes: "备注",
    patient: "患者",
    doctor: "服务提供者",
    specialty: "专业",
    phone: "电话",
    email: "邮箱",
    dob: "出生日期",
    gender: "性别",
    address: "地址",
    procedures: "治疗项目",
    procedure: "项目",
    tooth: "牙位",
    cost: "费用",
    procedureStatus: "状态",
    procedureNotes: "备注",
    medications: "用药",
    medication: "药品",
    dosage: "剂量",
    frequency: "频次",
    instructions: "说明",
    startDate: "开始日期",
    endDate: "结束日期",
    medicationStatus: "状态",
    consentForms: "知情同意书",
    consentTitle: "标题",
    consentStatus: "状态",
    signedAt: "签署时间",
    consentContent: "内容",
    attachments: "附件",
    fileName: "文件",
    fileType: "类型",
    filePath: "路径",
    uploadedAt: "上传时间",
    fileDescription: "描述",
    dentalChart: "牙位图",
    teethInvolved: "涉及牙位",
    verification: "验证",
    verificationCode: "验证码",
    verifyAt: "验证地址",
    generatedBy: "由 Docito 生成 (docito.app)",
    na: "—",
  },
  es: {
    title: "Plan de tratamiento",
    planId: "ID del plan",
    createdAt: "Creado el",
    updatedAt: "Actualizado el",
    publishedAt: "Publicado el",
    completedAt: "Completado el",
    status: "Estado",
    totalCost: "Costo total",
    description: "Descripción",
    notes: "Notas",
    patient: "Paciente",
    doctor: "Proveedor",
    specialty: "Especialidad",
    phone: "Teléfono",
    email: "Email",
    dob: "Fecha de nacimiento",
    gender: "Género",
    address: "Dirección",
    procedures: "Procedimientos",
    procedure: "Procedimiento",
    tooth: "Diente(s)",
    cost: "Costo",
    procedureStatus: "Estado",
    procedureNotes: "Notas",
    medications: "Medicamentos",
    medication: "Medicamento",
    dosage: "Dosis",
    frequency: "Frecuencia",
    instructions: "Instrucciones",
    startDate: "Inicio",
    endDate: "Fin",
    medicationStatus: "Estado",
    consentForms: "Consentimientos",
    consentTitle: "Título",
    consentStatus: "Estado",
    signedAt: "Firmado el",
    consentContent: "Contenido",
    attachments: "Adjuntos",
    fileName: "Archivo",
    fileType: "Tipo",
    filePath: "Ruta",
    uploadedAt: "Subido el",
    fileDescription: "Descripción",
    dentalChart: "Odontograma",
    teethInvolved: "Dientes involucrados",
    verification: "Verificación",
    verificationCode: "Código de verificación",
    verifyAt: "Verificar en",
    generatedBy: "Generado por Docito (docito.app)",
    na: "—",
  },
  pt: {
    title: "Plano de tratamento",
    planId: "ID do plano",
    createdAt: "Criado em",
    updatedAt: "Atualizado em",
    publishedAt: "Publicado em",
    completedAt: "Concluído em",
    status: "Status",
    totalCost: "Custo total",
    description: "Descrição",
    notes: "Notas",
    patient: "Paciente",
    doctor: "Prestador",
    specialty: "Especialidade",
    phone: "Telefone",
    email: "Email",
    dob: "Data de nascimento",
    gender: "Gênero",
    address: "Endereço",
    procedures: "Procedimentos",
    procedure: "Procedimento",
    tooth: "Dente(s)",
    cost: "Custo",
    procedureStatus: "Status",
    procedureNotes: "Notas",
    medications: "Medicamentos",
    medication: "Medicamento",
    dosage: "Dosagem",
    frequency: "Frequência",
    instructions: "Instruções",
    startDate: "Início",
    endDate: "Fim",
    medicationStatus: "Status",
    consentForms: "Termos de consentimento",
    consentTitle: "Título",
    consentStatus: "Status",
    signedAt: "Assinado em",
    consentContent: "Conteúdo",
    attachments: "Anexos",
    fileName: "Arquivo",
    fileType: "Tipo",
    filePath: "Caminho",
    uploadedAt: "Enviado em",
    fileDescription: "Descrição",
    dentalChart: "Odontograma",
    teethInvolved: "Dentes envolvidos",
    verification: "Verificação",
    verificationCode: "Código de verificação",
    verifyAt: "Verificar em",
    generatedBy: "Gerado por Docito (docito.app)",
    na: "—",
  },
  de: {
    title: "Behandlungsplan",
    planId: "Plan-ID",
    createdAt: "Erstellt am",
    updatedAt: "Aktualisiert am",
    publishedAt: "Veröffentlicht am",
    completedAt: "Abgeschlossen am",
    status: "Status",
    totalCost: "Gesamtkosten",
    description: "Beschreibung",
    notes: "Notizen",
    patient: "Patient",
    doctor: "Behandler",
    specialty: "Fachgebiet",
    phone: "Telefon",
    email: "E-Mail",
    dob: "Geburtsdatum",
    gender: "Geschlecht",
    address: "Adresse",
    procedures: "Behandlungen",
    procedure: "Behandlung",
    tooth: "Zahn/Zähne",
    cost: "Kosten",
    procedureStatus: "Status",
    procedureNotes: "Notizen",
    medications: "Medikamente",
    medication: "Medikament",
    dosage: "Dosierung",
    frequency: "Häufigkeit",
    instructions: "Anweisungen",
    startDate: "Beginn",
    endDate: "Ende",
    medicationStatus: "Status",
    consentForms: "Einwilligungen",
    consentTitle: "Titel",
    consentStatus: "Status",
    signedAt: "Unterzeichnet am",
    consentContent: "Inhalt",
    attachments: "Anhänge",
    fileName: "Datei",
    fileType: "Typ",
    filePath: "Pfad",
    uploadedAt: "Hochgeladen am",
    fileDescription: "Beschreibung",
    dentalChart: "Zahnstatus",
    teethInvolved: "Betroffene Zähne",
    verification: "Verifizierung",
    verificationCode: "Verifizierungscode",
    verifyAt: "Prüfen unter",
    generatedBy: "Erstellt von Docito (docito.app)",
    na: "—",
  },
};

function t(locale: Locale, key: string): string {
  return I18N[locale]?.[key] || I18N.en[key] || key;
}

function safeText(v: unknown, fallback: string): string {
  const s = typeof v === "string" ? v.trim() : "";
  return s.length ? s : fallback;
}

function isoDate(v: unknown): string | null {
  const s = typeof v === "string" ? v.trim() : "";
  if (!s) return null;
  const m = s.match(/^\d{4}-\d{2}-\d{2}/);
  return m ? m[0] : null;
}

function isoDateTime(v: unknown): string | null {
  const s = typeof v === "string" ? v.trim() : "";
  if (!s) return null;
  const d = new Date(s);
  if (isNaN(d.getTime())) return null;
  return d.toISOString().replace("T", " ").slice(0, 19) + "Z";
}

function stripHtml(input: string): string {
  // Very small sanitizer: remove tags and decode basic entities
  const noTags = input.replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<\/?[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return noTags
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/&#39;/g, "'");
}

function asString(v: any): string | null {
  if (typeof v === "string") return v;
  if (v == null) return null;
  try {
    return String(v);
  } catch {
    return null;
  }
}

function asNumber(v: any): number | null {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string") {
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function uniqNumbers(list: unknown): number[] {
  const out: number[] = [];
  const set = new Set<number>();
  if (Array.isArray(list)) {
    for (const x of list) {
      const n = asNumber(x);
      if (n != null && !set.has(n)) {
        set.add(n);
        out.push(n);
      }
    }
  }
  return out;
}

function isRtlLocale(locale: Locale): boolean {
  return locale === "ar";
}

function reverseRange(chars: string[], start: number, end: number) {
  let i = start;
  let j = end;
  while (i < j) {
    const tmp = chars[i];
    chars[i] = chars[j];
    chars[j] = tmp;
    i++;
    j--;
  }
}

function shapeArabicDisplay(text: string): string {
  try {
    const arabicShaper = (reshaper as any)?.ArabicShaper;
    const shaped = typeof arabicShaper?.convertArabic === "function"
      ? arabicShaper.convertArabic(text)
      : text;

    const bidi = (bidiFactory as any)();
    const embedding = bidi.getEmbeddingLevels(shaped, "rtl");
    const flips: Array<[number, number]> = bidi.getReorderSegments(shaped, embedding);

    const chars = shaped.split("");
    for (const [s, e] of flips) reverseRange(chars, s, e);
    return chars.join("");
  } catch {
    return text;
  }
}

function formatForLocale(locale: Locale, text: string): string {
  if (locale === "ar") return shapeArabicDisplay(text);
  return text;
}

function wrapText(font: PDFFont, text: string, fontSize: number, maxWidth: number): string[] {
  const clean = (text || "").replace(/\s+/g, " ").trim();
  if (!clean) return [];

  // Prefer space-based wrapping, but handle CJK / long tokens
  const hasSpaces = /\s/.test(clean);
  const tokens = hasSpaces ? clean.split(" ") : Array.from(clean); // grapheme-ish via codepoints

  const lines: string[] = [];
  let current = "";

  for (const token of tokens) {
    const candidate = current ? (hasSpaces ? `${current} ${token}` : `${current}${token}`) : token;
    const w = font.widthOfTextAtSize(candidate, fontSize);

    if (w <= maxWidth) {
      current = candidate;
      continue;
    }

    if (current) lines.push(current);
    current = token;

    // If a single token is wider than maxWidth (very long word), split by characters
    if (font.widthOfTextAtSize(current, fontSize) > maxWidth) {
      const chars = Array.from(current);
      let sub = "";
      for (const ch of chars) {
        const c2 = sub ? `${sub}${ch}` : ch;
        if (font.widthOfTextAtSize(c2, fontSize) <= maxWidth) {
          sub = c2;
        } else {
          if (sub) lines.push(sub);
          sub = ch;
        }
      }
      current = sub;
    }
  }

  if (current) lines.push(current);
  return lines;
}

type DrawTextOpts = {
  page: PDFPage;
  font: PDFFont;
  x: number;
  y: number;
  size: number;
  maxWidth: number;
  color?: { r: number; g: number; b: number };
  rtl?: boolean;
};

function drawWrappedText(text: string, opts: DrawTextOpts): { lines: number; yAfter: number } {
  const { page, font, x, y, size, maxWidth, color, rtl } = opts;
  const lines = wrapText(font, text, size, maxWidth);
  let yy = y;
  const gap = 14;

  for (const rawLine of lines.length ? lines : [""]) {
    const line = rawLine || "";
    if (rtl) {
      const w = font.widthOfTextAtSize(line, size);
      page.drawText(line, { x: x + maxWidth - w, y: yy, size, font, color: color ? rgb(color.r, color.g, color.b) : rgb(0.05, 0.05, 0.05) });
    } else {
      page.drawText(line, { x, y: yy, size, font, color: color ? rgb(color.r, color.g, color.b) : rgb(0.05, 0.05, 0.05) });
    }
    yy -= gap;
  }

  return { lines: lines.length || 1, yAfter: yy };
}

const FONT_URLS: Record<
  Locale,
  { url: string; kind: "ttf" | "otf" | "fallback" }
> = {
  en: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  ru: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  uz: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  tr: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  es: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  pt: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  de: { url: "https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", kind: "ttf" },
  ar: { url: "https://raw.githubusercontent.com/itext/i7js-examples/develop/src/main/resources/font/NotoNaskhArabic-Regular.ttf", kind: "ttf" },
  ja: { url: "https://raw.githubusercontent.com/notofonts/noto-cjk/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf", kind: "otf" },
  ko: { url: "https://raw.githubusercontent.com/notofonts/noto-cjk/main/Sans/OTF/Korean/NotoSansCJKkr-Regular.otf", kind: "otf" },
  zh: { url: "https://raw.githubusercontent.com/notofonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf", kind: "otf" },
};

const fontBytesCache = new Map<string, Uint8Array>();

async function fetchFontBytes(locale: Locale): Promise<Uint8Array> {
  const key = `font:${locale}`;
  const cached = fontBytesCache.get(key);
  if (cached) return cached;

  const { url } = FONT_URLS[locale];
  try {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`font fetch failed (${resp.status})`);
    const buf = new Uint8Array(await resp.arrayBuffer());
    fontBytesCache.set(key, buf);
    return buf;
  } catch {
    // Fallback: try embedded font, if invalid use null (caller uses StandardFonts)
    const fallback = b64ToBytes(DOCITO_FONT_TTF_BASE64);
    if (fallback.length > 0) {
      fontBytesCache.set(key, fallback);
      return fallback;
    }
    throw new Error("no_font_available");
  }
}

async function embedLocaleFont(pdf: PDFDocument, locale: Locale): Promise<PDFFont> {
  pdf.registerFontkit(fontkit);
  try {
    const bytes = await fetchFontBytes(locale);
    return await pdf.embedFont(bytes, { subset: true });
  } catch {
    // Fallback to built-in Helvetica if custom font unavailable
    return await pdf.embedFont(StandardFonts.Helvetica);
  }
}

async function getActorLocale(serviceClient: any, userId: string): Promise<Locale> {
  const { data } = await serviceClient
    .from("profiles")
    .select("language")
    .eq("user_id", userId)
    .maybeSingle();
  return normalizeLocale((data as any)?.language);
}

function mapUniversalToFdi(n: number): number | null {
  // Universal 1..32 -> FDI 11..48
  if (n < 1 || n > 32) return null;
  const map: Record<number, number> = {
    1: 18, 2: 17, 3: 16, 4: 15, 5: 14, 6: 13, 7: 12, 8: 11,
    9: 21, 10: 22, 11: 23, 12: 24, 13: 25, 14: 26, 15: 27, 16: 28,
    17: 38, 18: 37, 19: 36, 20: 35, 21: 34, 22: 33, 23: 32, 24: 31,
    25: 41, 26: 42, 27: 43, 28: 44, 29: 45, 30: 46, 31: 47, 32: 48,
  };
  return map[n] ?? null;
}

function normalizeToothNumberToFdi(n: number): number | null {
  // If already looks like FDI permanent range
  if (n >= 11 && n <= 48) return n;
  // Universal system
  if (n >= 1 && n <= 32) return mapUniversalToFdi(n);
  return null;
}

function drawDentalChart(params: {
  page: PDFPage;
  font: PDFFont;
  locale: Locale;
  x: number;
  yTop: number;
  width: number;
  height: number;
  highlightedFdi: Set<number>;
}) {
  const { page, font, locale, x, yTop, width, height, highlightedFdi } = params;

  const border = rgb(0.9, 0.9, 0.9);
  const labelColor = rgb(0.25, 0.25, 0.25);
  const textColor = rgb(0.05, 0.05, 0.05);
  const fillNormal = rgb(0.98, 0.98, 0.98);
  const fillHighlight = rgb(0.90, 0.95, 1.00);

  // Chart box
  page.drawRectangle({
    x,
    y: yTop - height,
    width,
    height,
    borderColor: border,
    borderWidth: 1,
    color: rgb(1, 1, 1),
  });

  const padding = 10;
  const innerX = x + padding;
  const innerW = width - padding * 2;

  const rowGap = 10;
  const rowH = (height - padding * 2 - rowGap) / 2;

  const cols = 16;
  const gap = 2;
  const boxW = (innerW - gap * (cols - 1)) / cols;
  const boxH = rowH;

  const upper: number[] = [18, 17, 16, 15, 14, 13, 12, 11, 21, 22, 23, 24, 25, 26, 27, 28];
  const lower: number[] = [48, 47, 46, 45, 44, 43, 42, 41, 31, 32, 33, 34, 35, 36, 37, 38];

  const drawRow = (row: number[], yRowTop: number) => {
    const yBox = yRowTop - boxH;

    for (let i = 0; i < cols; i++) {
      const tn = row[i];
      const isHL = highlightedFdi.has(tn);
      const bx = innerX + i * (boxW + gap);

      page.drawRectangle({
        x: bx,
        y: yBox,
        width: boxW,
        height: boxH,
        borderColor: border,
        borderWidth: 1,
        color: isHL ? fillHighlight : fillNormal,
      });

      const label = String(tn);
      const fs = 8;
      const tw = font.widthOfTextAtSize(label, fs);
      page.drawText(label, {
        x: bx + (boxW - tw) / 2,
        y: yBox + boxH / 2 - 4,
        size: fs,
        font,
        color: textColor,
      });
    }
  };

  const upperTop = yTop - padding;
  const lowerTop = yTop - padding - rowH - rowGap;

  drawRow(upper, upperTop);
  drawRow(lower, lowerTop);

  // Small legend (translated)
  const legend = `${t(locale, "teethInvolved")}: ${Array.from(highlightedFdi).sort((a, b) => a - b).join(", ") || t(locale, "na")}`;
  const rtl = isRtlLocale(locale);
  const legendText = formatForLocale(locale, legend);
  const legendY = yTop - height + 6;

  const legendSize = 9;
  const legendW = innerW;
  if (rtl) {
    const w = font.widthOfTextAtSize(legendText, legendSize);
    page.drawText(legendText, {
      x: innerX + legendW - w,
      y: legendY,
      size: legendSize,
      font,
      color: labelColor,
    });
  } else {
    page.drawText(legendText, {
      x: innerX,
      y: legendY,
      size: legendSize,
      font,
      color: labelColor,
    });
  }
}

async function safeSelectAll(serviceClient: any, table: string, queryFn: (q: any) => any): Promise<any[]> {
  try {
    const q0 = serviceClient.from(table).select("*");
    const q = queryFn(q0);
    const { data, error } = await q;
    if (error) return [];
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

async function canUserAccessTreatmentPlan(context: any, plan: any): Promise<boolean> {
  const roles: string[] = context?.roles || [];
  const userId: string | null = context?.userId || null;
  const serviceClient: any = context?.serviceClient;

  if (!userId) return false;
  if (roles.includes("super_admin")) return true;

  const patientId = asString(plan?.patient_id);
  if (patientId && patientId === userId) return true;

  const doctorId = asString(plan?.doctor_id) || asString(plan?.dentist_id);
  if (!doctorId) return false;

  try {
    const { data } = await serviceClient
      .from("doctors")
      .select("id,user_id")
      .eq("id", doctorId)
      .maybeSingle();
    const doctorUserId = asString((data as any)?.user_id);
    return !!doctorUserId && doctorUserId === userId;
  } catch {
    return false;
  }
}

async function generateTreatmentPlanPdf(params: {
  locale: Locale;
  planId: string;
  title: string;
  status: string;
  totalCost: string;
  description?: string | null;
  notes?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  publishedAt?: string | null;
  completedAt?: string | null;

  patientName: string;
  patientDob?: string | null;
  patientGender?: string | null;
  patientPhone?: string | null;
  patientEmail?: string | null;
  patientAddress?: string | null;

  doctorName: string;
  doctorSpecialty?: string | null;
  doctorPhone?: string | null;
  doctorEmail?: string | null;

  practiceName?: string | null;
  practiceAddress?: string | null;
  practicePhone?: string | null;

  procedures: Array<{
    name: string;
    status: string | null;
    cost: string | null;
    toothNumbers: number[];
    notes: string | null;
  }>;

  medications: Array<{
    name: string;
    dosage: string;
    frequency: string;
    instructions: string | null;
    startDate: string | null;
    endDate: string | null;
    status: string | null;
  }>;

  consentForms: Array<{
    title: string;
    status: string | null;
    signedAt: string | null;
    content: string | null;
  }>;

  attachments: Array<{
    fileName: string | null;
    fileType: string | null;
    filePath: string | null;
    uploadedAt: string | null;
    description: string | null;
  }>;

  verificationCode: string;
  verifyUrl: string;
}) {
  const W = 595.28;
  const H = 841.89;
  const margin = 44;

  const pdf = await PDFDocument.create();
  const font = await embedLocaleFont(pdf, params.locale);

  const logoBytes = b64ToBytes(DOCITO_LOGO_PNG_BASE64);
  let logo: Awaited<ReturnType<typeof pdf.embedPng>> | null = null;
  let logoW = 42;
  let logoH = 42;
  if (logoBytes.length > 0) {
    try {
      logo = await pdf.embedPng(logoBytes);
      logoH = (logo.height / logo.width) * logoW;
    } catch { logo = null; }
  }

  const rtl = isRtlLocale(params.locale);

  // Brand colors
  const accentColor = rgb(0.16, 0.47, 0.82); // Professional blue
  const accentLight = rgb(0.93, 0.96, 1.0);
  const sectionBg = rgb(0.95, 0.97, 1.0);
  const textDark = rgb(0.05, 0.05, 0.05);
  const textMuted = rgb(0.35, 0.35, 0.35);
  const borderLight = rgb(0.88, 0.88, 0.88);
  const rowAlt = rgb(0.97, 0.97, 0.98);

  const footerY = margin + 26;
  const bottomReserve = 120;

  let page = pdf.addPage([W, H]);
  let y = H - margin;

  const header = () => {
    y = H - margin;

    // Accent bar at very top
    page.drawRectangle({
      x: 0,
      y: H - 4,
      width: W,
      height: 4,
      color: accentColor,
    });

    // Logo left
    if (logo) {
      page.drawImage(logo, { x: margin, y: y - logoH, width: logoW, height: logoH });
    }

    // Practice name center (or docito.app if no practice)
    const centerText = params.practiceName || "Docito";
    const centerSize = 14;
    const centerW = font.widthOfTextAtSize(centerText, centerSize);
    page.drawText(centerText, {
      x: (W - centerW) / 2,
      y: y - 10,
      size: centerSize,
      font,
      color: textDark,
    });

    // Practice address below center name
    if (params.practiceAddress) {
      const addrSize = 8;
      const addrW = font.widthOfTextAtSize(params.practiceAddress, addrSize);
      page.drawText(params.practiceAddress, {
        x: (W - addrW) / 2,
        y: y - 22,
        size: addrSize,
        font,
        color: textMuted,
      });
    }

    // docito.app URL right
    const brand = "docito.app";
    const brandSize = 9;
    const brandW = font.widthOfTextAtSize(brand, brandSize);
    page.drawText(brand, {
      x: W - margin - brandW,
      y: y - 10,
      size: brandSize,
      font,
      color: accentColor,
    });

    y -= Math.max(logoH, 30) + 14;

    // Accent line under header
    page.drawRectangle({
      x: margin,
      y: y,
      width: W - margin * 2,
      height: 2,
      color: accentColor,
    });

    y -= 18;

    // Title
    const titleText = formatForLocale(params.locale, params.title || t(params.locale, "title"));
    const titleSize = 18;
    const titleW = font.widthOfTextAtSize(titleText, titleSize);

    page.drawText(titleText, {
      x: rtl ? (W - margin - titleW) : margin,
      y,
      size: titleSize,
      font,
      color: accentColor,
    });

    y -= 16;

    // "Generated by Dr. X at Practice" subtitle
    let generatedLine = "";
    if (params.doctorName && params.doctorName !== "—") {
      generatedLine = `${params.doctorName}`;
      if (params.doctorSpecialty) generatedLine += ` · ${params.doctorSpecialty}`;
      if (params.practiceName) generatedLine += ` — ${params.practiceName}`;
    }
    if (generatedLine) {
      const genLineText = formatForLocale(params.locale, generatedLine);
      const genSize = 9;
      const genW = font.widthOfTextAtSize(genLineText, genSize);
      page.drawText(genLineText, {
        x: rtl ? (W - margin - genW) : margin,
        y,
        size: genSize,
        font,
        color: textMuted,
      });
      y -= 14;
    }

    y -= 6;
  };

  const newPage = () => {
    page = pdf.addPage([W, H]);
    header();
  };

  const ensureSpace = (needed: number) => {
    if (y - needed < (margin + bottomReserve)) newPage();
  };

  header();

  const colLabelX = margin;
  const colValueX = margin + 160;
  const maxValueW = W - margin - colValueX;

  const labelSize = 10;
  const valueSize = 10;
  const lineGap = 14;

  const drawKV = (labelKey: string, rawValue: string | null | undefined) => {
    ensureSpace(2 * lineGap);

    const label = formatForLocale(params.locale, t(params.locale, labelKey));
    const value = formatForLocale(params.locale, safeText(rawValue, t(params.locale, "na")));

    const labelW = font.widthOfTextAtSize(label, labelSize);
    const labelX = rtl ? (colValueX + maxValueW - labelW) : colLabelX;

    page.drawText(label, { x: labelX, y, size: labelSize, font, color: textMuted });

    const res = drawWrappedText(value, {
      page,
      font,
      x: colValueX,
      y,
      size: valueSize,
      maxWidth: maxValueW,
      rtl,
      color: { r: 0.05, g: 0.05, b: 0.05 },
    });

    y = res.yAfter;
  };

  const drawSection = (titleKey: string) => {
    ensureSpace(40);
    y -= 6;

    const sectionTitle = formatForLocale(params.locale, t(params.locale, titleKey));
    const sectionSize = 12;
    const sectionW = font.widthOfTextAtSize(sectionTitle, sectionSize);
    const sectionPadding = 6;

    // Section header background
    page.drawRectangle({
      x: margin,
      y: y - sectionPadding,
      width: W - margin * 2,
      height: sectionSize + sectionPadding * 2,
      color: sectionBg,
    });

    // Accent left border
    page.drawRectangle({
      x: margin,
      y: y - sectionPadding,
      width: 3,
      height: sectionSize + sectionPadding * 2,
      color: accentColor,
    });

    page.drawText(sectionTitle, {
      x: rtl ? (W - margin - sectionW - 8) : margin + 10,
      y: y,
      size: sectionSize,
      font,
      color: accentColor,
    });

    y -= (sectionSize + sectionPadding * 2 + 8);
  };

  // Plan header fields
  drawKV("planId", params.planId);
  drawKV("status", params.status);
  drawKV("totalCost", params.totalCost);
  if (params.description) drawKV("description", params.description);
  if (params.notes) drawKV("notes", params.notes);
  if (params.createdAt) drawKV("createdAt", params.createdAt);
  if (params.updatedAt) drawKV("updatedAt", params.updatedAt);
  if (params.publishedAt) drawKV("publishedAt", params.publishedAt);
  if (params.completedAt) drawKV("completedAt", params.completedAt);

  // Dental chart
  const highlightedFdi = new Set<number>();
  for (const p of params.procedures) {
    for (const tn of p.toothNumbers || []) {
      const fdi = normalizeToothNumberToFdi(tn);
      if (fdi != null) highlightedFdi.add(fdi);
    }
  }

  const hasDentalContext = highlightedFdi.size > 0;

  if (hasDentalContext) {
    y -= 6;
    drawSection("dentalChart");

    const chartW = W - margin * 2;
    const chartH = 150;

    ensureSpace(chartH + 12);

    const chartTop = y + 6;
    drawDentalChart({
      page,
      font,
      locale: params.locale,
      x: margin,
      yTop: chartTop,
      width: chartW,
      height: chartH,
      highlightedFdi,
    });

    y -= (chartH + 18);
  }

  // Patient section
  y -= 6;
  drawSection("patient");
  drawKV("patient", params.patientName);
  if (params.patientDob) drawKV("dob", params.patientDob);
  if (params.patientGender) drawKV("gender", params.patientGender);
  if (params.patientPhone) drawKV("phone", params.patientPhone);
  if (params.patientEmail) drawKV("email", params.patientEmail);
  if (params.patientAddress) drawKV("address", params.patientAddress);

  // Doctor section
  y -= 6;
  drawSection("doctor");
  drawKV("doctor", params.doctorName);
  if (params.doctorSpecialty) drawKV("specialty", params.doctorSpecialty);
  if (params.doctorPhone) drawKV("phone", params.doctorPhone);
  if (params.doctorEmail) drawKV("email", params.doctorEmail);
  if (params.practiceName) {
    const practiceLabel = params.practiceName + (params.practicePhone ? ` · ${params.practicePhone}` : "");
    drawKV("notes", practiceLabel);
  }

  // Procedures table
  y -= 6;
  drawSection("procedures");
  if (!params.procedures.length) {
    drawKV("procedures", t(params.locale, "na"));
  } else {
    // Table header
    const tableX = margin;
    const colWidths = [180, 80, 70, 80, W - margin * 2 - 180 - 80 - 70 - 80];
    const headers = ["procedure", "tooth", "cost", "procedureStatus", "procedureNotes"];

    ensureSpace(30);

    // Header row background
    page.drawRectangle({
      x: tableX,
      y: y - 4,
      width: W - margin * 2,
      height: 16,
      color: accentLight,
    });

    let hx = tableX + 4;
    for (let hi = 0; hi < headers.length; hi++) {
      const hText = formatForLocale(params.locale, t(params.locale, headers[hi]));
      page.drawText(hText, { x: hx, y, size: 8, font, color: accentColor });
      hx += colWidths[hi];
    }
    y -= 18;

    for (let idx = 0; idx < params.procedures.length; idx++) {
      const p = params.procedures[idx];
      ensureSpace(20);

      // Alternating row background
      if (idx % 2 === 1) {
        page.drawRectangle({
          x: tableX,
          y: y - 4,
          width: W - margin * 2,
          height: 16,
          color: rowAlt,
        });
      }

      const teeth = (p.toothNumbers || []).map((n) => normalizeToothNumberToFdi(n) ?? n).filter((n) => n != null) as number[];
      const teethStr = teeth.length ? teeth.join(", ") : "—";
      const costStr = safeText(p.cost, "—");
      const statusStr = safeText(p.status, "—");
      const notesStr = safeText(p.notes, "");

      const rowData = [`${idx + 1}. ${p.name}`, teethStr, costStr, statusStr, notesStr];
      let rx = tableX + 4;
      const rowSize = 8;
      for (let ci = 0; ci < rowData.length; ci++) {
        const txt = formatForLocale(params.locale, rowData[ci]).slice(0, 60);
        page.drawText(txt, { x: rx, y, size: rowSize, font, color: textDark });
        rx += colWidths[ci];
      }
      y -= 16;
    }

    // Table bottom border
    page.drawLine({
      start: { x: margin, y: y + 8 },
      end: { x: W - margin, y: y + 8 },
      thickness: 0.8,
      color: borderLight,
    });
    y -= 6;
  }

  // Medications table
  y -= 6;
  drawSection("medications");
  if (!params.medications.length) {
    drawKV("medications", t(params.locale, "na"));
  } else {
    const tableX = margin;
    const medColWidths = [140, 80, 80, 80, W - margin * 2 - 140 - 80 - 80 - 80];
    const medHeaders = ["medication", "dosage", "frequency", "medicationStatus", "instructions"];

    ensureSpace(30);

    page.drawRectangle({
      x: tableX,
      y: y - 4,
      width: W - margin * 2,
      height: 16,
      color: accentLight,
    });

    let hx = tableX + 4;
    for (let hi = 0; hi < medHeaders.length; hi++) {
      const hText = formatForLocale(params.locale, t(params.locale, medHeaders[hi]));
      page.drawText(hText, { x: hx, y, size: 8, font, color: accentColor });
      hx += medColWidths[hi];
    }
    y -= 18;

    for (let i = 0; i < params.medications.length; i++) {
      const m = params.medications[i];
      ensureSpace(20);

      if (i % 2 === 1) {
        page.drawRectangle({
          x: tableX,
          y: y - 4,
          width: W - margin * 2,
          height: 16,
          color: rowAlt,
        });
      }

      const rowData = [
        `${i + 1}. ${m.name}`,
        m.dosage,
        m.frequency,
        safeText(m.status, "—"),
        safeText(m.instructions, ""),
      ];

      let rx = tableX + 4;
      for (let ci = 0; ci < rowData.length; ci++) {
        const txt = formatForLocale(params.locale, rowData[ci]).slice(0, 50);
        page.drawText(txt, { x: rx, y, size: 8, font, color: textDark });
        rx += medColWidths[ci];
      }
      y -= 16;

      // Date range below if present
      if (m.startDate || m.endDate) {
        ensureSpace(14);
        const dateStr = `${m.startDate || "?"} → ${m.endDate || "?"}`;
        page.drawText(dateStr, { x: tableX + 8, y, size: 7, font, color: textMuted });
        y -= 12;
      }
    }

    page.drawLine({
      start: { x: margin, y: y + 8 },
      end: { x: W - margin, y: y + 8 },
      thickness: 0.8,
      color: borderLight,
    });
    y -= 6;
  }

  // Consent Forms
  y -= 6;
  drawSection("consentForms");
  if (!params.consentForms.length) {
    drawKV("consentForms", t(params.locale, "na"));
  } else {
    for (let i = 0; i < params.consentForms.length; i++) {
      const c = params.consentForms[i];
      ensureSpace(90);

      const head = formatForLocale(params.locale, `${i + 1}. ${c.title}`);
      const headSize = 11;
      const headW = font.widthOfTextAtSize(head, headSize);

      page.drawText(head, { x: rtl ? (W - margin - headW) : margin, y, size: headSize, font, color: textDark });
      y -= 14;

      if (c.status) drawKV("consentStatus", c.status);
      if (c.signedAt) drawKV("signedAt", c.signedAt);
      if (c.content) drawKV("consentContent", c.content);

      y -= 6;
      page.drawLine({
        start: { x: margin, y },
        end: { x: W - margin, y },
        thickness: 0.8,
        color: borderLight,
      });
      y -= 12;
    }
  }

  // Attachments
  y -= 6;
  drawSection("attachments");
  if (!params.attachments.length) {
    drawKV("attachments", t(params.locale, "na"));
  } else {
    for (let i = 0; i < params.attachments.length; i++) {
      const a = params.attachments[i];
      ensureSpace(80);

      const head = formatForLocale(params.locale, `${i + 1}. ${safeText(a.fileName, t(params.locale, "na"))}`);
      const headSize = 11;
      const headW = font.widthOfTextAtSize(head, headSize);

      page.drawText(head, { x: rtl ? (W - margin - headW) : margin, y, size: headSize, font, color: textDark });
      y -= 14;

      if (a.fileType) drawKV("fileType", a.fileType);
      if (a.filePath) drawKV("filePath", a.filePath);
      if (a.uploadedAt) drawKV("uploadedAt", a.uploadedAt);
      if (a.description) drawKV("fileDescription", a.description);

      y -= 6;
      page.drawLine({
        start: { x: margin, y },
        end: { x: W - margin, y },
        thickness: 0.8,
        color: borderLight,
      });
      y -= 12;
    }
  }

  // Footer on last page
  if (y < margin + bottomReserve) newPage();

  // Footer accent bar
  page.drawRectangle({
    x: margin,
    y: footerY + 28,
    width: W - margin * 2,
    height: 2,
    color: accentColor,
  });

  const genText = formatForLocale(params.locale, t(params.locale, "generatedBy"));
  const genSize = 9;
  const genW = font.widthOfTextAtSize(genText, genSize);
  page.drawText(genText, {
    x: rtl ? (W - margin - genW) : margin,
    y: footerY + 10,
    size: genSize,
    font,
    color: accentColor,
  });

  // Practice + Doctor footer line
  if (params.practiceName || params.doctorName) {
    const footerInfo = [params.doctorName, params.practiceName].filter(Boolean).join(" · ");
    const fiSize = 8;
    const fiW = font.widthOfTextAtSize(footerInfo, fiSize);
    page.drawText(footerInfo, {
      x: rtl ? (W - margin - fiW) : margin,
      y: footerY,
      size: fiSize,
      font,
      color: textMuted,
    });
  }

  const verificationLabel = formatForLocale(params.locale, t(params.locale, "verification") + ":");
  const verificationLabelSize = 10;
  const verificationLabelW = font.widthOfTextAtSize(verificationLabel, verificationLabelSize);

  page.drawText(verificationLabel, {
    x: rtl ? (W - margin - verificationLabelW) : margin,
    y: footerY + 44,
    size: verificationLabelSize,
    font,
    color: textMuted,
  });

  const vCodeLine = formatForLocale(params.locale, `${t(params.locale, "verificationCode")}: ${params.verificationCode}`);
  const vUrlLine = formatForLocale(params.locale, `${t(params.locale, "verifyAt")}: ${params.verifyUrl}`);

  const vSize = 9;
  const v1W = font.widthOfTextAtSize(vCodeLine, vSize);
  const v2W = font.widthOfTextAtSize(vUrlLine, vSize);

  page.drawText(vCodeLine, {
    x: rtl ? (W - margin - v1W) : margin,
    y: footerY + 30,
    size: vSize,
    font,
    color: textDark,
  });

  page.drawText(vUrlLine, {
    x: rtl ? (W - margin - v2W) : margin,
    y: footerY + 18,
    size: vSize,
    font,
    color: textDark,
  });

  // QR code
  try {
    const dataUrl = await QRCode.toDataURL(params.verifyUrl, { margin: 1, width: 140 });
    const b64 = dataUrl.split(",")[1] || "";
    if (b64) {
      const qrBytes = b64ToBytes(b64);
      const qr = await pdf.embedPng(qrBytes);
      const qrW = 92;
      const qrH = 92;

      page.drawImage(qr, {
        x: W - margin - qrW,
        y: footerY + 8,
        width: qrW,
        height: qrH,
      });
    }
  } catch {
    // ignore QR failures
  }

  const bytes = await pdf.save();
  return bytes;
}

serve(async (req: Request) => {
  const sec = await secureHandler(req, "treatment-plan-generate-pdf", {
    requireAuth: true,
    allowedMethods: ["POST", "OPTIONS"],
    rateLimit: "STANDARD",
    validationSchema: schema,
    logRequests: false,
  });

  if (sec.response) return sec.response;

  const context = sec.context!;
  const body = sec.validatedBody as ReqBody;

  const { serviceClient, userId } = context;

  if (!userId) return errorResponse("Unauthorized", 401);

  // Locale: request overrides, otherwise use profile language
  const locale = body.locale ? normalizeLocale(body.locale) : await getActorLocale(serviceClient, userId);

  // Fetch treatment plan
  const { data: plan, error: planError } = await serviceClient
    .from("treatment_plans")
    .select("*")
    .eq("id", body.treatment_plan_id)
    .maybeSingle();

  if (planError || !plan) {
    return errorResponse("Treatment plan not found", 404);
  }

  // Access control (service role bypasses RLS, so enforce)
  const ok = await canUserAccessTreatmentPlan(context, plan);
  if (!ok) return errorResponse("Forbidden", 403);

  const planId = asString((plan as any)?.id) || body.treatment_plan_id;
  const patientId = asString((plan as any)?.patient_id);
  const providerId = asString((plan as any)?.doctor_id) || asString((plan as any)?.dentist_id);

  // Patient profile
  const { data: patientProfile } = patientId
    ? await serviceClient
      .from("profiles")
      .select("full_name, phone, email, date_of_birth, gender, address")
      .eq("user_id", patientId)
      .maybeSingle()
    : { data: null };

  // Doctor/dentist + profile
  let doctorName = "—";
  let doctorSpecialty: string | null = null;
  let doctorPhone: string | null = null;
  let doctorEmail: string | null = null;
  let practiceName: string | null = null;
  let practiceAddress: string | null = null;
  let practicePhone: string | null = null;

  if (providerId) {
    const { data: doctorRow } = await serviceClient
      .from("doctors")
      .select("id, user_id, specialty, specialty_en, specialty_ru, specialty_uz, specialty_ar, practice_id")
      .eq("id", providerId)
      .maybeSingle();

    const doctorUserId = asString((doctorRow as any)?.user_id);
    const practiceId = asString((doctorRow as any)?.practice_id);
    const specKey = locale === "ru"
      ? "specialty_ru"
      : locale === "uz"
        ? "specialty_uz"
        : locale === "ar"
          ? "specialty_ar"
          : "specialty_en";

    doctorSpecialty = asString((doctorRow as any)?.[specKey]) || asString((doctorRow as any)?.specialty) || null;

    if (doctorUserId) {
      const { data: doctorProfile } = await serviceClient
        .from("profiles")
        .select("full_name, phone, email")
        .eq("user_id", doctorUserId)
        .maybeSingle();

      doctorName = safeText((doctorProfile as any)?.full_name, "—");
      doctorPhone = asString((doctorProfile as any)?.phone);
      doctorEmail = asString((doctorProfile as any)?.email);
    }

    // Fetch practice info
    if (practiceId) {
      const { data: practiceRow } = await serviceClient
        .from("practices")
        .select("name, address, phone")
        .eq("id", practiceId)
        .maybeSingle();

      practiceName = asString((practiceRow as any)?.name);
      practiceAddress = asString((practiceRow as any)?.address);
      practicePhone = asString((practiceRow as any)?.phone);
    }
  }

  const patientName = safeText((patientProfile as any)?.full_name, "—");
  const patientDob = isoDate((patientProfile as any)?.date_of_birth);
  const patientGender = asString((patientProfile as any)?.gender);
  const patientPhone = asString((patientProfile as any)?.phone);
  const patientEmail = asString((patientProfile as any)?.email);
  const patientAddress = asString((patientProfile as any)?.address);

  // Procedures
  let proceduresRaw: any[] = [];
  try {
    const q = serviceClient
      .from("treatment_plan_procedures")
      .select("*, procedures:procedure_id(*)")
      .eq("treatment_plan_id", planId);

    // Some schemas have sequence_order; fallback safely if ordering fails
    const { data: ordered, error: orderErr } = await q.order("sequence_order", { ascending: true });
    if (!orderErr && Array.isArray(ordered)) proceduresRaw = ordered;
    else {
      const { data: fallback } = await serviceClient
        .from("treatment_plan_procedures")
        .select("*, procedures:procedure_id(*)")
        .eq("treatment_plan_id", planId)
        .order("created_at", { ascending: true });
      proceduresRaw = Array.isArray(fallback) ? fallback : [];
    }
  } catch {
    proceduresRaw = [];
  }

  const procedures = proceduresRaw.map((row) => {
    const proc = (row as any)?.procedures || {};
    const name = safeText(proc?.name, safeText((row as any)?.name, "—"));

    const toothNumbers = uniqNumbers((row as any)?.tooth_numbers);

    // cost fields differ across migrations
    const cost =
      asNumber((row as any)?.custom_cost) ??
      asNumber((row as any)?.cost) ??
      asNumber((row as any)?.custom_cost) ??
      asNumber(proc?.default_cost) ??
      0;

    const notes =
      asString((row as any)?.custom_notes) ??
      asString((row as any)?.notes) ??
      null;

    const status = asString((row as any)?.status) ?? null;

    return {
      name,
      status,
      cost: Number.isFinite(cost) ? `${cost}` : null,
      toothNumbers,
      notes,
    };
  });

  // Medications
  const medicationsRaw = await safeSelectAll(serviceClient, "medications", (q) =>
    q.eq("treatment_plan_id", planId).order("created_at", { ascending: true })
  );

  const medications = medicationsRaw.map((m) => ({
    name: safeText((m as any)?.name, "—"),
    dosage: safeText((m as any)?.dosage, "—"),
    frequency: safeText((m as any)?.frequency, "—"),
    instructions: asString((m as any)?.instructions),
    startDate: isoDate((m as any)?.start_date),
    endDate: isoDate((m as any)?.end_date),
    status: asString((m as any)?.status),
  }));

  // Consent forms
  const consentsRaw = await safeSelectAll(serviceClient, "consent_forms", (q) =>
    q.eq("treatment_plan_id", planId).order("created_at", { ascending: true })
  );

  const consentForms = consentsRaw.map((c) => {
    const rawContent = asString((c as any)?.content);
    const content = rawContent ? stripHtml(rawContent) : null;
    return {
      title: safeText((c as any)?.title, "—"),
      status: asString((c as any)?.status),
      signedAt: isoDateTime((c as any)?.signed_at),
      content,
    };
  });

  // Attachments (support multiple schema/table names)
  const attachmentsA = await safeSelectAll(serviceClient, "procedure_attachments", (q) =>
    q.eq("treatment_plan_id", planId).order("created_at", { ascending: true })
  );

  // Some installs may use procedure_files linked by procedure_id; fetch by procedures list if present
  const procedureIds = proceduresRaw.map((r) => asString((r as any)?.procedure_id)).filter(Boolean) as string[];
  const attachmentsB = procedureIds.length
    ? await safeSelectAll(serviceClient, "procedure_files", (q) =>
      q.in("procedure_id", procedureIds).order("created_at", { ascending: true })
    )
    : [];

  const attachmentsUnified = [...attachmentsA, ...attachmentsB];

  const attachments = attachmentsUnified.map((a) => ({
    fileName: asString((a as any)?.file_name) || asString((a as any)?.filename) || asString((a as any)?.name) || null,
    fileType: asString((a as any)?.file_type) || asString((a as any)?.mime_type) || null,
    filePath: asString((a as any)?.file_path) || asString((a as any)?.path) || null,
    uploadedAt: isoDateTime((a as any)?.created_at) || isoDateTime((a as any)?.uploaded_at) || null,
    description: asString((a as any)?.description) || null,
  }));

  // Verification code (prefer dedicated column if present; fallback to plan ID)
  const verificationCode =
    asString((plan as any)?.verification_code) ||
    asString((plan as any)?.public_code) ||
    planId;

  const verifyUrl = `https://docito.app`;

  const status = safeText((plan as any)?.status, "—");
  const totalCostNum = asNumber((plan as any)?.total_cost) ?? asNumber((plan as any)?.totalCost) ?? 0;

  const title = safeText((plan as any)?.title, t(locale, "title"));
  const description = asString((plan as any)?.description) || null;
  const notes = asString((plan as any)?.notes) || null;

  const createdAt = isoDateTime((plan as any)?.created_at);
  const updatedAt = isoDateTime((plan as any)?.updated_at);
  const publishedAt = isoDateTime((plan as any)?.published_at);
  const completedAt = isoDateTime((plan as any)?.completed_at);

  const pdfBytes = await generateTreatmentPlanPdf({
    locale,
    planId,
    title,
    status,
    totalCost: `${totalCostNum}`,
    description: description ? formatForLocale(locale, description) : null,
    notes: notes ? formatForLocale(locale, notes) : null,
    createdAt,
    updatedAt,
    publishedAt,
    completedAt,

    patientName: formatForLocale(locale, patientName),
    patientDob,
    patientGender: patientGender ? formatForLocale(locale, patientGender) : null,
    patientPhone,
    patientEmail,
    patientAddress,

    doctorName: formatForLocale(locale, doctorName),
    doctorSpecialty: doctorSpecialty ? formatForLocale(locale, doctorSpecialty) : null,
    doctorPhone,
    doctorEmail,

    practiceName: practiceName ? formatForLocale(locale, practiceName) : null,
    practiceAddress: practiceAddress ? formatForLocale(locale, practiceAddress) : null,
    practicePhone,

    procedures: procedures.map((p) => ({
      ...p,
      name: formatForLocale(locale, p.name),
      notes: p.notes ? formatForLocale(locale, p.notes) : null,
      status: p.status ? formatForLocale(locale, p.status) : null,
    })),

    medications: medications.map((m) => ({
      ...m,
      name: formatForLocale(locale, m.name),
      dosage: formatForLocale(locale, m.dosage),
      frequency: formatForLocale(locale, m.frequency),
      instructions: m.instructions ? formatForLocale(locale, m.instructions) : null,
      status: m.status ? formatForLocale(locale, m.status) : null,
    })),

    consentForms: consentForms.map((c) => ({
      ...c,
      title: formatForLocale(locale, c.title),
      status: c.status ? formatForLocale(locale, c.status) : null,
      content: c.content ? formatForLocale(locale, c.content) : null,
    })),

    attachments: attachments.map((a) => ({
      ...a,
      fileName: a.fileName ? formatForLocale(locale, a.fileName) : null,
      fileType: a.fileType ? formatForLocale(locale, a.fileType) : null,
      filePath: a.filePath ? a.filePath : null,
      description: a.description ? formatForLocale(locale, a.description) : null,
    })),

    verificationCode,
    verifyUrl,
  });

  const filenameSafe = verificationCode.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64);
  const filename = `treatment-plan-${filenameSafe}.pdf`;

  return new Response(pdfBytes as unknown as BodyInit, {
    status: 200,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
});
