// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the id and email of the signed-in Docito user. Use to verify the MCP connection is working.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-appointments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const token = ctx.getToken();
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-appointments.ts
var list_my_appointments_default = defineTool2({
  name: "list_my_appointments",
  title: "List my appointments",
  description: "List the signed-in user's own Docito appointments (as patient or doctor). RLS enforces access.",
  inputSchema: {
    limit: z.number().int().describe("Max rows to return. Defaults to 20; clamped to [1, 100].").optional(),
    status: z.string().describe("Optional appointment status filter (e.g. 'pending', 'confirmed', 'completed').").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const clamped = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("appointments").select(
      "id, appointment_date, start_time, end_time, status, appointment_type, doctor_id, patient_id, practice_id, notes"
    ).order("appointment_date", { ascending: false }).limit(clamped);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, rows }
    };
  }
});

// src/lib/mcp/tools/list-my-prescriptions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_my_prescriptions_default = defineTool3({
  name: "list_my_prescriptions",
  title: "List my prescriptions",
  description: "List the signed-in user's own Docito prescriptions. RLS enforces access \u2014 patients see their prescriptions; doctors see those they issued.",
  inputSchema: {
    limit: z2.number().int().describe("Max rows to return. Defaults to 20; clamped to [1, 100].").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const clamped = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("prescriptions").select("*").order("created_at", { ascending: false }).limit(clamped);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, rows }
    };
  }
});

// src/lib/mcp/tools/list-my-treatment-plans.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_treatment_plans_default = defineTool4({
  name: "list_my_treatment_plans",
  title: "List my treatment plans",
  description: "List the signed-in user's own Docito treatment plans. RLS enforces access.",
  inputSchema: {
    limit: z3.number().int().describe("Max rows to return. Defaults to 20; clamped to [1, 100].").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const clamped = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("treatment_plans").select("*").order("created_at", { ascending: false }).limit(clamped);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gswwpjdtgsxzcsnrxutu";
var mcp_default = defineMcp({
  name: "docito-mcp",
  title: "Docito",
  version: "0.1.0",
  instructions: "Docito MCP tools act as the signed-in user. Use `whoami` to verify connectivity, then `list_my_appointments`, `list_my_prescriptions`, or `list_my_treatment_plans` to read the caller's own healthcare data. All tools respect Docito's row-level security \u2014 a user only ever sees records they are authorized to see in the app.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_my_appointments_default,
    list_my_prescriptions_default,
    list_my_treatment_plans_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
