// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxqhtpvxfhnneeervqsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cWh0cHZ4ZmhubmVlZXJ2cXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDI3NjAsImV4cCI6MjA3MjAxODc2MH0.d-K18jBuWxFhj3hGECvvQZSR5arV3ZwRyaRZh4KwsNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});